@startuml
class ApiAttributeSetDataController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<FormViewModel>>>
    + <<async>> Init(attributeSetName:string) : Task<ActionResult<UpdateViewModel>>
}
class "BaseAuthorizedRestApiController`5"<T1,T2,T3,T4,T5> {
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixAttributeSetData,FormViewModel,FormViewModel,FormViewModel>" <|-- ApiAttributeSetDataController
@enduml
