@startuml
class AttributeSetDataPortalController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<FormViewModel>>>
    + <<async>> GetAdditionalData() : Task<ActionResult<PaginationModel<AdditionalViewModel>>>
    + <<async>> SaveAdditionalData(data:AdditionalViewModel) : Task<IActionResult>
    + <<async>> Init(attributeSet:string) : Task<ActionResult<FormViewModel>>
    + <<async>> Export() : Task<ActionResult>
    + <<async>> ImportData(attributeSetName:string, file:IFormFile) : Task<ActionResult<RepositoryResponse<ImportViewModel>>>
    + <<override>> <<async>> Delete(id:string) : Task<ActionResult<MixAttributeSetData>>
}
class "BaseAuthorizedRestApiController`5"<T1,T2,T3,T4,T5> {
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixAttributeSetData,FormViewModel,FormViewModel,DeleteViewModel>" <|-- AttributeSetDataPortalController
@enduml
