@startuml
class SiteStructureViewModel {
    + Pages : List<MixPages.ImportViewModel> <<get>> <<set>>
    + Modules : List<MixModules.ImportViewModel> <<get>> <<set>>
    + AttributeSets : List<MixAttributeSets.ImportViewModel> <<get>> <<set>>
    + Configurations : List<MixConfigurations.ImportViewModel> <<get>> <<set>>
    + Languages : List<MixLanguages.ImportViewModel> <<get>> <<set>>
    + RelatedData : List<MixRelatedAttributeDatas.ImportViewModel> <<get>> <<set>>
    + PagePostNavs : List<MixPagePosts.ImportViewModel> <<get>> <<set>>
    + PageModuleNavs : List<MixPageModules.ImportViewModel> <<get>> <<set>>
    + ModulePostNavs : List<MixModulePosts.ImportViewModel> <<get>> <<set>>
    + Posts : List<MixPosts.ImportViewModel> <<get>> <<set>>
    + ModuleDatas : List<MixModuleDatas.ImportViewModel> <<get>> <<set>>
    + AttributeSetDatas : List<MixAttributeSetDatas.ImportViewModel> <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + ThemeName : string <<get>> <<set>>
    + SiteStructureViewModel()
    + <<async>> InitAsync(culture:string) : Task
    + ExportSelectedItemsAsync() : RepositoryResponse<string>
    - ExportDatas(context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportAttributeSetsAsync(context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportPages(context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportPageModuleNav(item:MixPages.ImportViewModel, context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportPagePostNav(item:MixPages.ImportViewModel, context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportModules(context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportModuleDatas(item:MixModules.ImportViewModel, context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportModulePostNavs(item:MixModules.ImportViewModel, context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportAdditionalData(id:string, type:MixDatabaseParentType, context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportAttributeSetData(context:MixCmsContext, transaction:IDbContextTransaction) : void
    - ExportRelatedDatas(context:MixCmsContext, transaction:IDbContextTransaction) : void
    dicConfigurationIds : Dictionary<int, int>
    dicLanguageIds : Dictionary<int, int>
    dicModuleIds : Dictionary<int, int>
    dicPostIds : Dictionary<int, int>
    dicPageIds : Dictionary<int, int>
    dicFieldIds : Dictionary<int, int>
    dicAttributeSetIds : Dictionary<int, int>
    + <<async>> ImportAsync(destCulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportModulesAsync(destCulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportPostsAsync(destCulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportAttributeSetsAsync(context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportConfigurationsAsync(destCulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportLanguagesAsync(destCulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportPagesAsync(destCulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportAttributeSetDatas(destCulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportRelatedDatas(desCulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportPagePostNavs(desCulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportPageModuleNavs(desCulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportModulePostNavs(desCulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportModuleDatas(desCulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - <<async>> ImportRelatedAttributeSetDatas(desCulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
}
@enduml
