@startuml
class DashboardViewModel {
    + TotalPage : int <<get>> <<set>>
    + TotalPost : int <<get>> <<set>>
    + TotalProduct : int <<get>> <<set>>
    + TotalModule : int <<get>> <<set>>
    + TotalUser : int <<get>> <<set>>
    + DashboardViewModel(culture:string)
}
@enduml
