@startuml
class MyFieldResolver {
    + MyFieldResolver(tableMetadata:TableMetadata, dbContext:DbContext)
    + Resolve(context:IResolveFieldContext) : object
}
IFieldResolver <|-- MyFieldResolver
@enduml
