@startuml
class Aspnetuserroles <<partial>> {
    + UserId : string <<get>> <<set>>
    + RoleId : string <<get>> <<set>>
    + ApplicationUserId : string <<get>> <<set>>
}
Aspnetuserroles --> "ApplicationUser" Aspnetusers
Aspnetuserroles --> "Role" Aspnetroles
Aspnetuserroles --> "User" Aspnetusers
@enduml
