@startuml
class MixModulePost <<partial>> {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + PostId : int <<get>> <<set>>
    + ModuleId : int <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
}
MixModulePost --> "CreatedDateTime" DateTime
MixModulePost --> "Status" MixContentStatus
MixModulePost --> "MixModule" MixModule
MixModulePost --> "MixPost" MixPost
@enduml
