@startuml
class MixPost <<partial>> {
    + MixPost()
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + PublishedDateTime : DateTime? <<get>> <<set>>
    + Excerpt : string <<get>> <<set>>
    + ExtraProperties : string <<get>> <<set>>
    + Icon : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + SeoDescription : string <<get>> <<set>>
    + SeoKeywords : string <<get>> <<set>>
    + SeoName : string <<get>> <<set>>
    + SeoTitle : string <<get>> <<set>>
    + Source : string <<get>> <<set>>
    + Tags : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Type : string <<get>> <<set>>
    + Views : int? <<get>> <<set>>
    + ExtraFields : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
}
class "ICollection`1"<T> {
}
MixPost --> "CreatedDateTime" DateTime
MixPost --> "Status" MixContentStatus
MixPost --> "SpecificultureNavigation" MixCulture
MixPost --> "MixModuleData<MixModuleData>" "ICollection`1"
MixPost --> "MixModulePost<MixModulePost>" "ICollection`1"
MixPost --> "MixPagePost<MixPagePost>" "ICollection`1"
MixPost --> "MixPostMedia<MixPostMedia>" "ICollection`1"
MixPost --> "MixPostModule<MixPostModule>" "ICollection`1"
MixPost --> "MixRelatedPostMixPost<MixRelatedPost>" "ICollection`1"
MixPost --> "MixRelatedPostS<MixRelatedPost>" "ICollection`1"
@enduml
