@startuml
class MixPagePost <<partial>> {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + PostId : int <<get>> <<set>>
    + PageId : int <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
}
MixPagePost --> "CreatedDateTime" DateTime
MixPagePost --> "Status" MixContentStatus
MixPagePost --> "MixPage" MixPage
MixPagePost --> "MixPost" MixPost
@enduml
