@startuml
class Refreshtokens <<partial>> {
    + Id : string <<get>> <<set>>
    + ClientId : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + Username : string <<get>> <<set>>
}
Refreshtokens --> "ExpiresUtc" DateTime
Refreshtokens --> "IssuedUtc" DateTime
@enduml
