@startuml
class FieldConfigurations {
    + Upload : UploadConfigurations <<get>> <<set>>
}
class UploadConfigurations {
    + ArrayAccepts : JArray <<get>> <<set>>
    + Accepts : string <<get>>
    + Width : int? <<get>> <<set>>
    + Height : int? <<get>> <<set>>
    + IsCrop : bool <<get>> <<set>>
}
@enduml
