@startuml
class MixFolders {
    + <<const>> WebRootPath : string = "wwwroot"
    + <<const>> TemplatesFolder : string = "Views/Shared/Templates"
    + <<const>> JsonDataFolder : string = "MixContent/data"
    + <<const>> MixCacheFolder : string = "MixContent/cache"
    + <<const>> MixLogsFolder : string = "MixContent/logs"
    + <<const>> ExportFolder : string = "mix-content/exports"
    + <<const>> ImportFolder : string = "mix-content/imports/themes"
    + <<const>> SiteContentAssetsFolder : string = "mix-content/assets"
    + <<const>> SiteContentUploadsFolder : string = "mix-content/uploads"
}
@enduml
