@startuml
class MixTemplateFolders <<static>> {
    + <<const>> Masters : string = "Masters"
    + <<const>> Layouts : string = "Layouts"
    + <<const>> Pages : string = "Pages"
    + <<const>> Posts : string = "Posts"
    + <<const>> Modules : string = "Modules"
    + <<const>> Forms : string = "Forms"
    + <<const>> Edms : string = "Edms"
}
@enduml
