@startuml
class ServiceCollectionExtensions <<static>> {
    + {static} AddMixSignalR(services:IServiceCollection) : IServiceCollection
    + {static} UseMixSignalR(app:IApplicationBuilder) : IApplicationBuilder
}
@enduml
