@startuml
class ApiModulePostMvcController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<ReadMvcViewModel>>>
}
"BaseAuthorizedRestApiController`4" "<MixCmsContext,MixModulePost,ReadMvcViewModel,ReadMvcViewModel>" <|-- ApiModulePostMvcController
@enduml
