@startuml
class MixAppSettingKeywords {
    + <<const>> SiteName : string = "SiteName"
    + <<const>> ConnectionString : string = "ConnectionString"
    + <<const>> OrderBy : string = "OrderBy"
    + <<const>> DefaultBlankTemplateFolder : string = "DefaultTemplateFolder"
    + <<const>> DefaultTemplateFolder : string = "DefaultTemplateFolder"
    + <<const>> Language : string = "Language"
    + <<const>> DefaultStatus : string = "DefaultContentStatus"
    + <<const>> DefaultCulture : string = "DefaultCulture"
    + <<const>> IsMysql : string = "IsMysql"
    + <<const>> Domain : string = "Domain"
    + <<const>> PortalThemeSettings : string = "PortalThemeSettings"
    + <<const>> ThemeId : string = "ThemeId"
    + <<const>> ThemeName : string = "ThemeName"
    + <<const>> ThemeFolder : string = "ThemeFolder"
    + <<const>> ApiEncryptKey : string = "ApiEncryptKey"
    + <<const>> ApiEncryptIV : string = "ApiEncryptIV"
    + <<const>> IsEncryptApi : string = "IsEncryptApi"
    + <<const>> TemplateExtension : string = "TemplateExtension"
    + <<const>> DefaultTheme : string = "DefaultTheme"
    + <<const>> DefaultTemplate : string = "DefaultTemplate"
    + <<const>> DefaultTemplateContent : string = "DefaultTemplateContent"
    + <<const>> DefaultContentStatus : string = "DefaultContentStatus"
    + <<const>> NextSyncContent : string = "NextSyncContent"
    + <<const>> AllowedHosts : string = "AllowedHosts"
}
@enduml
