@startuml
class ReadListItemViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + FormTemplate : string <<get>> <<set>>
    + EdmTemplate : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Fields : string <<get>> <<set>>
    + PageSize : int? <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + ImageUrl : string <<get>>
    + ThumbnailUrl : string <<get>>
    + DetailsUrl : string <<get>>
    + ReadListItemViewModel()
    + ReadListItemViewModel(model:MixModule, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixModule,ReadListItemViewModel>" <|-- ReadListItemViewModel
ReadListItemViewModel --> "Cultures<Domain.Core.Models.SupportedCulture>" "List`1"
ReadListItemViewModel --> "Type" MixModuleType
ReadListItemViewModel --> "CreatedDateTime" DateTime
ReadListItemViewModel --> "Status" MixContentStatus
@enduml
