@startuml
class ModelBuilderExtensions <<static>> {
    + {static} ApplyAllConfigurationsFromNamespace(modelBuilder:ModelBuilder, assembly:Assembly, ns:string) : ModelBuilder
    + {static} ApplyPostgresIddentityConfigurations(modelBuilder:ModelBuilder) : ModelBuilder
    + {static} ApplyIddentityConfigurations(modelBuilder:ModelBuilder) : ModelBuilder
}
@enduml
