@startuml
class UpdateRolePermissionViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + TextKeyword : string <<get>> <<set>>
    + TextDefault : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Descriotion : string <<get>> <<set>>
    + Icon : string <<get>> <<set>>
    + Url : string <<get>> <<set>>
    + Level : int <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + UpdateRolePermissionViewModel()
    + UpdateRolePermissionViewModel(model:MixPortalPage, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixPortalPage,UpdateRolePermissionViewModel>" <|-- UpdateRolePermissionViewModel
UpdateRolePermissionViewModel --> "CreatedDateTime" DateTime
UpdateRolePermissionViewModel --> "Status" MixContentStatus
UpdateRolePermissionViewModel o-> "ChildPages<MixPortalPagePortalPages.UpdateViewModel>" "List`1"
@enduml
