@startuml
class ApiInitCmsController {
    - <<readonly>> _userManager : UserManager<ApplicationUser>
    - <<readonly>> _signInManager : SignInManager<ApplicationUser>
    - <<readonly>> _roleManager : RoleManager<IdentityRole>
    - <<readonly>> _idHelper : IdentityHelper
    + ApiInitCmsController(userManager:UserManager<ApplicationUser>, signInManager:SignInManager<ApplicationUser>, roleManager:RoleManager<IdentityRole>, hubContext:Microsoft.AspNetCore.SignalR.IHubContext<Mix.Cms.Service.SignalR.Hubs.PortalHub>, memoryCache:IMemoryCache)
    + <<async>> Step1(model:InitCmsViewModel) : Task<RepositoryResponse<bool>>
    + <<async>> InitSuperAdmin(model:MixRegisterViewModel) : Task<RepositoryResponse<AccessTokenViewModel>>
    + <<async>> InitLanguages(model:List<MixLanguage>) : Task<RepositoryResponse<bool>>
    + <<async>> Save(model:string, assets:IFormFile, theme:IFormFile) : Task<RepositoryResponse<Cms.Lib.ViewModels.MixThemes.InitViewModel>>
    - <<async>> InitStep1Async(model:InitCmsViewModel) : Task<RepositoryResponse<bool>>
    - <<async>> InitRolesAsync() : Task<bool>
}
"BaseApiController`1" "<MixCmsContext>" <|-- ApiInitCmsController
@enduml
