@startuml
class ApiPagePostController {
    + ApiPagePostController(context:MixCmsContext, memoryCache:IMemoryCache, hubContext:Microsoft.AspNetCore.SignalR.IHubContext<Mix.Cms.Service.SignalR.Hubs.PortalHub>)
    + <<async>> DeleteAsync(id:int) : Task<RepositoryResponse<MixPagePost>>
    + <<async>> Details(viewType:string, pageId:int?, postId:int?) : Task<ActionResult<JObject>>
    + <<async>> Save(model:ReadViewModel) : Task<RepositoryResponse<ReadViewModel>>
    + <<async>> SaveFields(pageId:int, postId:int, fields:List<EntityField>) : Task<RepositoryResponse<MixPagePost>>
    + <<async>> GetList(request:RequestPaging) : Task<ActionResult<JObject>>
    + <<async>> UpdateInfos(models:List<ReadViewModel>) : Task<RepositoryResponse<List<ReadViewModel>>>
    + <<async>> SaveList(models:List<ReadViewModel>) : Task<RepositoryResponse<List<ReadViewModel>>>
}
"BaseGenericApiController`2" "<MixCmsContext,MixPagePost>" <|-- ApiPagePostController
@enduml
