@startuml
class ApiRoleController {
    # <<readonly>> _userManager : UserManager<ApplicationUser>
    # <<readonly>> _signInManager : SignInManager<ApplicationUser>
    # <<readonly>> _roleManager : RoleManager<IdentityRole>
    # <<readonly>> _logger : ILogger
    + ApiRoleController(userManager:UserManager<ApplicationUser>, signInManager:SignInManager<ApplicationUser>, roleManager:RoleManager<IdentityRole>, logger:ILogger<ApiRoleController>, memoryCache:IMemoryCache, hubContext:IHubContext<PortalHub>)
    + Claims() : object
    + <<async>> GetDetails(id:string, viewType:string) : Task<JObject>
    + <<async>> GetPermissions() : Task<JObject>
    + <<async>> GetList() : Task<RepositoryResponse<List<RoleViewModel>>>
    + <<async>> Save(name:string) : Task<RepositoryResponse<IdentityRole>>
    + <<async>> Save(model:UpdateViewModel) : Task<RepositoryResponse<UpdateViewModel>>
    + <<async>> Update(model:Lib.ViewModels.MixPortalPageRoles.ReadViewModel) : Task<RepositoryResponse<Lib.ViewModels.MixPortalPageRoles.ReadViewModel>>
    + <<async>> Delete(name:string) : Task<RepositoryResponse<AspNetRoles>>
}
"BaseApiController`1" "<MixCmsContext>" <|-- ApiRoleController
@enduml
