@startuml
class ApiTemplateController {
    + ApiTemplateController(context:MixCmsContext, memoryCache:IMemoryCache, hubContext:Microsoft.AspNetCore.SignalR.IHubContext<Mix.Cms.Service.SignalR.Hubs.PortalHub>)
    + <<async>> DetailsAsync(viewType:string, themeId:int, folderType:string, id:int?) : Task<ActionResult<RepositoryResponse<UpdateViewModel>>>
    + <<async>> DeleteAsync(id:int) : Task<RepositoryResponse<MixTemplate>>
    + <<async>> Save(model:Lib.ViewModels.MixTemplates.UpdateViewModel) : Task<RepositoryResponse<Lib.ViewModels.MixTemplates.UpdateViewModel>>
    + <<async>> GetList(themeId:int, request:RequestPaging) : Task<ActionResult<JObject>>
}
"BaseGenericApiController`2" "<MixCmsContext,MixTemplate>" <|-- ApiTemplateController
@enduml
