@startuml
class "BaseApiController`1"<TDbContext> {
    # <<readonly>> _hubContext : IHubContext<Mix.Cms.Service.SignalR.Hubs.PortalHub>
    # {static} _context : TDbContext
    # {static} _transaction : IDbContextTransaction
    # <<readonly>> _memoryCache : IMemoryCache
    # _lang : string
    # _domain : string
    + BaseApiController(context:TDbContext, memoryCache:IMemoryCache, hubContext:IHubContext<PortalHub>)
    + <<override>> OnActionExecuting(context:ActionExecutingContext) : void
    # RemoveCache() : void
    # <<async>> GetSingleAsync(key:string, predicate:Expression<Func<TModel, bool>>, model:TModel) : Task<RepositoryResponse<TView>>
    # AlertAsync(action:string, status:int, message:string) : void
    # ParseRequestPagingDate(request:RequestPaging) : void
    # ParseQuery(request:RequestPaging) : QueryString
    # GetLanguage() : void
}
Controller <|-- "BaseApiController`1"
@enduml
