@startuml
class DeleteViewModel {
    + Id : string <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + DeleteViewModel()
    + DeleteViewModel(model:MixAttributeSetData, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> RemoveRelatedModels(view:DeleteViewModel, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<bool>
    + <<override>> <<async>> RemoveRelatedModelsAsync(view:DeleteViewModel, _context:MixCmsContext, _transaction:IDbContextTransaction) : System.Threading.Tasks.Task<RepositoryResponse<bool>>
}
"ViewModelBase`3" "<MixCmsContext,MixAttributeSetData,DeleteViewModel>" <|-- DeleteViewModel
@enduml
