@startuml
class DefaultViewModel {
    + Id : string <<get>> <<set>>
    + FacebookId : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Avatar : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + DefaultViewModel()
    + DefaultViewModel(model:MixMessengerUser, _context:MixChatServiceContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixChatServiceContext, _transaction:IDbContextTransaction) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixChatServiceContext,MixMessengerUser,DefaultViewModel>" <|-- DefaultViewModel
DefaultViewModel --> "CreatedDate" DateTime
@enduml
