@startuml
class ApiModuleController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<ReadListItemViewModel>>>
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixModule,UpdateViewModel,ReadListItemViewModel,UpdateViewModel>" <|-- ApiModuleController
@enduml
