@startuml
class IpRestrictionMiddleware {
    + <<readonly>> Next : RequestDelegate
    + <<readonly>> IpSecuritySettings : IpSecuritySettings
    + IpRestrictionMiddleware(next:RequestDelegate, ipSecuritySettings:IOptions<IpSecuritySettings>)
    + <<async>> Invoke(context:HttpContext) : Task
}
class IpSecuritySettings {
    + IsRetrictIp : bool <<get>> <<set>>
    + AllowedPortalIps : string <<get>> <<set>>
    + AllowedIps : string <<get>> <<set>>
    + ExceptIps : string <<get>> <<set>>
    + AllowedIPsList : List<string> <<get>>
}
@enduml
