@startuml
class MixCmsUserConfiguration {
    + Configure(entity:EntityTypeBuilder<MixCmsUser>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixCmsUser>" <|-- MixCmsUserConfiguration
@enduml
