@startuml
class MixCacheConfiguration {
    + Configure(entity:EntityTypeBuilder<MixCache>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixCache>" <|-- MixCacheConfiguration
@enduml
