@startuml
class MixPageConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPage>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixPage>" <|-- MixPageConfiguration
@enduml
