### YamlMime:ManagedReference
items:
- uid: Mix.Identity.Const.ApplicationTypes
  commentId: T:Mix.Identity.Const.ApplicationTypes
  id: Const.ApplicationTypes
  parent: Mix.Identity
  children:
  - Mix.Identity.Const.ApplicationTypes.JavaScript
  - Mix.Identity.Const.ApplicationTypes.NativeConfidential
  langs:
  - csharp
  - vb
  name: Const.ApplicationTypes
  nameWithType: Const.ApplicationTypes
  fullName: Mix.Identity.Const.ApplicationTypes
  type: Enum
  source:
    remote:
      path: src/platform/mix.identity/Const.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: ApplicationTypes
    path: ../../mix.core/src/platform/mix.identity/Const.cs
    startLine: 18
  assemblies:
  - mix.identity
  namespace: Mix.Identity
  syntax:
    content: public enum ApplicationTypes
    content.vb: Public Enum ApplicationTypes
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Mix.Identity.Const.ApplicationTypes.JavaScript
  commentId: F:Mix.Identity.Const.ApplicationTypes.JavaScript
  id: JavaScript
  parent: Mix.Identity.Const.ApplicationTypes
  langs:
  - csharp
  - vb
  name: JavaScript
  nameWithType: Const.ApplicationTypes.JavaScript
  fullName: Mix.Identity.Const.ApplicationTypes.JavaScript
  type: Field
  source:
    remote:
      path: src/platform/mix.identity/Const.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: JavaScript
    path: ../../mix.core/src/platform/mix.identity/Const.cs
    startLine: 20
  assemblies:
  - mix.identity
  namespace: Mix.Identity
  syntax:
    content: JavaScript = 0
    return:
      type: Mix.Identity.Const.ApplicationTypes
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Identity.Const.ApplicationTypes.NativeConfidential
  commentId: F:Mix.Identity.Const.ApplicationTypes.NativeConfidential
  id: NativeConfidential
  parent: Mix.Identity.Const.ApplicationTypes
  langs:
  - csharp
  - vb
  name: NativeConfidential
  nameWithType: Const.ApplicationTypes.NativeConfidential
  fullName: Mix.Identity.Const.ApplicationTypes.NativeConfidential
  type: Field
  source:
    remote:
      path: src/platform/mix.identity/Const.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: NativeConfidential
    path: ../../mix.core/src/platform/mix.identity/Const.cs
    startLine: 21
  assemblies:
  - mix.identity
  namespace: Mix.Identity
  syntax:
    content: NativeConfidential = 1
    return:
      type: Mix.Identity.Const.ApplicationTypes
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Mix.Identity
  commentId: N:Mix.Identity
  name: Mix.Identity
  nameWithType: Mix.Identity
  fullName: Mix.Identity
- uid: Mix.Identity.Const.ApplicationTypes
  commentId: T:Mix.Identity.Const.ApplicationTypes
  parent: Mix.Identity
  name: Const.ApplicationTypes
  nameWithType: Const.ApplicationTypes
  fullName: Mix.Identity.Const.ApplicationTypes
