### YamlMime:ManagedReference
items:
- uid: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest
  commentId: T:Mix.Xunittest.Domain.Tests.c1_ConfigurationTest
  id: c1_ConfigurationTest
  parent: Mix.Xunittest.Domain.Tests
  children:
  - Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.#ctor(Mix.Xunittest.Domain.SharedMixCmsDbFixture)
  - Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.CreateSampleValue
  langs:
  - csharp
  - vb
  name: c1_ConfigurationTest
  nameWithType: c1_ConfigurationTest
  fullName: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest
  type: Class
  source:
    remote:
      path: src/test/mix.xunittest/Domain/Tests/c1_ConfigurationTest.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: c1_ConfigurationTest
    path: ../../mix.core/src/test/mix.xunittest/Domain/Tests/c1_ConfigurationTest.cs
    startLine: 2
  assemblies:
  - mix.xunittest
  namespace: Mix.Xunittest.Domain.Tests
  syntax:
    content: 'public class c1_ConfigurationTest : ViewModelTestBase<SharedMixCmsDbFixture, MixConfigurationViewModel, MixCmsContext, MixConfiguration, int>, IClassFixture<SharedMixCmsDbFixture>'
    content.vb: >-
      Public Class c1_ConfigurationTest
          Inherits ViewModelTestBase(Of SharedMixCmsDbFixture, MixConfigurationViewModel, MixCmsContext, MixConfiguration, Integer)
          Implements IClassFixture(Of SharedMixCmsDbFixture)
  inheritance:
  - System.Object
  implements:
  - IClassFixture{Mix.Xunittest.Domain.SharedMixCmsDbFixture}
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.#ctor(Mix.Xunittest.Domain.SharedMixCmsDbFixture)
  commentId: M:Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.#ctor(Mix.Xunittest.Domain.SharedMixCmsDbFixture)
  id: '#ctor(Mix.Xunittest.Domain.SharedMixCmsDbFixture)'
  parent: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest
  langs:
  - csharp
  - vb
  name: c1_ConfigurationTest(SharedMixCmsDbFixture)
  nameWithType: c1_ConfigurationTest.c1_ConfigurationTest(SharedMixCmsDbFixture)
  fullName: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.c1_ConfigurationTest(Mix.Xunittest.Domain.SharedMixCmsDbFixture)
  type: Constructor
  source:
    remote:
      path: src/test/mix.xunittest/Domain/Tests/c1_ConfigurationTest.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: .ctor
    path: ../../mix.core/src/test/mix.xunittest/Domain/Tests/c1_ConfigurationTest.cs
    startLine: 7
  assemblies:
  - mix.xunittest
  namespace: Mix.Xunittest.Domain.Tests
  syntax:
    content: public c1_ConfigurationTest(SharedMixCmsDbFixture fixture)
    parameters:
    - id: fixture
      type: Mix.Xunittest.Domain.SharedMixCmsDbFixture
    content.vb: Public Sub New(fixture As SharedMixCmsDbFixture)
  overload: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.CreateSampleValue
  commentId: M:Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.CreateSampleValue
  id: CreateSampleValue
  parent: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest
  langs:
  - csharp
  - vb
  name: CreateSampleValue()
  nameWithType: c1_ConfigurationTest.CreateSampleValue()
  fullName: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.CreateSampleValue()
  type: Method
  source:
    remote:
      path: src/test/mix.xunittest/Domain/Tests/c1_ConfigurationTest.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: CreateSampleValue
    path: ../../mix.core/src/test/mix.xunittest/Domain/Tests/c1_ConfigurationTest.cs
    startLine: 11
  assemblies:
  - mix.xunittest
  namespace: Mix.Xunittest.Domain.Tests
  syntax:
    content: protected override MixConfigurationViewModel CreateSampleValue()
    return:
      type: MixConfigurationViewModel
    content.vb: Protected Overrides Function CreateSampleValue As MixConfigurationViewModel
  overload: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.CreateSampleValue*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
references:
- uid: Mix.Xunittest.Domain.Tests
  commentId: N:Mix.Xunittest.Domain.Tests
  name: Mix.Xunittest.Domain.Tests
  nameWithType: Mix.Xunittest.Domain.Tests
  fullName: Mix.Xunittest.Domain.Tests
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: IClassFixture{Mix.Xunittest.Domain.SharedMixCmsDbFixture}
  commentId: '!:IClassFixture{Mix.Xunittest.Domain.SharedMixCmsDbFixture}'
  definition: IClassFixture`1
  name: IClassFixture<SharedMixCmsDbFixture>
  nameWithType: IClassFixture<SharedMixCmsDbFixture>
  fullName: IClassFixture<Mix.Xunittest.Domain.SharedMixCmsDbFixture>
  nameWithType.vb: IClassFixture(Of SharedMixCmsDbFixture)
  fullName.vb: IClassFixture(Of Mix.Xunittest.Domain.SharedMixCmsDbFixture)
  name.vb: IClassFixture(Of SharedMixCmsDbFixture)
  spec.csharp:
  - uid: IClassFixture`1
    name: IClassFixture
    nameWithType: IClassFixture
    fullName: IClassFixture
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Mix.Xunittest.Domain.SharedMixCmsDbFixture
    name: SharedMixCmsDbFixture
    nameWithType: SharedMixCmsDbFixture
    fullName: Mix.Xunittest.Domain.SharedMixCmsDbFixture
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IClassFixture`1
    name: IClassFixture
    nameWithType: IClassFixture
    fullName: IClassFixture
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Mix.Xunittest.Domain.SharedMixCmsDbFixture
    name: SharedMixCmsDbFixture
    nameWithType: SharedMixCmsDbFixture
    fullName: Mix.Xunittest.Domain.SharedMixCmsDbFixture
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: IClassFixture`1
  isExternal: true
  name: IClassFixture<>
  nameWithType: IClassFixture<>
  fullName: IClassFixture<>
  nameWithType.vb: IClassFixture(Of )
  fullName.vb: IClassFixture(Of )
  name.vb: IClassFixture(Of )
  spec.csharp:
  - uid: IClassFixture`1
    name: IClassFixture
    nameWithType: IClassFixture
    fullName: IClassFixture
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IClassFixture`1
    name: IClassFixture
    nameWithType: IClassFixture
    fullName: IClassFixture
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.#ctor*
  commentId: Overload:Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.#ctor
  name: c1_ConfigurationTest
  nameWithType: c1_ConfigurationTest.c1_ConfigurationTest
  fullName: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.c1_ConfigurationTest
- uid: Mix.Xunittest.Domain.SharedMixCmsDbFixture
  commentId: T:Mix.Xunittest.Domain.SharedMixCmsDbFixture
  parent: Mix.Xunittest.Domain
  name: SharedMixCmsDbFixture
  nameWithType: SharedMixCmsDbFixture
  fullName: Mix.Xunittest.Domain.SharedMixCmsDbFixture
- uid: Mix.Xunittest.Domain
  commentId: N:Mix.Xunittest.Domain
  name: Mix.Xunittest.Domain
  nameWithType: Mix.Xunittest.Domain
  fullName: Mix.Xunittest.Domain
- uid: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.CreateSampleValue*
  commentId: Overload:Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.CreateSampleValue
  name: CreateSampleValue
  nameWithType: c1_ConfigurationTest.CreateSampleValue
  fullName: Mix.Xunittest.Domain.Tests.c1_ConfigurationTest.CreateSampleValue
- uid: MixConfigurationViewModel
  commentId: '!:MixConfigurationViewModel'
  isExternal: true
  name: MixConfigurationViewModel
  nameWithType: MixConfigurationViewModel
  fullName: MixConfigurationViewModel
