### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.MYSQL.Base
  commentId: N:Mix.Database.EntityConfigurations.MYSQL.Base
  id: Mix.Database.EntityConfigurations.MYSQL.Base
  children:
  - Mix.Database.EntityConfigurations.MYSQL.Base.MySqlAssociationBaseConfiguration`2
  - Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration`2
  - Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualSEOContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualUniqueNameContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityBaseConfiguration`2
  - Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityUniqueNameBaseConfiguration`2
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.MYSQL.Base
  nameWithType: Mix.Database.EntityConfigurations.MYSQL.Base
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlAssociationBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.Base.MySqlAssociationBaseConfiguration`2
  name: MySqlAssociationBaseConfiguration<T, TPrimaryKey>
  nameWithType: MySqlAssociationBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlAssociationBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: MySqlAssociationBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlAssociationBaseConfiguration(Of T, TPrimaryKey)
  name.vb: MySqlAssociationBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlAssociationBaseConfiguration`2
    name: MySqlAssociationBaseConfiguration
    nameWithType: MySqlAssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlAssociationBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlAssociationBaseConfiguration`2
    name: MySqlAssociationBaseConfiguration
    nameWithType: MySqlAssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlAssociationBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration`2
  name: MySqlEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: MySqlEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: MySqlEntityBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: MySqlEntityBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration`2
    name: MySqlEntityBaseConfiguration
    nameWithType: MySqlEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration`2
    name: MySqlEntityBaseConfiguration
    nameWithType: MySqlEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration`2
  name: MySqlMultilingualContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: MySqlMultilingualContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: MySqlMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: MySqlMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration`2
    name: MySqlMultilingualContentBaseConfiguration
    nameWithType: MySqlMultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration`2
    name: MySqlMultilingualContentBaseConfiguration
    nameWithType: MySqlMultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualSEOContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualSEOContentBaseConfiguration`2
  name: MySqlMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: MySqlMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: MySqlMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: MySqlMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualSEOContentBaseConfiguration`2
    name: MySqlMultilingualSEOContentBaseConfiguration
    nameWithType: MySqlMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualSEOContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualSEOContentBaseConfiguration`2
    name: MySqlMultilingualSEOContentBaseConfiguration
    nameWithType: MySqlMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualSEOContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualUniqueNameContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualUniqueNameContentBaseConfiguration`2
  name: MySqlMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: MySqlMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: MySqlMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: MySqlMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualUniqueNameContentBaseConfiguration`2
    name: MySqlMultilingualUniqueNameContentBaseConfiguration
    nameWithType: MySqlMultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualUniqueNameContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualUniqueNameContentBaseConfiguration`2
    name: MySqlMultilingualUniqueNameContentBaseConfiguration
    nameWithType: MySqlMultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualUniqueNameContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityBaseConfiguration`2
  name: MySqlTenantEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: MySqlTenantEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: MySqlTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: MySqlTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityBaseConfiguration`2
    name: MySqlTenantEntityBaseConfiguration
    nameWithType: MySqlTenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityBaseConfiguration`2
    name: MySqlTenantEntityBaseConfiguration
    nameWithType: MySqlTenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityUniqueNameBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityUniqueNameBaseConfiguration`2
  name: MySqlTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  nameWithType: MySqlTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: MySqlTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  name.vb: MySqlTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityUniqueNameBaseConfiguration`2
    name: MySqlTenantEntityUniqueNameBaseConfiguration
    nameWithType: MySqlTenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityUniqueNameBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityUniqueNameBaseConfiguration`2
    name: MySqlTenantEntityUniqueNameBaseConfiguration
    nameWithType: MySqlTenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlTenantEntityUniqueNameBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
