### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.POSTGRES
  commentId: N:Mix.Database.EntityConfigurations.POSTGRES
  id: Mix.Database.EntityConfigurations.POSTGRES
  children:
  - Mix.Database.EntityConfigurations.POSTGRES.MixConfigurationConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixConfigurationContentConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixContributorConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixCultureConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseColumnConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseContextConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixDataConentAssociationConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixDataConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixDataContentConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixDataContentValueConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixDiscussionConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixDomainConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixLanguageConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixLanguageContentConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixMediaConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixModuleConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixModuleContentConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixModuleDataConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixModulePostAssociationConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixPageConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixPageContentConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixPageModuleAssociationConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixPagePostAssociationConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixPostConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixPostContentConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixTenantConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixThemeConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixUrlAliasConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.MixViewTemplateContentConfiguration
  - Mix.Database.EntityConfigurations.POSTGRES.PostgresDatabaseConstants
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.POSTGRES
  nameWithType: Mix.Database.EntityConfigurations.POSTGRES
  fullName: Mix.Database.EntityConfigurations.POSTGRES
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixConfigurationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixConfigurationConfiguration
  name: MixConfigurationConfiguration
  nameWithType: MixConfigurationConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixConfigurationConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixConfigurationContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixConfigurationContentConfiguration
  name: MixConfigurationContentConfiguration
  nameWithType: MixConfigurationContentConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixConfigurationContentConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixContributorConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixContributorConfiguration
  name: MixContributorConfiguration
  nameWithType: MixContributorConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixContributorConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixCultureConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixCultureConfiguration
  name: MixCultureConfiguration
  nameWithType: MixCultureConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixCultureConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseColumnConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseColumnConfiguration
  name: MixDatabaseColumnConfiguration
  nameWithType: MixDatabaseColumnConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseColumnConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseConfiguration
  name: MixDatabaseConfiguration
  nameWithType: MixDatabaseConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseContextConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseContextConfiguration
  name: MixDatabaseContextConfiguration
  nameWithType: MixDatabaseContextConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixDatabaseContextConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixDataConentAssociationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixDataConentAssociationConfiguration
  name: MixDataConentAssociationConfiguration
  nameWithType: MixDataConentAssociationConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixDataConentAssociationConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixDataConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixDataConfiguration
  name: MixDataConfiguration
  nameWithType: MixDataConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixDataConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixDataContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixDataContentConfiguration
  name: MixDataContentConfiguration
  nameWithType: MixDataContentConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixDataContentConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixDataContentValueConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixDataContentValueConfiguration
  name: MixDataContentValueConfiguration
  nameWithType: MixDataContentValueConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixDataContentValueConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixDiscussionConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixDiscussionConfiguration
  name: MixDiscussionConfiguration
  nameWithType: MixDiscussionConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixDiscussionConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixDomainConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixDomainConfiguration
  name: MixDomainConfiguration
  nameWithType: MixDomainConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixDomainConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixLanguageConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixLanguageConfiguration
  name: MixLanguageConfiguration
  nameWithType: MixLanguageConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixLanguageConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixLanguageContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixLanguageContentConfiguration
  name: MixLanguageContentConfiguration
  nameWithType: MixLanguageContentConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixLanguageContentConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixMediaConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixMediaConfiguration
  name: MixMediaConfiguration
  nameWithType: MixMediaConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixMediaConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixModuleConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixModuleConfiguration
  name: MixModuleConfiguration
  nameWithType: MixModuleConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixModuleConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixModuleContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixModuleContentConfiguration
  name: MixModuleContentConfiguration
  nameWithType: MixModuleContentConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixModuleContentConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixModuleDataConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixModuleDataConfiguration
  name: MixModuleDataConfiguration
  nameWithType: MixModuleDataConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixModuleDataConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixModulePostAssociationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixModulePostAssociationConfiguration
  name: MixModulePostAssociationConfiguration
  nameWithType: MixModulePostAssociationConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixModulePostAssociationConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixPageConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixPageConfiguration
  name: MixPageConfiguration
  nameWithType: MixPageConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixPageConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixPageContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixPageContentConfiguration
  name: MixPageContentConfiguration
  nameWithType: MixPageContentConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixPageContentConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixPageModuleAssociationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixPageModuleAssociationConfiguration
  name: MixPageModuleAssociationConfiguration
  nameWithType: MixPageModuleAssociationConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixPageModuleAssociationConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixPagePostAssociationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixPagePostAssociationConfiguration
  name: MixPagePostAssociationConfiguration
  nameWithType: MixPagePostAssociationConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixPagePostAssociationConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixPostConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixPostConfiguration
  name: MixPostConfiguration
  nameWithType: MixPostConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixPostConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixPostContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixPostContentConfiguration
  name: MixPostContentConfiguration
  nameWithType: MixPostContentConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixPostContentConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixTenantConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixTenantConfiguration
  name: MixTenantConfiguration
  nameWithType: MixTenantConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixTenantConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixThemeConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixThemeConfiguration
  name: MixThemeConfiguration
  nameWithType: MixThemeConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixThemeConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixUrlAliasConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixUrlAliasConfiguration
  name: MixUrlAliasConfiguration
  nameWithType: MixUrlAliasConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixUrlAliasConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.MixViewTemplateContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.MixViewTemplateContentConfiguration
  name: MixViewTemplateContentConfiguration
  nameWithType: MixViewTemplateContentConfiguration
  fullName: Mix.Database.EntityConfigurations.POSTGRES.MixViewTemplateContentConfiguration
- uid: Mix.Database.EntityConfigurations.POSTGRES.PostgresDatabaseConstants
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.PostgresDatabaseConstants
  name: PostgresDatabaseConstants
  nameWithType: PostgresDatabaseConstants
  fullName: Mix.Database.EntityConfigurations.POSTGRES.PostgresDatabaseConstants
