### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations
  commentId: N:Mix.Database.EntityConfigurations
  id: Mix.Database.EntityConfigurations
  children:
  - Mix.Database.EntityConfigurations.IDatabaseConstants
  - Mix.Database.EntityConfigurations.PropertyBuilderExtensions
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations
  nameWithType: Mix.Database.EntityConfigurations
  fullName: Mix.Database.EntityConfigurations
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants
  commentId: T:Mix.Database.EntityConfigurations.IDatabaseConstants
  parent: Mix.Database.EntityConfigurations
  name: IDatabaseConstants
  nameWithType: IDatabaseConstants
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants
- uid: Mix.Database.EntityConfigurations.PropertyBuilderExtensions
  commentId: T:Mix.Database.EntityConfigurations.PropertyBuilderExtensions
  name: PropertyBuilderExtensions
  nameWithType: PropertyBuilderExtensions
  fullName: Mix.Database.EntityConfigurations.PropertyBuilderExtensions
- uid: Mix.Database.EntityConfigurations
  commentId: N:Mix.Database.EntityConfigurations
  name: Mix.Database.EntityConfigurations
  nameWithType: Mix.Database.EntityConfigurations
  fullName: Mix.Database.EntityConfigurations
