### YamlMime:ManagedReference
items:
- uid: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel
  commentId: T:Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel
  id: MixConfigurationContentViewModel
  parent: Mix.Portal.Domain.ViewModels
  children:
  - Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor
  - Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor(MixConfigurationContent,UnitOfWorkInfo)
  - Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor(UnitOfWorkInfo)
  - Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.DefaultContent
  langs:
  - csharp
  - vb
  name: MixConfigurationContentViewModel
  nameWithType: MixConfigurationContentViewModel
  fullName: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel
  type: Class
  source:
    remote:
      path: src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MixConfigurationContentViewModel
    path: ../../mix.core/src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
    startLine: 2
  assemblies:
  - mix.portal
  namespace: Mix.Portal.Domain.ViewModels
  syntax:
    content: 'public class MixConfigurationContentViewModel : MultilingualUniqueNameContentViewModelBase<MixCmsContext, MixConfigurationContent, int, MixConfigurationContentViewModel>'
    content.vb: >-
      Public Class MixConfigurationContentViewModel
          Inherits MultilingualUniqueNameContentViewModelBase(Of MixCmsContext, MixConfigurationContent, Integer, MixConfigurationContentViewModel)
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.DefaultContent
  commentId: P:Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.DefaultContent
  id: DefaultContent
  parent: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel
  langs:
  - csharp
  - vb
  name: DefaultContent
  nameWithType: MixConfigurationContentViewModel.DefaultContent
  fullName: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.DefaultContent
  type: Property
  source:
    remote:
      path: src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: DefaultContent
    path: ../../mix.core/src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
    startLine: 6
  assemblies:
  - mix.portal
  namespace: Mix.Portal.Domain.ViewModels
  syntax:
    content: public string DefaultContent { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DefaultContent As String
  overload: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.DefaultContent*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor
  commentId: M:Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor
  id: '#ctor'
  parent: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel
  langs:
  - csharp
  - vb
  name: MixConfigurationContentViewModel()
  nameWithType: MixConfigurationContentViewModel.MixConfigurationContentViewModel()
  fullName: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.MixConfigurationContentViewModel()
  type: Constructor
  source:
    remote:
      path: src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: .ctor
    path: ../../mix.core/src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
    startLine: 8
  assemblies:
  - mix.portal
  namespace: Mix.Portal.Domain.ViewModels
  syntax:
    content: public MixConfigurationContentViewModel()
    content.vb: Public Sub New
  overload: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor(UnitOfWorkInfo)
  commentId: M:Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor(UnitOfWorkInfo)
  id: '#ctor(UnitOfWorkInfo)'
  parent: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel
  langs:
  - csharp
  - vb
  name: MixConfigurationContentViewModel(UnitOfWorkInfo)
  nameWithType: MixConfigurationContentViewModel.MixConfigurationContentViewModel(UnitOfWorkInfo)
  fullName: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.MixConfigurationContentViewModel(UnitOfWorkInfo)
  type: Constructor
  source:
    remote:
      path: src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: .ctor
    path: ../../mix.core/src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
    startLine: 13
  assemblies:
  - mix.portal
  namespace: Mix.Portal.Domain.ViewModels
  syntax:
    content: public MixConfigurationContentViewModel(UnitOfWorkInfo unitOfWorkInfo)
    parameters:
    - id: unitOfWorkInfo
      type: UnitOfWorkInfo
    content.vb: Public Sub New(unitOfWorkInfo As UnitOfWorkInfo)
  overload: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor(MixConfigurationContent,UnitOfWorkInfo)
  commentId: M:Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor(MixConfigurationContent,UnitOfWorkInfo)
  id: '#ctor(MixConfigurationContent,UnitOfWorkInfo)'
  parent: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel
  langs:
  - csharp
  - vb
  name: MixConfigurationContentViewModel(MixConfigurationContent, UnitOfWorkInfo)
  nameWithType: MixConfigurationContentViewModel.MixConfigurationContentViewModel(MixConfigurationContent, UnitOfWorkInfo)
  fullName: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.MixConfigurationContentViewModel(MixConfigurationContent, UnitOfWorkInfo)
  type: Constructor
  source:
    remote:
      path: src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: .ctor
    path: ../../mix.core/src/modules/mix.portal/Domain/ViewModels/MixConfigurationContentViewModel.cs
    startLine: 17
  assemblies:
  - mix.portal
  namespace: Mix.Portal.Domain.ViewModels
  syntax:
    content: public MixConfigurationContentViewModel(MixConfigurationContent entity, UnitOfWorkInfo uowInfo = null)
    parameters:
    - id: entity
      type: MixConfigurationContent
    - id: uowInfo
      type: UnitOfWorkInfo
    content.vb: Public Sub New(entity As MixConfigurationContent, uowInfo As UnitOfWorkInfo = Nothing)
  overload: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Mix.Portal.Domain.ViewModels
  commentId: N:Mix.Portal.Domain.ViewModels
  name: Mix.Portal.Domain.ViewModels
  nameWithType: Mix.Portal.Domain.ViewModels
  fullName: Mix.Portal.Domain.ViewModels
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.DefaultContent*
  commentId: Overload:Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.DefaultContent
  name: DefaultContent
  nameWithType: MixConfigurationContentViewModel.DefaultContent
  fullName: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.DefaultContent
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor*
  commentId: Overload:Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.#ctor
  name: MixConfigurationContentViewModel
  nameWithType: MixConfigurationContentViewModel.MixConfigurationContentViewModel
  fullName: Mix.Portal.Domain.ViewModels.MixConfigurationContentViewModel.MixConfigurationContentViewModel
- uid: UnitOfWorkInfo
  isExternal: true
  name: UnitOfWorkInfo
  nameWithType: UnitOfWorkInfo
  fullName: UnitOfWorkInfo
- uid: MixConfigurationContent
  isExternal: true
  name: MixConfigurationContent
  nameWithType: MixConfigurationContent
  fullName: MixConfigurationContent
