### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.SQLITE
  commentId: N:Mix.Database.EntityConfigurations.SQLITE
  id: Mix.Database.EntityConfigurations.SQLITE
  children:
  - Mix.Database.EntityConfigurations.SQLITE.MixConfigurationConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixConfigurationContentConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixContributorConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixCultureConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDatabaseColumnConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDatabaseConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDataConentAssociationConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDataConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDataContentConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDataContentValueConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDiscussionConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDomainConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixLanguageConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixLanguageContentConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixMediaConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixModuleConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixModuleContentConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixPageConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixPageContentConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixPostConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixPostContentConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixTenantConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixThemeConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixUrlAliasConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixViewTemplateContentConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.SQLITE
  nameWithType: Mix.Database.EntityConfigurations.SQLITE
  fullName: Mix.Database.EntityConfigurations.SQLITE
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.SQLITE.MixConfigurationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixConfigurationConfiguration
  name: MixConfigurationConfiguration
  nameWithType: MixConfigurationConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixConfigurationConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixConfigurationContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixConfigurationContentConfiguration
  name: MixConfigurationContentConfiguration
  nameWithType: MixConfigurationContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixConfigurationContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixContributorConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixContributorConfiguration
  name: MixContributorConfiguration
  nameWithType: MixContributorConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixContributorConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixCultureConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixCultureConfiguration
  name: MixCultureConfiguration
  nameWithType: MixCultureConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixCultureConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixDatabaseColumnConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixDatabaseColumnConfiguration
  name: MixDatabaseColumnConfiguration
  nameWithType: MixDatabaseColumnConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixDatabaseColumnConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixDatabaseConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixDatabaseConfiguration
  name: MixDatabaseConfiguration
  nameWithType: MixDatabaseConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixDatabaseConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixDataConentAssociationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixDataConentAssociationConfiguration
  name: MixDataConentAssociationConfiguration
  nameWithType: MixDataConentAssociationConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixDataConentAssociationConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixDataConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixDataConfiguration
  name: MixDataConfiguration
  nameWithType: MixDataConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixDataConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixDataContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixDataContentConfiguration
  name: MixDataContentConfiguration
  nameWithType: MixDataContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixDataContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixDataContentValueConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixDataContentValueConfiguration
  name: MixDataContentValueConfiguration
  nameWithType: MixDataContentValueConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixDataContentValueConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixDiscussionConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixDiscussionConfiguration
  name: MixDiscussionConfiguration
  nameWithType: MixDiscussionConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixDiscussionConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixDomainConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixDomainConfiguration
  name: MixDomainConfiguration
  nameWithType: MixDomainConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixDomainConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixLanguageConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixLanguageConfiguration
  name: MixLanguageConfiguration
  nameWithType: MixLanguageConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixLanguageConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixLanguageContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixLanguageContentConfiguration
  name: MixLanguageContentConfiguration
  nameWithType: MixLanguageContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixLanguageContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixMediaConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixMediaConfiguration
  name: MixMediaConfiguration
  nameWithType: MixMediaConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixMediaConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixModuleConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixModuleConfiguration
  name: MixModuleConfiguration
  nameWithType: MixModuleConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixModuleConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixModuleContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixModuleContentConfiguration
  name: MixModuleContentConfiguration
  nameWithType: MixModuleContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixModuleContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixPageConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixPageConfiguration
  name: MixPageConfiguration
  nameWithType: MixPageConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixPageConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixPageContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixPageContentConfiguration
  name: MixPageContentConfiguration
  nameWithType: MixPageContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixPageContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixPostConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixPostConfiguration
  name: MixPostConfiguration
  nameWithType: MixPostConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixPostConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixPostContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixPostContentConfiguration
  name: MixPostContentConfiguration
  nameWithType: MixPostContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixPostContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixTenantConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixTenantConfiguration
  name: MixTenantConfiguration
  nameWithType: MixTenantConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixTenantConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixThemeConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixThemeConfiguration
  name: MixThemeConfiguration
  nameWithType: MixThemeConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixThemeConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixUrlAliasConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixUrlAliasConfiguration
  name: MixUrlAliasConfiguration
  nameWithType: MixUrlAliasConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixUrlAliasConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.MixViewTemplateContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.MixViewTemplateContentConfiguration
  name: MixViewTemplateContentConfiguration
  nameWithType: MixViewTemplateContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLITE.MixViewTemplateContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants
  name: SqliteDatabaseConstants
  nameWithType: SqliteDatabaseConstants
  fullName: Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants
