### YamlMime:ManagedReference
items:
- uid: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  commentId: N:Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  id: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  children:
  - Mix.Cms.Lib.ViewModels.MixAttributeSetValues.DeleteViewModel
  - Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ImportViewModel
  - Mix.Cms.Lib.ViewModels.MixAttributeSetValues.NavigationViewModel
  - Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ReadMvcViewModel
  - Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ReadViewModel
  - Mix.Cms.Lib.ViewModels.MixAttributeSetValues.UpdateViewModel
  langs:
  - csharp
  - vb
  name: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  nameWithType: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  fullName: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  type: Namespace
  assemblies:
  - Mix.Cms.Lib
references:
- uid: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.DeleteViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixAttributeSetValues.DeleteViewModel
  name: DeleteViewModel
  nameWithType: DeleteViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.DeleteViewModel
- uid: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ImportViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ImportViewModel
  name: ImportViewModel
  nameWithType: ImportViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ImportViewModel
- uid: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.NavigationViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixAttributeSetValues.NavigationViewModel
  name: NavigationViewModel
  nameWithType: NavigationViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.NavigationViewModel
- uid: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ReadMvcViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ReadMvcViewModel
  name: ReadMvcViewModel
  nameWithType: ReadMvcViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ReadMvcViewModel
- uid: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ReadViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ReadViewModel
  name: ReadViewModel
  nameWithType: ReadViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.ReadViewModel
- uid: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.UpdateViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixAttributeSetValues.UpdateViewModel
  parent: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  name: UpdateViewModel
  nameWithType: UpdateViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixAttributeSetValues.UpdateViewModel
- uid: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  commentId: N:Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  name: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  nameWithType: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
  fullName: Mix.Cms.Lib.ViewModels.MixAttributeSetValues
