### YamlMime:ManagedReference
items:
- uid: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  commentId: N:Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  id: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  children:
  - Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration
  langs:
  - csharp
  - vb
  name: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  nameWithType: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  fullName: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  type: Namespace
  assemblies:
  - mix.heart
references:
- uid: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration
  commentId: T:Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration
  name: MixCacheConfiguration
  nameWithType: MixCacheConfiguration
  fullName: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration
