### YamlMime:ManagedReference
items:
- uid: Mix.Shared.Models.SmtpConfiguration
  commentId: T:Mix.Shared.Models.SmtpConfiguration
  id: SmtpConfiguration
  parent: Mix.Shared.Models
  children:
  - Mix.Shared.Models.SmtpConfiguration.Port
  - Mix.Shared.Models.SmtpConfiguration.Server
  - Mix.Shared.Models.SmtpConfiguration.SSL
  - Mix.Shared.Models.SmtpConfiguration.User
  langs:
  - csharp
  - vb
  name: SmtpConfiguration
  nameWithType: SmtpConfiguration
  fullName: Mix.Shared.Models.SmtpConfiguration
  type: Class
  source:
    remote:
      path: src/platform/mix.shared/Models/SmtpConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: SmtpConfiguration
    path: ../../mix.core/src/platform/mix.shared/Models/SmtpConfiguration.cs
    startLine: 2
  assemblies:
  - mix.shared
  namespace: Mix.Shared.Models
  syntax:
    content: public class SmtpConfiguration
    content.vb: Public Class SmtpConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Shared.Models.SmtpConfiguration.Server
  commentId: P:Mix.Shared.Models.SmtpConfiguration.Server
  id: Server
  parent: Mix.Shared.Models.SmtpConfiguration
  langs:
  - csharp
  - vb
  name: Server
  nameWithType: SmtpConfiguration.Server
  fullName: Mix.Shared.Models.SmtpConfiguration.Server
  type: Property
  source:
    remote:
      path: src/platform/mix.shared/Models/SmtpConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Server
    path: ../../mix.core/src/platform/mix.shared/Models/SmtpConfiguration.cs
    startLine: 4
  assemblies:
  - mix.shared
  namespace: Mix.Shared.Models
  syntax:
    content: public string Server { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Server As String
  overload: Mix.Shared.Models.SmtpConfiguration.Server*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Shared.Models.SmtpConfiguration.Port
  commentId: P:Mix.Shared.Models.SmtpConfiguration.Port
  id: Port
  parent: Mix.Shared.Models.SmtpConfiguration
  langs:
  - csharp
  - vb
  name: Port
  nameWithType: SmtpConfiguration.Port
  fullName: Mix.Shared.Models.SmtpConfiguration.Port
  type: Property
  source:
    remote:
      path: src/platform/mix.shared/Models/SmtpConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Port
    path: ../../mix.core/src/platform/mix.shared/Models/SmtpConfiguration.cs
    startLine: 5
  assemblies:
  - mix.shared
  namespace: Mix.Shared.Models
  syntax:
    content: public int Port { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Port As Integer
  overload: Mix.Shared.Models.SmtpConfiguration.Port*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Shared.Models.SmtpConfiguration.SSL
  commentId: P:Mix.Shared.Models.SmtpConfiguration.SSL
  id: SSL
  parent: Mix.Shared.Models.SmtpConfiguration
  langs:
  - csharp
  - vb
  name: SSL
  nameWithType: SmtpConfiguration.SSL
  fullName: Mix.Shared.Models.SmtpConfiguration.SSL
  type: Property
  source:
    remote:
      path: src/platform/mix.shared/Models/SmtpConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: SSL
    path: ../../mix.core/src/platform/mix.shared/Models/SmtpConfiguration.cs
    startLine: 6
  assemblies:
  - mix.shared
  namespace: Mix.Shared.Models
  syntax:
    content: public bool SSL { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property SSL As Boolean
  overload: Mix.Shared.Models.SmtpConfiguration.SSL*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Shared.Models.SmtpConfiguration.User
  commentId: P:Mix.Shared.Models.SmtpConfiguration.User
  id: User
  parent: Mix.Shared.Models.SmtpConfiguration
  langs:
  - csharp
  - vb
  name: User
  nameWithType: SmtpConfiguration.User
  fullName: Mix.Shared.Models.SmtpConfiguration.User
  type: Property
  source:
    remote:
      path: src/platform/mix.shared/Models/SmtpConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: User
    path: ../../mix.core/src/platform/mix.shared/Models/SmtpConfiguration.cs
    startLine: 7
  assemblies:
  - mix.shared
  namespace: Mix.Shared.Models
  syntax:
    content: public string User { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property User As String
  overload: Mix.Shared.Models.SmtpConfiguration.User*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Mix.Shared.Models
  commentId: N:Mix.Shared.Models
  name: Mix.Shared.Models
  nameWithType: Mix.Shared.Models
  fullName: Mix.Shared.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Shared.Models.SmtpConfiguration.Server*
  commentId: Overload:Mix.Shared.Models.SmtpConfiguration.Server
  name: Server
  nameWithType: SmtpConfiguration.Server
  fullName: Mix.Shared.Models.SmtpConfiguration.Server
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Mix.Shared.Models.SmtpConfiguration.Port*
  commentId: Overload:Mix.Shared.Models.SmtpConfiguration.Port
  name: Port
  nameWithType: SmtpConfiguration.Port
  fullName: Mix.Shared.Models.SmtpConfiguration.Port
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Mix.Shared.Models.SmtpConfiguration.SSL*
  commentId: Overload:Mix.Shared.Models.SmtpConfiguration.SSL
  name: SSL
  nameWithType: SmtpConfiguration.SSL
  fullName: Mix.Shared.Models.SmtpConfiguration.SSL
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Mix.Shared.Models.SmtpConfiguration.User*
  commentId: Overload:Mix.Shared.Models.SmtpConfiguration.User
  name: User
  nameWithType: SmtpConfiguration.User
  fullName: Mix.Shared.Models.SmtpConfiguration.User
