### YamlMime:ManagedReference
items:
- uid: Mix.Database.Entities.Cms.MixConfiguration
  commentId: T:Mix.Database.Entities.Cms.MixConfiguration
  id: MixConfiguration
  parent: Mix.Database.Entities.Cms
  children:
  - Mix.Database.Entities.Cms.MixConfiguration.MixConfigurationContents
  langs:
  - csharp
  - vb
  name: MixConfiguration
  nameWithType: MixConfiguration
  fullName: Mix.Database.Entities.Cms.MixConfiguration
  type: Class
  source:
    remote:
      path: src/platform/mix.database/Entities/Cms/MixConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MixConfiguration
    path: ../../mix.core/src/platform/mix.database/Entities/Cms/MixConfiguration.cs
    startLine: 5
  assemblies:
  - mix.database
  namespace: Mix.Database.Entities.Cms
  syntax:
    content: 'public class MixConfiguration : TenantEntityUniqueNameBase<int>'
    content.vb: >-
      Public Class MixConfiguration
          Inherits TenantEntityUniqueNameBase(Of Integer)
  inheritance:
  - System.Object
  - Mix.Database.Entities.Base.TenantEntityBase{System.Int32}
  - Mix.Database.Entities.Base.TenantEntityUniqueNameBase{System.Int32}
  inheritedMembers:
  - Mix.Database.Entities.Base.TenantEntityUniqueNameBase{System.Int32}.SystemName
  - Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.DisplayName
  - Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.Description
  - Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.MixTenantId
  - Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.MixTenant
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Database.Entities.Cms.MixConfiguration.MixConfigurationContents
  commentId: P:Mix.Database.Entities.Cms.MixConfiguration.MixConfigurationContents
  id: MixConfigurationContents
  parent: Mix.Database.Entities.Cms.MixConfiguration
  langs:
  - csharp
  - vb
  name: MixConfigurationContents
  nameWithType: MixConfiguration.MixConfigurationContents
  fullName: Mix.Database.Entities.Cms.MixConfiguration.MixConfigurationContents
  type: Property
  source:
    remote:
      path: src/platform/mix.database/Entities/Cms/MixConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MixConfigurationContents
    path: ../../mix.core/src/platform/mix.database/Entities/Cms/MixConfiguration.cs
    startLine: 7
  assemblies:
  - mix.database
  namespace: Mix.Database.Entities.Cms
  syntax:
    content: public virtual ICollection<MixConfigurationContent> MixConfigurationContents { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.ICollection{Mix.Database.Entities.Cms.MixConfigurationContent}
    content.vb: Public Overridable Property MixConfigurationContents As ICollection(Of MixConfigurationContent)
  overload: Mix.Database.Entities.Cms.MixConfiguration.MixConfigurationContents*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Mix.Database.Entities.Cms
  commentId: N:Mix.Database.Entities.Cms
  name: Mix.Database.Entities.Cms
  nameWithType: Mix.Database.Entities.Cms
  fullName: Mix.Database.Entities.Cms
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Mix.Database.Entities.Base.TenantEntityBase{System.Int32}
  commentId: T:Mix.Database.Entities.Base.TenantEntityBase{System.Int32}
  parent: Mix.Database.Entities.Base
  definition: Mix.Database.Entities.Base.TenantEntityBase`1
  name: TenantEntityBase<Int32>
  nameWithType: TenantEntityBase<Int32>
  fullName: Mix.Database.Entities.Base.TenantEntityBase<System.Int32>
  nameWithType.vb: TenantEntityBase(Of Int32)
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of System.Int32)
  name.vb: TenantEntityBase(Of Int32)
  spec.csharp:
  - uid: Mix.Database.Entities.Base.TenantEntityBase`1
    name: TenantEntityBase
    nameWithType: TenantEntityBase
    fullName: Mix.Database.Entities.Base.TenantEntityBase
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.Entities.Base.TenantEntityBase`1
    name: TenantEntityBase
    nameWithType: TenantEntityBase
    fullName: Mix.Database.Entities.Base.TenantEntityBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.Entities.Base.TenantEntityUniqueNameBase{System.Int32}
  commentId: T:Mix.Database.Entities.Base.TenantEntityUniqueNameBase{System.Int32}
  parent: Mix.Database.Entities.Base
  definition: Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1
  name: TenantEntityUniqueNameBase<Int32>
  nameWithType: TenantEntityUniqueNameBase<Int32>
  fullName: Mix.Database.Entities.Base.TenantEntityUniqueNameBase<System.Int32>
  nameWithType.vb: TenantEntityUniqueNameBase(Of Int32)
  fullName.vb: Mix.Database.Entities.Base.TenantEntityUniqueNameBase(Of System.Int32)
  name.vb: TenantEntityUniqueNameBase(Of Int32)
  spec.csharp:
  - uid: Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1
    name: TenantEntityUniqueNameBase
    nameWithType: TenantEntityUniqueNameBase
    fullName: Mix.Database.Entities.Base.TenantEntityUniqueNameBase
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1
    name: TenantEntityUniqueNameBase
    nameWithType: TenantEntityUniqueNameBase
    fullName: Mix.Database.Entities.Base.TenantEntityUniqueNameBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.Entities.Base.TenantEntityUniqueNameBase{System.Int32}.SystemName
  commentId: P:Mix.Database.Entities.Base.TenantEntityUniqueNameBase{System.Int32}.SystemName
  parent: Mix.Database.Entities.Base.TenantEntityUniqueNameBase{System.Int32}
  definition: Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1.SystemName
  name: SystemName
  nameWithType: TenantEntityUniqueNameBase<Int32>.SystemName
  fullName: Mix.Database.Entities.Base.TenantEntityUniqueNameBase<System.Int32>.SystemName
  nameWithType.vb: TenantEntityUniqueNameBase(Of Int32).SystemName
  fullName.vb: Mix.Database.Entities.Base.TenantEntityUniqueNameBase(Of System.Int32).SystemName
- uid: Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.DisplayName
  commentId: P:Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.DisplayName
  parent: Mix.Database.Entities.Base.TenantEntityBase{System.Int32}
  definition: Mix.Database.Entities.Base.TenantEntityBase`1.DisplayName
  name: DisplayName
  nameWithType: TenantEntityBase<Int32>.DisplayName
  fullName: Mix.Database.Entities.Base.TenantEntityBase<System.Int32>.DisplayName
  nameWithType.vb: TenantEntityBase(Of Int32).DisplayName
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of System.Int32).DisplayName
- uid: Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.Description
  commentId: P:Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.Description
  parent: Mix.Database.Entities.Base.TenantEntityBase{System.Int32}
  definition: Mix.Database.Entities.Base.TenantEntityBase`1.Description
  name: Description
  nameWithType: TenantEntityBase<Int32>.Description
  fullName: Mix.Database.Entities.Base.TenantEntityBase<System.Int32>.Description
  nameWithType.vb: TenantEntityBase(Of Int32).Description
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of System.Int32).Description
- uid: Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.MixTenantId
  commentId: P:Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.MixTenantId
  parent: Mix.Database.Entities.Base.TenantEntityBase{System.Int32}
  definition: Mix.Database.Entities.Base.TenantEntityBase`1.MixTenantId
  name: MixTenantId
  nameWithType: TenantEntityBase<Int32>.MixTenantId
  fullName: Mix.Database.Entities.Base.TenantEntityBase<System.Int32>.MixTenantId
  nameWithType.vb: TenantEntityBase(Of Int32).MixTenantId
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of System.Int32).MixTenantId
- uid: Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.MixTenant
  commentId: P:Mix.Database.Entities.Base.TenantEntityBase{System.Int32}.MixTenant
  parent: Mix.Database.Entities.Base.TenantEntityBase{System.Int32}
  definition: Mix.Database.Entities.Base.TenantEntityBase`1.MixTenant
  name: MixTenant
  nameWithType: TenantEntityBase<Int32>.MixTenant
  fullName: Mix.Database.Entities.Base.TenantEntityBase<System.Int32>.MixTenant
  nameWithType.vb: TenantEntityBase(Of Int32).MixTenant
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of System.Int32).MixTenant
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Database.Entities.Base.TenantEntityBase`1
  commentId: T:Mix.Database.Entities.Base.TenantEntityBase`1
  name: TenantEntityBase<TPrimaryKey>
  nameWithType: TenantEntityBase<TPrimaryKey>
  fullName: Mix.Database.Entities.Base.TenantEntityBase<TPrimaryKey>
  nameWithType.vb: TenantEntityBase(Of TPrimaryKey)
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of TPrimaryKey)
  name.vb: TenantEntityBase(Of TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.Entities.Base.TenantEntityBase`1
    name: TenantEntityBase
    nameWithType: TenantEntityBase
    fullName: Mix.Database.Entities.Base.TenantEntityBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.Entities.Base.TenantEntityBase`1
    name: TenantEntityBase
    nameWithType: TenantEntityBase
    fullName: Mix.Database.Entities.Base.TenantEntityBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.Entities.Base
  commentId: N:Mix.Database.Entities.Base
  name: Mix.Database.Entities.Base
  nameWithType: Mix.Database.Entities.Base
  fullName: Mix.Database.Entities.Base
- uid: Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1
  commentId: T:Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1
  name: TenantEntityUniqueNameBase<TPrimaryKey>
  nameWithType: TenantEntityUniqueNameBase<TPrimaryKey>
  fullName: Mix.Database.Entities.Base.TenantEntityUniqueNameBase<TPrimaryKey>
  nameWithType.vb: TenantEntityUniqueNameBase(Of TPrimaryKey)
  fullName.vb: Mix.Database.Entities.Base.TenantEntityUniqueNameBase(Of TPrimaryKey)
  name.vb: TenantEntityUniqueNameBase(Of TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1
    name: TenantEntityUniqueNameBase
    nameWithType: TenantEntityUniqueNameBase
    fullName: Mix.Database.Entities.Base.TenantEntityUniqueNameBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1
    name: TenantEntityUniqueNameBase
    nameWithType: TenantEntityUniqueNameBase
    fullName: Mix.Database.Entities.Base.TenantEntityUniqueNameBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1.SystemName
  commentId: P:Mix.Database.Entities.Base.TenantEntityUniqueNameBase`1.SystemName
  name: SystemName
  nameWithType: TenantEntityUniqueNameBase<TPrimaryKey>.SystemName
  fullName: Mix.Database.Entities.Base.TenantEntityUniqueNameBase<TPrimaryKey>.SystemName
  nameWithType.vb: TenantEntityUniqueNameBase(Of TPrimaryKey).SystemName
  fullName.vb: Mix.Database.Entities.Base.TenantEntityUniqueNameBase(Of TPrimaryKey).SystemName
- uid: Mix.Database.Entities.Base.TenantEntityBase`1.DisplayName
  commentId: P:Mix.Database.Entities.Base.TenantEntityBase`1.DisplayName
  name: DisplayName
  nameWithType: TenantEntityBase<TPrimaryKey>.DisplayName
  fullName: Mix.Database.Entities.Base.TenantEntityBase<TPrimaryKey>.DisplayName
  nameWithType.vb: TenantEntityBase(Of TPrimaryKey).DisplayName
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of TPrimaryKey).DisplayName
- uid: Mix.Database.Entities.Base.TenantEntityBase`1.Description
  commentId: P:Mix.Database.Entities.Base.TenantEntityBase`1.Description
  name: Description
  nameWithType: TenantEntityBase<TPrimaryKey>.Description
  fullName: Mix.Database.Entities.Base.TenantEntityBase<TPrimaryKey>.Description
  nameWithType.vb: TenantEntityBase(Of TPrimaryKey).Description
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of TPrimaryKey).Description
- uid: Mix.Database.Entities.Base.TenantEntityBase`1.MixTenantId
  commentId: P:Mix.Database.Entities.Base.TenantEntityBase`1.MixTenantId
  name: MixTenantId
  nameWithType: TenantEntityBase<TPrimaryKey>.MixTenantId
  fullName: Mix.Database.Entities.Base.TenantEntityBase<TPrimaryKey>.MixTenantId
  nameWithType.vb: TenantEntityBase(Of TPrimaryKey).MixTenantId
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of TPrimaryKey).MixTenantId
- uid: Mix.Database.Entities.Base.TenantEntityBase`1.MixTenant
  commentId: P:Mix.Database.Entities.Base.TenantEntityBase`1.MixTenant
  name: MixTenant
  nameWithType: TenantEntityBase<TPrimaryKey>.MixTenant
  fullName: Mix.Database.Entities.Base.TenantEntityBase<TPrimaryKey>.MixTenant
  nameWithType.vb: TenantEntityBase(Of TPrimaryKey).MixTenant
  fullName.vb: Mix.Database.Entities.Base.TenantEntityBase(Of TPrimaryKey).MixTenant
- uid: Mix.Database.Entities.Cms.MixConfiguration.MixConfigurationContents*
  commentId: Overload:Mix.Database.Entities.Cms.MixConfiguration.MixConfigurationContents
  name: MixConfigurationContents
  nameWithType: MixConfiguration.MixConfigurationContents
  fullName: Mix.Database.Entities.Cms.MixConfiguration.MixConfigurationContents
- uid: System.Collections.Generic.ICollection{Mix.Database.Entities.Cms.MixConfigurationContent}
  commentId: T:System.Collections.Generic.ICollection{Mix.Database.Entities.Cms.MixConfigurationContent}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.ICollection`1
  name: ICollection<MixConfigurationContent>
  nameWithType: ICollection<MixConfigurationContent>
  fullName: System.Collections.Generic.ICollection<Mix.Database.Entities.Cms.MixConfigurationContent>
  nameWithType.vb: ICollection(Of MixConfigurationContent)
  fullName.vb: System.Collections.Generic.ICollection(Of Mix.Database.Entities.Cms.MixConfigurationContent)
  name.vb: ICollection(Of MixConfigurationContent)
  spec.csharp:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Mix.Database.Entities.Cms.MixConfigurationContent
    name: MixConfigurationContent
    nameWithType: MixConfigurationContent
    fullName: Mix.Database.Entities.Cms.MixConfigurationContent
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Mix.Database.Entities.Cms.MixConfigurationContent
    name: MixConfigurationContent
    nameWithType: MixConfigurationContent
    fullName: Mix.Database.Entities.Cms.MixConfigurationContent
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.ICollection`1
  commentId: T:System.Collections.Generic.ICollection`1
  isExternal: true
  name: ICollection<T>
  nameWithType: ICollection<T>
  fullName: System.Collections.Generic.ICollection<T>
  nameWithType.vb: ICollection(Of T)
  fullName.vb: System.Collections.Generic.ICollection(Of T)
  name.vb: ICollection(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
