### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.SQLITE.Base
  commentId: N:Mix.Database.EntityConfigurations.SQLITE.Base
  id: Mix.Database.EntityConfigurations.SQLITE.Base
  children:
  - Mix.Database.EntityConfigurations.SQLITE.Base.SqliteAssociationBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualSEOContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualUniqueNameContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityUniqueNameBaseConfiguration`2
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.SQLITE.Base
  nameWithType: Mix.Database.EntityConfigurations.SQLITE.Base
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteAssociationBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.Base.SqliteAssociationBaseConfiguration`2
  name: SqliteAssociationBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqliteAssociationBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteAssociationBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqliteAssociationBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteAssociationBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqliteAssociationBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteAssociationBaseConfiguration`2
    name: SqliteAssociationBaseConfiguration
    nameWithType: SqliteAssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteAssociationBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteAssociationBaseConfiguration`2
    name: SqliteAssociationBaseConfiguration
    nameWithType: SqliteAssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteAssociationBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration`2
  name: SqliteEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqliteEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqliteEntityBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqliteEntityBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration`2
    name: SqliteEntityBaseConfiguration
    nameWithType: SqliteEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration`2
    name: SqliteEntityBaseConfiguration
    nameWithType: SqliteEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration`2
  name: SqliteMultilingualContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqliteMultilingualContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqliteMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqliteMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration`2
    name: SqliteMultilingualContentBaseConfiguration
    nameWithType: SqliteMultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration`2
    name: SqliteMultilingualContentBaseConfiguration
    nameWithType: SqliteMultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualSEOContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualSEOContentBaseConfiguration`2
  name: SqliteMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqliteMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqliteMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqliteMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualSEOContentBaseConfiguration`2
    name: SqliteMultilingualSEOContentBaseConfiguration
    nameWithType: SqliteMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualSEOContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualSEOContentBaseConfiguration`2
    name: SqliteMultilingualSEOContentBaseConfiguration
    nameWithType: SqliteMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualSEOContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualUniqueNameContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualUniqueNameContentBaseConfiguration`2
  name: SqliteMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqliteMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqliteMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqliteMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualUniqueNameContentBaseConfiguration`2
    name: SqliteMultilingualUniqueNameContentBaseConfiguration
    nameWithType: SqliteMultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualUniqueNameContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualUniqueNameContentBaseConfiguration`2
    name: SqliteMultilingualUniqueNameContentBaseConfiguration
    nameWithType: SqliteMultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualUniqueNameContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityBaseConfiguration`2
  name: SqliteTenantEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqliteTenantEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqliteTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqliteTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityBaseConfiguration`2
    name: SqliteTenantEntityBaseConfiguration
    nameWithType: SqliteTenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityBaseConfiguration`2
    name: SqliteTenantEntityBaseConfiguration
    nameWithType: SqliteTenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityUniqueNameBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityUniqueNameBaseConfiguration`2
  name: SqliteTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqliteTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqliteTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqliteTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityUniqueNameBaseConfiguration`2
    name: SqliteTenantEntityUniqueNameBaseConfiguration
    nameWithType: SqliteTenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityUniqueNameBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityUniqueNameBaseConfiguration`2
    name: SqliteTenantEntityUniqueNameBaseConfiguration
    nameWithType: SqliteTenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteTenantEntityUniqueNameBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
