### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration`2
  id: MySqlEntityBaseConfiguration`2
  parent: Mix.Database.EntityConfigurations.MYSQL.Base
  children: []
  langs:
  - csharp
  - vb
  name: MySqlEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: MySqlEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration<T, TPrimaryKey>
  type: Class
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/MYSQL/Base/MySqlEntityBaseConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MySqlEntityBaseConfiguration
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/MYSQL/Base/MySqlEntityBaseConfiguration.cs
    startLine: 4
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations.MYSQL.Base
  syntax:
    content: 'public abstract class MySqlEntityBaseConfiguration<T, TPrimaryKey> : EntityBaseConfiguration<T, TPrimaryKey, MySqlDatabaseConstants> where T : EntityBase<TPrimaryKey> where TPrimaryKey : IComparable'
    typeParameters:
    - id: T
    - id: TPrimaryKey
    content.vb: >-
      Public MustInherit Class MySqlEntityBaseConfiguration(Of T As EntityBase(Of TPrimaryKey), TPrimaryKey As IComparable)
          Inherits EntityBaseConfiguration(Of T, TPrimaryKey, MySqlDatabaseConstants)
  inheritance:
  - System.Object
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}
  derivedClasses:
  - Mix.Database.EntityConfigurations.MYSQL.MixContributorConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDatabaseColumnConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDataConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDataContentAssociationConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDataContentValueConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDiscussionConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixPostConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixTenantConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixViewTemplateContentConfiguration
  inheritedMembers:
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}.Config
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}.Configure(EntityTypeBuilder{{T}})
  nameWithType.vb: MySqlEntityBaseConfiguration(Of T, TPrimaryKey)
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
  fullName.vb: Mix.Database.EntityConfigurations.MYSQL.Base.MySqlEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: MySqlEntityBaseConfiguration(Of T, TPrimaryKey)
references:
- uid: Mix.Database.EntityConfigurations.MYSQL.Base
  commentId: N:Mix.Database.EntityConfigurations.MYSQL.Base
  name: Mix.Database.EntityConfigurations.MYSQL.Base
  nameWithType: Mix.Database.EntityConfigurations.MYSQL.Base
  fullName: Mix.Database.EntityConfigurations.MYSQL.Base
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}
  commentId: T:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}
  parent: Mix.Database.EntityConfigurations.Base
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  name: EntityBaseConfiguration<T, TPrimaryKey, MySqlDatabaseConstants>
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, MySqlDatabaseConstants>
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants>
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, MySqlDatabaseConstants)
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants)
  name.vb: EntityBaseConfiguration(Of T, TPrimaryKey, MySqlDatabaseConstants)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants
    name: MySqlDatabaseConstants
    nameWithType: MySqlDatabaseConstants
    fullName: Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants
    name: MySqlDatabaseConstants
    nameWithType: MySqlDatabaseConstants
    fullName: Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}.Config
  commentId: P:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}.Config
  parent: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  name: Config
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, MySqlDatabaseConstants>.Config
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants>.Config
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, MySqlDatabaseConstants).Config
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants).Config
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}.Configure(EntityTypeBuilder{{T}})
  commentId: M:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}.Configure(EntityTypeBuilder{`0})
  parent: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants}
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  name: Configure(EntityTypeBuilder<T>)
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, MySqlDatabaseConstants>.Configure(EntityTypeBuilder<T>)
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants>.Configure(EntityTypeBuilder<T>)
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, MySqlDatabaseConstants).Configure(EntityTypeBuilder(Of T))
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants).Configure(EntityTypeBuilder(Of T))
  name.vb: Configure(EntityTypeBuilder(Of T))
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration<T, TPrimaryKey, MySqlDatabaseConstants>.Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants>.Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration(Of T, TPrimaryKey, MySqlDatabaseConstants).Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants).Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  name: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base
  commentId: N:Mix.Database.EntityConfigurations.Base
  name: Mix.Database.EntityConfigurations.Base
  nameWithType: Mix.Database.EntityConfigurations.Base
  fullName: Mix.Database.EntityConfigurations.Base
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  commentId: P:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  name: Config
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  commentId: M:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  isExternal: true
  name: Configure(EntityTypeBuilder<T>)
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  name.vb: Configure(EntityTypeBuilder(Of T))
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
