### YamlMime:ManagedReference
items:
- uid: Mix.Heart.EntityConfigurations.MSSQL
  commentId: N:Mix.Heart.EntityConfigurations.MSSQL
  id: Mix.Heart.EntityConfigurations.MSSQL
  children:
  - Mix.Heart.EntityConfigurations.MSSQL.MixCacheConfiguration
  langs:
  - csharp
  - vb
  name: Mix.Heart.EntityConfigurations.MSSQL
  nameWithType: Mix.Heart.EntityConfigurations.MSSQL
  fullName: Mix.Heart.EntityConfigurations.MSSQL
  type: Namespace
  assemblies:
  - mix.heart
references:
- uid: Mix.Heart.EntityConfigurations.MSSQL.MixCacheConfiguration
  commentId: T:Mix.Heart.EntityConfigurations.MSSQL.MixCacheConfiguration
  name: MixCacheConfiguration
  nameWithType: MixCacheConfiguration
  fullName: Mix.Heart.EntityConfigurations.MSSQL.MixCacheConfiguration
