### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.SQLSERVER
  commentId: N:Mix.Database.EntityConfigurations.SQLSERVER
  id: Mix.Database.EntityConfigurations.SQLSERVER
  children:
  - Mix.Database.EntityConfigurations.SQLSERVER.MixConfigurationConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixConfigurationContentConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixContributorConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixCultureConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseColumnConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseContextConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDataConentAssociationConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDataConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDataContentConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDataContentValueConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDiscussionConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDomainConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixLanguageConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixLanguageContentConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixMediaConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixModuleConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixModuleContentConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixPageConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixPageContentConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixPostConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixPostContentConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixTenantConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixThemeConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixUrlAliasConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixViewTemplateContentConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.SQLSERVER
  nameWithType: Mix.Database.EntityConfigurations.SQLSERVER
  fullName: Mix.Database.EntityConfigurations.SQLSERVER
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixConfigurationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixConfigurationConfiguration
  name: MixConfigurationConfiguration
  nameWithType: MixConfigurationConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixConfigurationConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixConfigurationContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixConfigurationContentConfiguration
  name: MixConfigurationContentConfiguration
  nameWithType: MixConfigurationContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixConfigurationContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixContributorConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixContributorConfiguration
  name: MixContributorConfiguration
  nameWithType: MixContributorConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixContributorConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixCultureConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixCultureConfiguration
  name: MixCultureConfiguration
  nameWithType: MixCultureConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixCultureConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseColumnConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseColumnConfiguration
  name: MixDatabaseColumnConfiguration
  nameWithType: MixDatabaseColumnConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseColumnConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseConfiguration
  name: MixDatabaseConfiguration
  nameWithType: MixDatabaseConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseContextConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseContextConfiguration
  name: MixDatabaseContextConfiguration
  nameWithType: MixDatabaseContextConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseContextConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixDataConentAssociationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixDataConentAssociationConfiguration
  name: MixDataConentAssociationConfiguration
  nameWithType: MixDataConentAssociationConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixDataConentAssociationConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixDataConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixDataConfiguration
  name: MixDataConfiguration
  nameWithType: MixDataConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixDataConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixDataContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixDataContentConfiguration
  name: MixDataContentConfiguration
  nameWithType: MixDataContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixDataContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixDataContentValueConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixDataContentValueConfiguration
  name: MixDataContentValueConfiguration
  nameWithType: MixDataContentValueConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixDataContentValueConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixDiscussionConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixDiscussionConfiguration
  name: MixDiscussionConfiguration
  nameWithType: MixDiscussionConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixDiscussionConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixDomainConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixDomainConfiguration
  name: MixDomainConfiguration
  nameWithType: MixDomainConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixDomainConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixLanguageConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixLanguageConfiguration
  name: MixLanguageConfiguration
  nameWithType: MixLanguageConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixLanguageConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixLanguageContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixLanguageContentConfiguration
  name: MixLanguageContentConfiguration
  nameWithType: MixLanguageContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixLanguageContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixMediaConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixMediaConfiguration
  name: MixMediaConfiguration
  nameWithType: MixMediaConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixMediaConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixModuleConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixModuleConfiguration
  name: MixModuleConfiguration
  nameWithType: MixModuleConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixModuleConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixModuleContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixModuleContentConfiguration
  name: MixModuleContentConfiguration
  nameWithType: MixModuleContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixModuleContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixPageConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixPageConfiguration
  name: MixPageConfiguration
  nameWithType: MixPageConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixPageConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixPageContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixPageContentConfiguration
  name: MixPageContentConfiguration
  nameWithType: MixPageContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixPageContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixPostConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixPostConfiguration
  name: MixPostConfiguration
  nameWithType: MixPostConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixPostConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixPostContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixPostContentConfiguration
  name: MixPostContentConfiguration
  nameWithType: MixPostContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixPostContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixTenantConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixTenantConfiguration
  name: MixTenantConfiguration
  nameWithType: MixTenantConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixTenantConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixThemeConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixThemeConfiguration
  name: MixThemeConfiguration
  nameWithType: MixThemeConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixThemeConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixUrlAliasConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixUrlAliasConfiguration
  name: MixUrlAliasConfiguration
  nameWithType: MixUrlAliasConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixUrlAliasConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.MixViewTemplateContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.MixViewTemplateContentConfiguration
  name: MixViewTemplateContentConfiguration
  nameWithType: MixViewTemplateContentConfiguration
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.MixViewTemplateContentConfiguration
- uid: Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants
  name: SqlServerDatabaseConstants
  nameWithType: SqlServerDatabaseConstants
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants
