### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.MYSQL
  commentId: N:Mix.Database.EntityConfigurations.MYSQL
  id: Mix.Database.EntityConfigurations.MYSQL
  children:
  - Mix.Database.EntityConfigurations.MYSQL.MixConfigurationConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixConfigurationContentConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixContributorConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixCultureConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDatabaseColumnConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDatabaseConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDatabaseContextConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDataConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDataContentAssociationConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDataContentConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDataContentValueConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDiscussionConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixDomainConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixLanguageConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixLanguageContentConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixMediaConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixModuleConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixModuleContentConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixPageConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixPageContentConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixPostConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixPostContentConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixTenantConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixThemeConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixUrlAliasConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MixViewTemplateContentConfiguration
  - Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.MYSQL
  nameWithType: Mix.Database.EntityConfigurations.MYSQL
  fullName: Mix.Database.EntityConfigurations.MYSQL
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.MYSQL.MixConfigurationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixConfigurationConfiguration
  name: MixConfigurationConfiguration
  nameWithType: MixConfigurationConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixConfigurationConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixConfigurationContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixConfigurationContentConfiguration
  name: MixConfigurationContentConfiguration
  nameWithType: MixConfigurationContentConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixConfigurationContentConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixContributorConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixContributorConfiguration
  name: MixContributorConfiguration
  nameWithType: MixContributorConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixContributorConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixCultureConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixCultureConfiguration
  name: MixCultureConfiguration
  nameWithType: MixCultureConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixCultureConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixDatabaseColumnConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixDatabaseColumnConfiguration
  name: MixDatabaseColumnConfiguration
  nameWithType: MixDatabaseColumnConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixDatabaseColumnConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixDatabaseConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixDatabaseConfiguration
  name: MixDatabaseConfiguration
  nameWithType: MixDatabaseConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixDatabaseConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixDatabaseContextConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixDatabaseContextConfiguration
  name: MixDatabaseContextConfiguration
  nameWithType: MixDatabaseContextConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixDatabaseContextConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixDataConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixDataConfiguration
  name: MixDataConfiguration
  nameWithType: MixDataConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixDataConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixDataContentAssociationConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixDataContentAssociationConfiguration
  name: MixDataContentAssociationConfiguration
  nameWithType: MixDataContentAssociationConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixDataContentAssociationConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixDataContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixDataContentConfiguration
  name: MixDataContentConfiguration
  nameWithType: MixDataContentConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixDataContentConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixDataContentValueConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixDataContentValueConfiguration
  name: MixDataContentValueConfiguration
  nameWithType: MixDataContentValueConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixDataContentValueConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixDiscussionConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixDiscussionConfiguration
  name: MixDiscussionConfiguration
  nameWithType: MixDiscussionConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixDiscussionConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixDomainConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixDomainConfiguration
  name: MixDomainConfiguration
  nameWithType: MixDomainConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixDomainConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixLanguageConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixLanguageConfiguration
  name: MixLanguageConfiguration
  nameWithType: MixLanguageConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixLanguageConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixLanguageContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixLanguageContentConfiguration
  name: MixLanguageContentConfiguration
  nameWithType: MixLanguageContentConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixLanguageContentConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixMediaConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixMediaConfiguration
  name: MixMediaConfiguration
  nameWithType: MixMediaConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixMediaConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixModuleConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixModuleConfiguration
  name: MixModuleConfiguration
  nameWithType: MixModuleConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixModuleConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixModuleContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixModuleContentConfiguration
  name: MixModuleContentConfiguration
  nameWithType: MixModuleContentConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixModuleContentConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixPageConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixPageConfiguration
  name: MixPageConfiguration
  nameWithType: MixPageConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixPageConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixPageContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixPageContentConfiguration
  name: MixPageContentConfiguration
  nameWithType: MixPageContentConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixPageContentConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixPostConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixPostConfiguration
  name: MixPostConfiguration
  nameWithType: MixPostConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixPostConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixPostContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixPostContentConfiguration
  name: MixPostContentConfiguration
  nameWithType: MixPostContentConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixPostContentConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixTenantConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixTenantConfiguration
  name: MixTenantConfiguration
  nameWithType: MixTenantConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixTenantConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixThemeConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixThemeConfiguration
  name: MixThemeConfiguration
  nameWithType: MixThemeConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixThemeConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixUrlAliasConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixUrlAliasConfiguration
  name: MixUrlAliasConfiguration
  nameWithType: MixUrlAliasConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixUrlAliasConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MixViewTemplateContentConfiguration
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MixViewTemplateContentConfiguration
  name: MixViewTemplateContentConfiguration
  nameWithType: MixViewTemplateContentConfiguration
  fullName: Mix.Database.EntityConfigurations.MYSQL.MixViewTemplateContentConfiguration
- uid: Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants
  name: MySqlDatabaseConstants
  nameWithType: MySqlDatabaseConstants
  fullName: Mix.Database.EntityConfigurations.MYSQL.MySqlDatabaseConstants
