### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.SQLITE.Quartz
  commentId: N:Mix.Database.EntityConfigurations.SQLITE.Quartz
  id: Mix.Database.EntityConfigurations.SQLITE.Quartz
  children:
  - Mix.Database.EntityConfigurations.SQLITE.Quartz.SQLiteQuartzConfigurations
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.SQLITE.Quartz
  nameWithType: Mix.Database.EntityConfigurations.SQLITE.Quartz
  fullName: Mix.Database.EntityConfigurations.SQLITE.Quartz
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.SQLITE.Quartz.SQLiteQuartzConfigurations
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.Quartz.SQLiteQuartzConfigurations
  name: SQLiteQuartzConfigurations
  nameWithType: SQLiteQuartzConfigurations
  fullName: Mix.Database.EntityConfigurations.SQLITE.Quartz.SQLiteQuartzConfigurations
