### YamlMime:ManagedReference
items:
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL
  commentId: N:Mix.Cms.Lib.Models.EntityConfigurations.MySQL
  id: Mix.Cms.Lib.Models.EntityConfigurations.MySQL
  children:
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeFieldConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetReferenceConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetValueConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeValueConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCacheConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCmsUserConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixConfigurationConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCultureConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixFileConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixLanguageConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixMediaConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModuleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModuleDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModulePostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPageConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPageModuleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPagePostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageNavigationConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageRoleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostMediaConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostModuleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedAttributeDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedAttributeSetConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedPostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixTemplateConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixThemeConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixUrlAliasConfiguration
  langs:
  - csharp
  - vb
  name: Mix.Cms.Lib.Models.EntityConfigurations.MySQL
  nameWithType: Mix.Cms.Lib.Models.EntityConfigurations.MySQL
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL
  type: Namespace
  assemblies:
  - Mix.Cms.Lib
references:
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeFieldConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeFieldConfiguration
  name: MixAttributeFieldConfiguration
  nameWithType: MixAttributeFieldConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeFieldConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetConfiguration
  name: MixAttributeSetConfiguration
  nameWithType: MixAttributeSetConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetDataConfiguration
  name: MixAttributeSetDataConfiguration
  nameWithType: MixAttributeSetDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetReferenceConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetReferenceConfiguration
  name: MixAttributeSetReferenceConfiguration
  nameWithType: MixAttributeSetReferenceConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetReferenceConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetValueConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetValueConfiguration
  name: MixAttributeSetValueConfiguration
  nameWithType: MixAttributeSetValueConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeSetValueConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeValueConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeValueConfiguration
  name: MixAttributeValueConfiguration
  nameWithType: MixAttributeValueConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixAttributeValueConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCacheConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCacheConfiguration
  name: MixCacheConfiguration
  nameWithType: MixCacheConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCacheConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCmsUserConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCmsUserConfiguration
  name: MixCmsUserConfiguration
  nameWithType: MixCmsUserConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCmsUserConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixConfigurationConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixConfigurationConfiguration
  name: MixConfigurationConfiguration
  nameWithType: MixConfigurationConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixConfigurationConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCultureConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCultureConfiguration
  name: MixCultureConfiguration
  nameWithType: MixCultureConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixCultureConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixFileConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixFileConfiguration
  name: MixFileConfiguration
  nameWithType: MixFileConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixFileConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixLanguageConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixLanguageConfiguration
  name: MixLanguageConfiguration
  nameWithType: MixLanguageConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixLanguageConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixMediaConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixMediaConfiguration
  name: MixMediaConfiguration
  nameWithType: MixMediaConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixMediaConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModuleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModuleConfiguration
  name: MixModuleConfiguration
  nameWithType: MixModuleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModuleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModuleDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModuleDataConfiguration
  name: MixModuleDataConfiguration
  nameWithType: MixModuleDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModuleDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModulePostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModulePostConfiguration
  name: MixModulePostConfiguration
  nameWithType: MixModulePostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixModulePostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPageConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPageConfiguration
  name: MixPageConfiguration
  nameWithType: MixPageConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPageConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPageModuleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPageModuleConfiguration
  name: MixPageModuleConfiguration
  nameWithType: MixPageModuleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPageModuleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPagePostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPagePostConfiguration
  name: MixPagePostConfiguration
  nameWithType: MixPagePostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPagePostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageConfiguration
  name: MixPortalPageConfiguration
  nameWithType: MixPortalPageConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageNavigationConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageNavigationConfiguration
  name: MixPortalPageNavigationConfiguration
  nameWithType: MixPortalPageNavigationConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageNavigationConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageRoleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageRoleConfiguration
  name: MixPortalPageRoleConfiguration
  nameWithType: MixPortalPageRoleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPortalPageRoleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostConfiguration
  name: MixPostConfiguration
  nameWithType: MixPostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostMediaConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostMediaConfiguration
  name: MixPostMediaConfiguration
  nameWithType: MixPostMediaConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostMediaConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostModuleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostModuleConfiguration
  name: MixPostModuleConfiguration
  nameWithType: MixPostModuleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixPostModuleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedAttributeDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedAttributeDataConfiguration
  name: MixRelatedAttributeDataConfiguration
  nameWithType: MixRelatedAttributeDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedAttributeDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedAttributeSetConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedAttributeSetConfiguration
  name: MixRelatedAttributeSetConfiguration
  nameWithType: MixRelatedAttributeSetConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedAttributeSetConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedDataConfiguration
  name: MixRelatedDataConfiguration
  nameWithType: MixRelatedDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedPostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedPostConfiguration
  name: MixRelatedPostConfiguration
  nameWithType: MixRelatedPostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixRelatedPostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixTemplateConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixTemplateConfiguration
  name: MixTemplateConfiguration
  nameWithType: MixTemplateConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixTemplateConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixThemeConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixThemeConfiguration
  name: MixThemeConfiguration
  nameWithType: MixThemeConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixThemeConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixUrlAliasConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixUrlAliasConfiguration
  name: MixUrlAliasConfiguration
  nameWithType: MixUrlAliasConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MySQL.MixUrlAliasConfiguration
