### YamlMime:ManagedReference
items:
- uid: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration
  commentId: T:Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration
  id: MixCacheConfiguration
  parent: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  children:
  - Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration.Configure(EntityTypeBuilder{Mix.Heart.Entities.Cache.MixCache})
  langs:
  - csharp
  - vb
  name: MixCacheConfiguration
  nameWithType: MixCacheConfiguration
  fullName: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration
  type: Class
  source:
    remote:
      path: src/Mix.Heart/EntitiyConfigurations/SQLITE/MixCacheConfiguration.cs
      branch: develop/v2
      repo: https://github.com/mixcore/mix.heart.git
    id: MixCacheConfiguration
    path: ../../mix.core/src/framework/mix-heart/src/Mix.Heart/EntitiyConfigurations/SQLITE/MixCacheConfiguration.cs
    startLine: 8
  assemblies:
  - mix.heart
  namespace: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  syntax:
    content: 'public class MixCacheConfiguration : IEntityTypeConfiguration<MixCache>'
    content.vb: >-
      Public Class MixCacheConfiguration
          Inherits IEntityTypeConfiguration(Of MixCache)
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration.Configure(EntityTypeBuilder{Mix.Heart.Entities.Cache.MixCache})
  commentId: M:Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration.Configure(EntityTypeBuilder{Mix.Heart.Entities.Cache.MixCache})
  id: Configure(EntityTypeBuilder{Mix.Heart.Entities.Cache.MixCache})
  parent: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration
  langs:
  - csharp
  - vb
  name: Configure(EntityTypeBuilder<MixCache>)
  nameWithType: MixCacheConfiguration.Configure(EntityTypeBuilder<MixCache>)
  fullName: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration.Configure(EntityTypeBuilder<Mix.Heart.Entities.Cache.MixCache>)
  type: Method
  source:
    remote:
      path: src/Mix.Heart/EntitiyConfigurations/SQLITE/MixCacheConfiguration.cs
      branch: develop/v2
      repo: https://github.com/mixcore/mix.heart.git
    id: Configure
    path: ../../mix.core/src/framework/mix-heart/src/Mix.Heart/EntitiyConfigurations/SQLITE/MixCacheConfiguration.cs
    startLine: 10
  assemblies:
  - mix.heart
  namespace: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  syntax:
    content: public void Configure(EntityTypeBuilder<MixCache> entity)
    parameters:
    - id: entity
      type: EntityTypeBuilder{Mix.Heart.Entities.Cache.MixCache}
    content.vb: Public Sub Configure(entity As EntityTypeBuilder(Of MixCache))
  overload: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration.Configure*
  nameWithType.vb: MixCacheConfiguration.Configure(EntityTypeBuilder(Of MixCache))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration.Configure(EntityTypeBuilder(Of Mix.Heart.Entities.Cache.MixCache))
  name.vb: Configure(EntityTypeBuilder(Of MixCache))
references:
- uid: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  commentId: N:Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  name: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  nameWithType: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
  fullName: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration.Configure*
  commentId: Overload:Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration.Configure
  name: Configure
  nameWithType: MixCacheConfiguration.Configure
  fullName: Mix.Heart.Infrastructure.EntityConfigurations.SQLITE.MixCacheConfiguration.Configure
- uid: EntityTypeBuilder{Mix.Heart.Entities.Cache.MixCache}
  commentId: '!:EntityTypeBuilder{Mix.Heart.Entities.Cache.MixCache}'
  definition: EntityTypeBuilder`1
  name: EntityTypeBuilder<MixCache>
  nameWithType: EntityTypeBuilder<MixCache>
  fullName: EntityTypeBuilder<Mix.Heart.Entities.Cache.MixCache>
  nameWithType.vb: EntityTypeBuilder(Of MixCache)
  fullName.vb: EntityTypeBuilder(Of Mix.Heart.Entities.Cache.MixCache)
  name.vb: EntityTypeBuilder(Of MixCache)
  spec.csharp:
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Mix.Heart.Entities.Cache.MixCache
    name: MixCache
    nameWithType: MixCache
    fullName: Mix.Heart.Entities.Cache.MixCache
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Mix.Heart.Entities.Cache.MixCache
    name: MixCache
    nameWithType: MixCache
    fullName: Mix.Heart.Entities.Cache.MixCache
  - name: )
    nameWithType: )
    fullName: )
- uid: EntityTypeBuilder`1
  isExternal: true
  name: EntityTypeBuilder<>
  nameWithType: EntityTypeBuilder<>
  fullName: EntityTypeBuilder<>
  nameWithType.vb: EntityTypeBuilder(Of )
  fullName.vb: EntityTypeBuilder(Of )
  name.vb: EntityTypeBuilder(Of )
  spec.csharp:
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
