### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants
  commentId: T:Mix.Database.EntityConfigurations.IDatabaseConstants
  id: IDatabaseConstants
  parent: Mix.Database.EntityConfigurations
  children:
  - Mix.Database.EntityConfigurations.IDatabaseConstants.CharSet
  - Mix.Database.EntityConfigurations.IDatabaseConstants.DatabaseCollation
  - Mix.Database.EntityConfigurations.IDatabaseConstants.DateTime
  - Mix.Database.EntityConfigurations.IDatabaseConstants.GenerateUUID
  - Mix.Database.EntityConfigurations.IDatabaseConstants.Guid
  - Mix.Database.EntityConfigurations.IDatabaseConstants.Integer
  - Mix.Database.EntityConfigurations.IDatabaseConstants.MaxLength
  - Mix.Database.EntityConfigurations.IDatabaseConstants.MediumLength
  - Mix.Database.EntityConfigurations.IDatabaseConstants.NString
  - Mix.Database.EntityConfigurations.IDatabaseConstants.SmallLength
  - Mix.Database.EntityConfigurations.IDatabaseConstants.String
  - Mix.Database.EntityConfigurations.IDatabaseConstants.Text
  langs:
  - csharp
  - vb
  name: IDatabaseConstants
  nameWithType: IDatabaseConstants
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants
  type: Interface
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: IDatabaseConstants
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 2
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: public interface IDatabaseConstants
    content.vb: Public Interface IDatabaseConstants
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.DatabaseCollation
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.DatabaseCollation
  id: DatabaseCollation
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: DatabaseCollation
  nameWithType: IDatabaseConstants.DatabaseCollation
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.DatabaseCollation
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: DatabaseCollation
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 4
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string DatabaseCollation { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property DatabaseCollation As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.DatabaseCollation*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.CharSet
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.CharSet
  id: CharSet
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: CharSet
  nameWithType: IDatabaseConstants.CharSet
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.CharSet
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: CharSet
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 5
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string CharSet { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property CharSet As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.CharSet*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.SmallLength
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.SmallLength
  id: SmallLength
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: SmallLength
  nameWithType: IDatabaseConstants.SmallLength
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.SmallLength
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: SmallLength
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 6
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string SmallLength { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property SmallLength As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.SmallLength*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.MediumLength
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.MediumLength
  id: MediumLength
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: MediumLength
  nameWithType: IDatabaseConstants.MediumLength
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.MediumLength
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MediumLength
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 7
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string MediumLength { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property MediumLength As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.MediumLength*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.MaxLength
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.MaxLength
  id: MaxLength
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: MaxLength
  nameWithType: IDatabaseConstants.MaxLength
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.MaxLength
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MaxLength
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 8
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string MaxLength { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property MaxLength As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.MaxLength*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.DateTime
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.DateTime
  id: DateTime
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: DateTime
  nameWithType: IDatabaseConstants.DateTime
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.DateTime
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: DateTime
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 9
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string DateTime { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property DateTime As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.DateTime*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.Guid
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.Guid
  id: Guid
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: Guid
  nameWithType: IDatabaseConstants.Guid
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.Guid
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Guid
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 10
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string Guid { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Guid As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.Guid*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.Integer
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.Integer
  id: Integer
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: Integer
  nameWithType: IDatabaseConstants.Integer
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.Integer
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Integer
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 11
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string Integer { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Integer As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.Integer*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.String
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.String
  id: String
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: String
  nameWithType: IDatabaseConstants.String
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.String
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: String
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 12
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string String { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property String As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.String*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.NString
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.NString
  id: NString
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: NString
  nameWithType: IDatabaseConstants.NString
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.NString
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: NString
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 13
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string NString { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property NString As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.NString*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.Text
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.Text
  id: Text
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: Text
  nameWithType: IDatabaseConstants.Text
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.Text
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Text
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 14
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string Text { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Text As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.Text*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.GenerateUUID
  commentId: P:Mix.Database.EntityConfigurations.IDatabaseConstants.GenerateUUID
  id: GenerateUUID
  parent: Mix.Database.EntityConfigurations.IDatabaseConstants
  langs:
  - csharp
  - vb
  name: GenerateUUID
  nameWithType: IDatabaseConstants.GenerateUUID
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.GenerateUUID
  type: Property
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: GenerateUUID
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/IDatabaseConstants.cs
    startLine: 15
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations
  syntax:
    content: string GenerateUUID { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property GenerateUUID As String
  overload: Mix.Database.EntityConfigurations.IDatabaseConstants.GenerateUUID*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Mix.Database.EntityConfigurations
  commentId: N:Mix.Database.EntityConfigurations
  name: Mix.Database.EntityConfigurations
  nameWithType: Mix.Database.EntityConfigurations
  fullName: Mix.Database.EntityConfigurations
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.DatabaseCollation*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.DatabaseCollation
  name: DatabaseCollation
  nameWithType: IDatabaseConstants.DatabaseCollation
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.DatabaseCollation
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.CharSet*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.CharSet
  name: CharSet
  nameWithType: IDatabaseConstants.CharSet
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.CharSet
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.SmallLength*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.SmallLength
  name: SmallLength
  nameWithType: IDatabaseConstants.SmallLength
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.SmallLength
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.MediumLength*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.MediumLength
  name: MediumLength
  nameWithType: IDatabaseConstants.MediumLength
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.MediumLength
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.MaxLength*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.MaxLength
  name: MaxLength
  nameWithType: IDatabaseConstants.MaxLength
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.MaxLength
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.DateTime*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.DateTime
  name: DateTime
  nameWithType: IDatabaseConstants.DateTime
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.DateTime
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.Guid*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.Guid
  name: Guid
  nameWithType: IDatabaseConstants.Guid
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.Guid
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.Integer*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.Integer
  name: Integer
  nameWithType: IDatabaseConstants.Integer
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.Integer
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.String*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.String
  name: String
  nameWithType: IDatabaseConstants.String
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.String
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.NString*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.NString
  name: NString
  nameWithType: IDatabaseConstants.NString
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.NString
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.Text*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.Text
  name: Text
  nameWithType: IDatabaseConstants.Text
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.Text
- uid: Mix.Database.EntityConfigurations.IDatabaseConstants.GenerateUUID*
  commentId: Overload:Mix.Database.EntityConfigurations.IDatabaseConstants.GenerateUUID
  name: GenerateUUID
  nameWithType: IDatabaseConstants.GenerateUUID
  fullName: Mix.Database.EntityConfigurations.IDatabaseConstants.GenerateUUID
