### YamlMime:ManagedReference
items:
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL
  commentId: N:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL
  id: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL
  children:
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeFieldConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetReferenceConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetValueConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeValueConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCacheConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCmsUserConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixConfigurationConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCultureConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixFileConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixLanguageConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixMediaConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModuleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModuleDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModulePostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPageConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPageModuleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPagePostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageNavigationConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageRoleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostMediaConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostModuleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedAttributeDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedAttributeSetConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedPostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixTemplateConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixThemeConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixUrlAliasConfiguration
  langs:
  - csharp
  - vb
  name: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL
  nameWithType: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL
  type: Namespace
  assemblies:
  - Mix.Cms.Lib
references:
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeFieldConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeFieldConfiguration
  name: MixAttributeFieldConfiguration
  nameWithType: MixAttributeFieldConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeFieldConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetConfiguration
  name: MixAttributeSetConfiguration
  nameWithType: MixAttributeSetConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetDataConfiguration
  name: MixAttributeSetDataConfiguration
  nameWithType: MixAttributeSetDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetReferenceConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetReferenceConfiguration
  name: MixAttributeSetReferenceConfiguration
  nameWithType: MixAttributeSetReferenceConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetReferenceConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetValueConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetValueConfiguration
  name: MixAttributeSetValueConfiguration
  nameWithType: MixAttributeSetValueConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeSetValueConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeValueConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeValueConfiguration
  name: MixAttributeValueConfiguration
  nameWithType: MixAttributeValueConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixAttributeValueConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCacheConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCacheConfiguration
  name: MixCacheConfiguration
  nameWithType: MixCacheConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCacheConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCmsUserConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCmsUserConfiguration
  name: MixCmsUserConfiguration
  nameWithType: MixCmsUserConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCmsUserConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixConfigurationConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixConfigurationConfiguration
  name: MixConfigurationConfiguration
  nameWithType: MixConfigurationConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixConfigurationConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCultureConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCultureConfiguration
  name: MixCultureConfiguration
  nameWithType: MixCultureConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixCultureConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixFileConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixFileConfiguration
  name: MixFileConfiguration
  nameWithType: MixFileConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixFileConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixLanguageConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixLanguageConfiguration
  name: MixLanguageConfiguration
  nameWithType: MixLanguageConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixLanguageConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixMediaConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixMediaConfiguration
  name: MixMediaConfiguration
  nameWithType: MixMediaConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixMediaConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModuleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModuleConfiguration
  name: MixModuleConfiguration
  nameWithType: MixModuleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModuleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModuleDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModuleDataConfiguration
  name: MixModuleDataConfiguration
  nameWithType: MixModuleDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModuleDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModulePostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModulePostConfiguration
  name: MixModulePostConfiguration
  nameWithType: MixModulePostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixModulePostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPageConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPageConfiguration
  name: MixPageConfiguration
  nameWithType: MixPageConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPageConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPageModuleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPageModuleConfiguration
  name: MixPageModuleConfiguration
  nameWithType: MixPageModuleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPageModuleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPagePostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPagePostConfiguration
  name: MixPagePostConfiguration
  nameWithType: MixPagePostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPagePostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageConfiguration
  name: MixPortalPageConfiguration
  nameWithType: MixPortalPageConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageNavigationConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageNavigationConfiguration
  name: MixPortalPageNavigationConfiguration
  nameWithType: MixPortalPageNavigationConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageNavigationConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageRoleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageRoleConfiguration
  name: MixPortalPageRoleConfiguration
  nameWithType: MixPortalPageRoleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPortalPageRoleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostConfiguration
  name: MixPostConfiguration
  nameWithType: MixPostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostMediaConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostMediaConfiguration
  name: MixPostMediaConfiguration
  nameWithType: MixPostMediaConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostMediaConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostModuleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostModuleConfiguration
  name: MixPostModuleConfiguration
  nameWithType: MixPostModuleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixPostModuleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedAttributeDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedAttributeDataConfiguration
  name: MixRelatedAttributeDataConfiguration
  nameWithType: MixRelatedAttributeDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedAttributeDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedAttributeSetConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedAttributeSetConfiguration
  name: MixRelatedAttributeSetConfiguration
  nameWithType: MixRelatedAttributeSetConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedAttributeSetConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedDataConfiguration
  name: MixRelatedDataConfiguration
  nameWithType: MixRelatedDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedPostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedPostConfiguration
  name: MixRelatedPostConfiguration
  nameWithType: MixRelatedPostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixRelatedPostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixTemplateConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixTemplateConfiguration
  name: MixTemplateConfiguration
  nameWithType: MixTemplateConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixTemplateConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixThemeConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixThemeConfiguration
  name: MixThemeConfiguration
  nameWithType: MixThemeConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixThemeConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixUrlAliasConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixUrlAliasConfiguration
  name: MixUrlAliasConfiguration
  nameWithType: MixUrlAliasConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.MSSQL.MixUrlAliasConfiguration
