### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Quartz
  commentId: N:Mix.Database.EntityConfigurations.SQLSERVER.Quartz
  id: Mix.Database.EntityConfigurations.SQLSERVER.Quartz
  children:
  - Mix.Database.EntityConfigurations.SQLSERVER.Quartz.SqlServerQuartzConfigurations
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.SQLSERVER.Quartz
  nameWithType: Mix.Database.EntityConfigurations.SQLSERVER.Quartz
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Quartz
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Quartz.SqlServerQuartzConfigurations
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.Quartz.SqlServerQuartzConfigurations
  name: SqlServerQuartzConfigurations
  nameWithType: SqlServerQuartzConfigurations
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Quartz.SqlServerQuartzConfigurations
