### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base
  commentId: N:Mix.Database.EntityConfigurations.SQLSERVER.Base
  id: Mix.Database.EntityConfigurations.SQLSERVER.Base
  children:
  - Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerAssociationBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualSEOContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualUniqueNameContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityUniqueNameBaseConfiguration`2
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.SQLSERVER.Base
  nameWithType: Mix.Database.EntityConfigurations.SQLSERVER.Base
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerAssociationBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerAssociationBaseConfiguration`2
  name: SqlServerAssociationBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqlServerAssociationBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerAssociationBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqlServerAssociationBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerAssociationBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqlServerAssociationBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerAssociationBaseConfiguration`2
    name: SqlServerAssociationBaseConfiguration
    nameWithType: SqlServerAssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerAssociationBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerAssociationBaseConfiguration`2
    name: SqlServerAssociationBaseConfiguration
    nameWithType: SqlServerAssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerAssociationBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration`2
  name: SqlServerEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqlServerEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqlServerEntityBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqlServerEntityBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration`2
    name: SqlServerEntityBaseConfiguration
    nameWithType: SqlServerEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration`2
    name: SqlServerEntityBaseConfiguration
    nameWithType: SqlServerEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration`2
  name: SqlServerMultilingualContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqlServerMultilingualContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqlServerMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqlServerMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration`2
    name: SqlServerMultilingualContentBaseConfiguration
    nameWithType: SqlServerMultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration`2
    name: SqlServerMultilingualContentBaseConfiguration
    nameWithType: SqlServerMultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualSEOContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualSEOContentBaseConfiguration`2
  name: SqlServerMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqlServerMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqlServerMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqlServerMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualSEOContentBaseConfiguration`2
    name: SqlServerMultilingualSEOContentBaseConfiguration
    nameWithType: SqlServerMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualSEOContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualSEOContentBaseConfiguration`2
    name: SqlServerMultilingualSEOContentBaseConfiguration
    nameWithType: SqlServerMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualSEOContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualUniqueNameContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualUniqueNameContentBaseConfiguration`2
  name: SqlServerMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqlServerMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqlServerMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqlServerMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualUniqueNameContentBaseConfiguration`2
    name: SqlServerMultilingualUniqueNameContentBaseConfiguration
    nameWithType: SqlServerMultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualUniqueNameContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualUniqueNameContentBaseConfiguration`2
    name: SqlServerMultilingualUniqueNameContentBaseConfiguration
    nameWithType: SqlServerMultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualUniqueNameContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityBaseConfiguration`2
  name: SqlServerTenantEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqlServerTenantEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqlServerTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqlServerTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityBaseConfiguration`2
    name: SqlServerTenantEntityBaseConfiguration
    nameWithType: SqlServerTenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityBaseConfiguration`2
    name: SqlServerTenantEntityBaseConfiguration
    nameWithType: SqlServerTenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityUniqueNameBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityUniqueNameBaseConfiguration`2
  name: SqlServerTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqlServerTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: SqlServerTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqlServerTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityUniqueNameBaseConfiguration`2
    name: SqlServerTenantEntityUniqueNameBaseConfiguration
    nameWithType: SqlServerTenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityUniqueNameBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityUniqueNameBaseConfiguration`2
    name: SqlServerTenantEntityUniqueNameBaseConfiguration
    nameWithType: SqlServerTenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerTenantEntityUniqueNameBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
