### YamlMime:ManagedReference
items:
- uid: Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES
  commentId: N:Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES
  id: Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES
  children:
  - Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES.MixCacheConfiguration
  langs:
  - csharp
  - vb
  name: Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES
  nameWithType: Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES
  fullName: Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES
  type: Namespace
  assemblies:
  - mix.heart
references:
- uid: Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES.MixCacheConfiguration
  commentId: T:Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES.MixCacheConfiguration
  name: MixCacheConfiguration
  nameWithType: MixCacheConfiguration
  fullName: Mix.Heart.Infrastructure.EntityConfigurations.POSTGRES.MixCacheConfiguration
