### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.Base
  commentId: N:Mix.Database.EntityConfigurations.Base
  id: Mix.Database.EntityConfigurations.Base
  children:
  - Mix.Database.EntityConfigurations.Base.AssociationBaseConfiguration`3
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  - Mix.Database.EntityConfigurations.Base.ExtraColumnMultilingualSEOContentBaseConfiguration`3
  - Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3
  - Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration`3
  - Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration`3
  - Mix.Database.EntityConfigurations.Base.TenantEntityBaseConfiguration`3
  - Mix.Database.EntityConfigurations.Base.TenantEntityUniqueNameBaseConfiguration`3
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.Base
  nameWithType: Mix.Database.EntityConfigurations.Base
  fullName: Mix.Database.EntityConfigurations.Base
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.Base.AssociationBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.AssociationBaseConfiguration`3
  name: AssociationBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: AssociationBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.AssociationBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: AssociationBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.AssociationBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: AssociationBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.AssociationBaseConfiguration`3
    name: AssociationBaseConfiguration
    nameWithType: AssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.AssociationBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.AssociationBaseConfiguration`3
    name: AssociationBaseConfiguration
    nameWithType: AssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.AssociationBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  name: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.ExtraColumnMultilingualSEOContentBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.ExtraColumnMultilingualSEOContentBaseConfiguration`3
  name: ExtraColumnMultilingualSEOContentBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: ExtraColumnMultilingualSEOContentBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.ExtraColumnMultilingualSEOContentBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: ExtraColumnMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.ExtraColumnMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: ExtraColumnMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.ExtraColumnMultilingualSEOContentBaseConfiguration`3
    name: ExtraColumnMultilingualSEOContentBaseConfiguration
    nameWithType: ExtraColumnMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.ExtraColumnMultilingualSEOContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.ExtraColumnMultilingualSEOContentBaseConfiguration`3
    name: ExtraColumnMultilingualSEOContentBaseConfiguration
    nameWithType: ExtraColumnMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.ExtraColumnMultilingualSEOContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3
  name: MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3
    name: MultilingualContentBaseConfiguration
    nameWithType: MultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3
    name: MultilingualContentBaseConfiguration
    nameWithType: MultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration`3
  name: MultilingualSEOContentBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: MultilingualSEOContentBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: MultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: MultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration`3
    name: MultilingualSEOContentBaseConfiguration
    nameWithType: MultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration`3
    name: MultilingualSEOContentBaseConfiguration
    nameWithType: MultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration`3
  name: MultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: MultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: MultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: MultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration`3
    name: MultilingualUniqueNameContentBaseConfiguration
    nameWithType: MultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration`3
    name: MultilingualUniqueNameContentBaseConfiguration
    nameWithType: MultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.TenantEntityBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.TenantEntityBaseConfiguration`3
  name: TenantEntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: TenantEntityBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.TenantEntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: TenantEntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.TenantEntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: TenantEntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.TenantEntityBaseConfiguration`3
    name: TenantEntityBaseConfiguration
    nameWithType: TenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.TenantEntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.TenantEntityBaseConfiguration`3
    name: TenantEntityBaseConfiguration
    nameWithType: TenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.TenantEntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.TenantEntityUniqueNameBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.TenantEntityUniqueNameBaseConfiguration`3
  name: TenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: TenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.TenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: TenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.TenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: TenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.TenantEntityUniqueNameBaseConfiguration`3
    name: TenantEntityUniqueNameBaseConfiguration
    nameWithType: TenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.TenantEntityUniqueNameBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.TenantEntityUniqueNameBaseConfiguration`3
    name: TenantEntityUniqueNameBaseConfiguration
    nameWithType: TenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.TenantEntityUniqueNameBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
