### YamlMime:ManagedReference
items:
- uid: Mix.Cms.Lib.ViewModels.MixConfigurations
  commentId: N:Mix.Cms.Lib.ViewModels.MixConfigurations
  id: Mix.Cms.Lib.ViewModels.MixConfigurations
  children:
  - Mix.Cms.Lib.ViewModels.MixConfigurations.DeleteViewModel
  - Mix.Cms.Lib.ViewModels.MixConfigurations.ImportViewModel
  - Mix.Cms.Lib.ViewModels.MixConfigurations.ReadMvcViewModel
  - Mix.Cms.Lib.ViewModels.MixConfigurations.ReadViewModel
  - Mix.Cms.Lib.ViewModels.MixConfigurations.SystemConfigurationViewModel
  - Mix.Cms.Lib.ViewModels.MixConfigurations.UpdateViewModel
  langs:
  - csharp
  - vb
  name: Mix.Cms.Lib.ViewModels.MixConfigurations
  nameWithType: Mix.Cms.Lib.ViewModels.MixConfigurations
  fullName: Mix.Cms.Lib.ViewModels.MixConfigurations
  type: Namespace
  assemblies:
  - Mix.Cms.Lib
references:
- uid: Mix.Cms.Lib.ViewModels.MixConfigurations.DeleteViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixConfigurations.DeleteViewModel
  name: DeleteViewModel
  nameWithType: DeleteViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixConfigurations.DeleteViewModel
- uid: Mix.Cms.Lib.ViewModels.MixConfigurations.UpdateViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixConfigurations.UpdateViewModel
  parent: Mix.Cms.Lib.ViewModels.MixConfigurations
  name: UpdateViewModel
  nameWithType: UpdateViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixConfigurations.UpdateViewModel
- uid: Mix.Cms.Lib.ViewModels.MixConfigurations.ReadMvcViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixConfigurations.ReadMvcViewModel
  name: ReadMvcViewModel
  nameWithType: ReadMvcViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixConfigurations.ReadMvcViewModel
- uid: Mix.Cms.Lib.ViewModels.MixConfigurations.ReadViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixConfigurations.ReadViewModel
  name: ReadViewModel
  nameWithType: ReadViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixConfigurations.ReadViewModel
- uid: Mix.Cms.Lib.ViewModels.MixConfigurations.SystemConfigurationViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixConfigurations.SystemConfigurationViewModel
  name: SystemConfigurationViewModel
  nameWithType: SystemConfigurationViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixConfigurations.SystemConfigurationViewModel
- uid: Mix.Cms.Lib.ViewModels.MixConfigurations.ImportViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.MixConfigurations.ImportViewModel
  name: ImportViewModel
  nameWithType: ImportViewModel
  fullName: Mix.Cms.Lib.ViewModels.MixConfigurations.ImportViewModel
- uid: Mix.Cms.Lib.ViewModels.MixConfigurations
  commentId: N:Mix.Cms.Lib.ViewModels.MixConfigurations
  name: Mix.Cms.Lib.ViewModels.MixConfigurations
  nameWithType: Mix.Cms.Lib.ViewModels.MixConfigurations
  fullName: Mix.Cms.Lib.ViewModels.MixConfigurations
