### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.MYSQL.Quartz
  commentId: N:Mix.Database.EntityConfigurations.MYSQL.Quartz
  id: Mix.Database.EntityConfigurations.MYSQL.Quartz
  children:
  - Mix.Database.EntityConfigurations.MYSQL.Quartz.MySqlQuartzConfigurations
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.MYSQL.Quartz
  nameWithType: Mix.Database.EntityConfigurations.MYSQL.Quartz
  fullName: Mix.Database.EntityConfigurations.MYSQL.Quartz
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.MYSQL.Quartz.MySqlQuartzConfigurations
  commentId: T:Mix.Database.EntityConfigurations.MYSQL.Quartz.MySqlQuartzConfigurations
  name: MySqlQuartzConfigurations
  nameWithType: MySqlQuartzConfigurations
  fullName: Mix.Database.EntityConfigurations.MYSQL.Quartz.MySqlQuartzConfigurations
