### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration`2
  id: SqliteEntityBaseConfiguration`2
  parent: Mix.Database.EntityConfigurations.SQLITE.Base
  children: []
  langs:
  - csharp
  - vb
  name: SqliteEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqliteEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration<T, TPrimaryKey>
  type: Class
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/SQLITE/Base/SqliteEntityBaseConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: SqliteEntityBaseConfiguration
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/SQLITE/Base/SqliteEntityBaseConfiguration.cs
    startLine: 4
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations.SQLITE.Base
  syntax:
    content: 'public abstract class SqliteEntityBaseConfiguration<T, TPrimaryKey> : EntityBaseConfiguration<T, TPrimaryKey, SqliteDatabaseConstants> where T : EntityBase<TPrimaryKey> where TPrimaryKey : IComparable'
    typeParameters:
    - id: T
    - id: TPrimaryKey
    content.vb: >-
      Public MustInherit Class SqliteEntityBaseConfiguration(Of T As EntityBase(Of TPrimaryKey), TPrimaryKey As IComparable)
          Inherits EntityBaseConfiguration(Of T, TPrimaryKey, SqliteDatabaseConstants)
  inheritance:
  - System.Object
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}
  derivedClasses:
  - Mix.Database.EntityConfigurations.SQLITE.MixContributorConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDatabaseColumnConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDataConentAssociationConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDataConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDataContentValueConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixDiscussionConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixPostConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixTenantConfiguration
  - Mix.Database.EntityConfigurations.SQLITE.MixViewTemplateContentConfiguration
  inheritedMembers:
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}.Config
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}.Configure(EntityTypeBuilder{{T}})
  nameWithType.vb: SqliteEntityBaseConfiguration(Of T, TPrimaryKey)
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
  fullName.vb: Mix.Database.EntityConfigurations.SQLITE.Base.SqliteEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqliteEntityBaseConfiguration(Of T, TPrimaryKey)
references:
- uid: Mix.Database.EntityConfigurations.SQLITE.Base
  commentId: N:Mix.Database.EntityConfigurations.SQLITE.Base
  name: Mix.Database.EntityConfigurations.SQLITE.Base
  nameWithType: Mix.Database.EntityConfigurations.SQLITE.Base
  fullName: Mix.Database.EntityConfigurations.SQLITE.Base
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}
  commentId: T:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}
  parent: Mix.Database.EntityConfigurations.Base
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  name: EntityBaseConfiguration<T, TPrimaryKey, SqliteDatabaseConstants>
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, SqliteDatabaseConstants>
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants>
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, SqliteDatabaseConstants)
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants)
  name.vb: EntityBaseConfiguration(Of T, TPrimaryKey, SqliteDatabaseConstants)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants
    name: SqliteDatabaseConstants
    nameWithType: SqliteDatabaseConstants
    fullName: Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants
    name: SqliteDatabaseConstants
    nameWithType: SqliteDatabaseConstants
    fullName: Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}.Config
  commentId: P:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}.Config
  parent: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  name: Config
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, SqliteDatabaseConstants>.Config
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants>.Config
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, SqliteDatabaseConstants).Config
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants).Config
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}.Configure(EntityTypeBuilder{{T}})
  commentId: M:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}.Configure(EntityTypeBuilder{`0})
  parent: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants}
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  name: Configure(EntityTypeBuilder<T>)
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, SqliteDatabaseConstants>.Configure(EntityTypeBuilder<T>)
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants>.Configure(EntityTypeBuilder<T>)
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, SqliteDatabaseConstants).Configure(EntityTypeBuilder(Of T))
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants).Configure(EntityTypeBuilder(Of T))
  name.vb: Configure(EntityTypeBuilder(Of T))
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration<T, TPrimaryKey, SqliteDatabaseConstants>.Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants>.Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration(Of T, TPrimaryKey, SqliteDatabaseConstants).Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLITE.SqliteDatabaseConstants).Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  name: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base
  commentId: N:Mix.Database.EntityConfigurations.Base
  name: Mix.Database.EntityConfigurations.Base
  nameWithType: Mix.Database.EntityConfigurations.Base
  fullName: Mix.Database.EntityConfigurations.Base
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  commentId: P:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  name: Config
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  commentId: M:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  isExternal: true
  name: Configure(EntityTypeBuilder<T>)
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  name.vb: Configure(EntityTypeBuilder(Of T))
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
