### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3
  id: MultilingualContentBaseConfiguration`3
  parent: Mix.Database.EntityConfigurations.Base
  children:
  - Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  langs:
  - csharp
  - vb
  name: MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>
  type: Class
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/MultilingualContentBaseConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MultilingualContentBaseConfiguration
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/MultilingualContentBaseConfiguration.cs
    startLine: 4
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations.Base
  syntax:
    content: 'public abstract class MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig> : EntityBaseConfiguration<T, TPrimaryKey, TConfig> where T : MultilingualContentBase<TPrimaryKey> where TPrimaryKey : IComparable where TConfig : IDatabaseConstants'
    typeParameters:
    - id: T
    - id: TPrimaryKey
    - id: TConfig
    content.vb: >-
      Public MustInherit Class MultilingualContentBaseConfiguration(Of T As MultilingualContentBase(Of TPrimaryKey), TPrimaryKey As IComparable, TConfig As IDatabaseConstants)
          Inherits EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  inheritance:
  - System.Object
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},{TConfig}}
  derivedClasses:
  - Mix.Database.EntityConfigurations.Base.MultilingualSEOContentBaseConfiguration`3
  - Mix.Database.EntityConfigurations.Base.MultilingualUniqueNameContentBaseConfiguration`3
  - Mix.Database.EntityConfigurations.MYSQL.Base.MySqlMultilingualContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLITE.Base.SqliteMultilingualContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerMultilingualContentBaseConfiguration`2
  inheritedMembers:
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},{TConfig}}.Config
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},{TConfig}}.Configure(EntityTypeBuilder{{T}})
  nameWithType.vb: MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
  fullName.vb: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig)
- uid: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  commentId: M:Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  id: Configure(EntityTypeBuilder{`0})
  parent: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3
  langs:
  - csharp
  - vb
  name: Configure(EntityTypeBuilder<T>)
  nameWithType: MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  fullName: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  type: Method
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/Base/MultilingualContentBaseConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Configure
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/Base/MultilingualContentBaseConfiguration.cs
    startLine: 9
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations.Base
  syntax:
    content: public override void Configure(EntityTypeBuilder<T> builder)
    parameters:
    - id: builder
      type: EntityTypeBuilder{{T}}
    content.vb: Public Overrides Sub Configure(builder As EntityTypeBuilder(Of T))
  overridden: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},{TConfig}}.Configure(EntityTypeBuilder{{T}})
  overload: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3.Configure*
  nameWithType.vb: MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
  fullName.vb: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  name.vb: Configure(EntityTypeBuilder(Of T))
references:
- uid: Mix.Database.EntityConfigurations.Base
  commentId: N:Mix.Database.EntityConfigurations.Base
  name: Mix.Database.EntityConfigurations.Base
  nameWithType: Mix.Database.EntityConfigurations.Base
  fullName: Mix.Database.EntityConfigurations.Base
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},{TConfig}}
  commentId: T:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,`2}
  parent: Mix.Database.EntityConfigurations.Base
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  name: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},{TConfig}}.Config
  commentId: P:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,`2}.Config
  parent: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},{TConfig}}
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  name: Config
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},{TConfig}}.Configure(EntityTypeBuilder{{T}})
  commentId: M:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,`2}.Configure(EntityTypeBuilder{`0})
  parent: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},{TConfig}}
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  name: Configure(EntityTypeBuilder<T>)
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  name.vb: Configure(EntityTypeBuilder(Of T))
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  name: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  commentId: P:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  name: Config
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  commentId: M:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  isExternal: true
  name: Configure(EntityTypeBuilder<T>)
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  name.vb: Configure(EntityTypeBuilder(Of T))
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3.Configure*
  commentId: Overload:Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration`3.Configure
  name: Configure
  nameWithType: MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
  fullName: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
  nameWithType.vb: MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
  fullName.vb: Mix.Database.EntityConfigurations.Base.MultilingualContentBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
- uid: EntityTypeBuilder{{T}}
  commentId: '!:EntityTypeBuilder{`0}'
  definition: EntityTypeBuilder`1
  name: EntityTypeBuilder<T>
  nameWithType: EntityTypeBuilder<T>
  fullName: EntityTypeBuilder<T>
  nameWithType.vb: EntityTypeBuilder(Of T)
  fullName.vb: EntityTypeBuilder(Of T)
  name.vb: EntityTypeBuilder(Of T)
  spec.csharp:
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: EntityTypeBuilder`1
  isExternal: true
  name: EntityTypeBuilder<>
  nameWithType: EntityTypeBuilder<>
  fullName: EntityTypeBuilder<>
  nameWithType.vb: EntityTypeBuilder(Of )
  fullName.vb: EntityTypeBuilder(Of )
  name.vb: EntityTypeBuilder(Of )
  spec.csharp:
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
