### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.POSTGRES.Quartz
  commentId: N:Mix.Database.EntityConfigurations.POSTGRES.Quartz
  id: Mix.Database.EntityConfigurations.POSTGRES.Quartz
  children:
  - Mix.Database.EntityConfigurations.POSTGRES.Quartz.PostgresSqlQuartzConfigurations
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.POSTGRES.Quartz
  nameWithType: Mix.Database.EntityConfigurations.POSTGRES.Quartz
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Quartz
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.POSTGRES.Quartz.PostgresSqlQuartzConfigurations
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.Quartz.PostgresSqlQuartzConfigurations
  name: PostgresSqlQuartzConfigurations
  nameWithType: PostgresSqlQuartzConfigurations
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Quartz.PostgresSqlQuartzConfigurations
