### YamlMime:ManagedReference
items:
- uid: Mix.Shared.Models.DatabaseConfigurations
  commentId: T:Mix.Shared.Models.DatabaseConfigurations
  id: DatabaseConfigurations
  parent: Mix.Shared.Models
  children:
  - Mix.Shared.Models.DatabaseConfigurations.ClearDbPool
  - Mix.Shared.Models.DatabaseConfigurations.ConnectionStrings
  - Mix.Shared.Models.DatabaseConfigurations.DatabaseProvider
  langs:
  - csharp
  - vb
  name: DatabaseConfigurations
  nameWithType: DatabaseConfigurations
  fullName: Mix.Shared.Models.DatabaseConfigurations
  type: Class
  source:
    remote:
      path: src/platform/mix.shared/Models/DatabaseConfigurations.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: DatabaseConfigurations
    path: ../../mix.core/src/platform/mix.shared/Models/DatabaseConfigurations.cs
    startLine: 4
  assemblies:
  - mix.shared
  namespace: Mix.Shared.Models
  syntax:
    content: public class DatabaseConfigurations
    content.vb: Public Class DatabaseConfigurations
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Shared.Models.DatabaseConfigurations.ConnectionStrings
  commentId: P:Mix.Shared.Models.DatabaseConfigurations.ConnectionStrings
  id: ConnectionStrings
  parent: Mix.Shared.Models.DatabaseConfigurations
  langs:
  - csharp
  - vb
  name: ConnectionStrings
  nameWithType: DatabaseConfigurations.ConnectionStrings
  fullName: Mix.Shared.Models.DatabaseConfigurations.ConnectionStrings
  type: Property
  source:
    remote:
      path: src/platform/mix.shared/Models/DatabaseConfigurations.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: ConnectionStrings
    path: ../../mix.core/src/platform/mix.shared/Models/DatabaseConfigurations.cs
    startLine: 6
  assemblies:
  - mix.shared
  namespace: Mix.Shared.Models
  syntax:
    content: public ConnectionStrings ConnectionStrings { get; set; }
    parameters: []
    return:
      type: Mix.Shared.Models.ConnectionStrings
    content.vb: Public Property ConnectionStrings As ConnectionStrings
  overload: Mix.Shared.Models.DatabaseConfigurations.ConnectionStrings*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Shared.Models.DatabaseConfigurations.ClearDbPool
  commentId: P:Mix.Shared.Models.DatabaseConfigurations.ClearDbPool
  id: ClearDbPool
  parent: Mix.Shared.Models.DatabaseConfigurations
  langs:
  - csharp
  - vb
  name: ClearDbPool
  nameWithType: DatabaseConfigurations.ClearDbPool
  fullName: Mix.Shared.Models.DatabaseConfigurations.ClearDbPool
  type: Property
  source:
    remote:
      path: src/platform/mix.shared/Models/DatabaseConfigurations.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: ClearDbPool
    path: ../../mix.core/src/platform/mix.shared/Models/DatabaseConfigurations.cs
    startLine: 7
  assemblies:
  - mix.shared
  namespace: Mix.Shared.Models
  syntax:
    content: public bool ClearDbPool { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ClearDbPool As Boolean
  overload: Mix.Shared.Models.DatabaseConfigurations.ClearDbPool*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Shared.Models.DatabaseConfigurations.DatabaseProvider
  commentId: P:Mix.Shared.Models.DatabaseConfigurations.DatabaseProvider
  id: DatabaseProvider
  parent: Mix.Shared.Models.DatabaseConfigurations
  langs:
  - csharp
  - vb
  name: DatabaseProvider
  nameWithType: DatabaseConfigurations.DatabaseProvider
  fullName: Mix.Shared.Models.DatabaseConfigurations.DatabaseProvider
  type: Property
  source:
    remote:
      path: src/platform/mix.shared/Models/DatabaseConfigurations.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: DatabaseProvider
    path: ../../mix.core/src/platform/mix.shared/Models/DatabaseConfigurations.cs
    startLine: 8
  assemblies:
  - mix.shared
  namespace: Mix.Shared.Models
  syntax:
    content: public MixDatabaseProvider DatabaseProvider { get; set; }
    parameters: []
    return:
      type: Mix.Heart.Enums.MixDatabaseProvider
    content.vb: Public Property DatabaseProvider As MixDatabaseProvider
  overload: Mix.Shared.Models.DatabaseConfigurations.DatabaseProvider*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Mix.Shared.Models
  commentId: N:Mix.Shared.Models
  name: Mix.Shared.Models
  nameWithType: Mix.Shared.Models
  fullName: Mix.Shared.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Shared.Models.DatabaseConfigurations.ConnectionStrings*
  commentId: Overload:Mix.Shared.Models.DatabaseConfigurations.ConnectionStrings
  name: ConnectionStrings
  nameWithType: DatabaseConfigurations.ConnectionStrings
  fullName: Mix.Shared.Models.DatabaseConfigurations.ConnectionStrings
- uid: Mix.Shared.Models.ConnectionStrings
  commentId: T:Mix.Shared.Models.ConnectionStrings
  parent: Mix.Shared.Models
  name: ConnectionStrings
  nameWithType: ConnectionStrings
  fullName: Mix.Shared.Models.ConnectionStrings
- uid: Mix.Shared.Models.DatabaseConfigurations.ClearDbPool*
  commentId: Overload:Mix.Shared.Models.DatabaseConfigurations.ClearDbPool
  name: ClearDbPool
  nameWithType: DatabaseConfigurations.ClearDbPool
  fullName: Mix.Shared.Models.DatabaseConfigurations.ClearDbPool
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Mix.Shared.Models.DatabaseConfigurations.DatabaseProvider*
  commentId: Overload:Mix.Shared.Models.DatabaseConfigurations.DatabaseProvider
  name: DatabaseProvider
  nameWithType: DatabaseConfigurations.DatabaseProvider
  fullName: Mix.Shared.Models.DatabaseConfigurations.DatabaseProvider
- uid: Mix.Heart.Enums.MixDatabaseProvider
  commentId: T:Mix.Heart.Enums.MixDatabaseProvider
  parent: Mix.Heart.Enums
  name: MixDatabaseProvider
  nameWithType: MixDatabaseProvider
  fullName: Mix.Heart.Enums.MixDatabaseProvider
- uid: Mix.Heart.Enums
  commentId: N:Mix.Heart.Enums
  name: Mix.Heart.Enums
  nameWithType: Mix.Heart.Enums
  fullName: Mix.Heart.Enums
