### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.POSTGRES.Base
  commentId: N:Mix.Database.EntityConfigurations.POSTGRES.Base
  id: Mix.Database.EntityConfigurations.POSTGRES.Base
  children:
  - Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresAssociationBaseConfiguration`2
  - Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresEntityBaseConfiguration`2
  - Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualSEOContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualUniqueNameContentBaseConfiguration`2
  - Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityBaseConfiguration`2
  - Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityUniqueNameBaseConfiguration`2
  langs:
  - csharp
  - vb
  name: Mix.Database.EntityConfigurations.POSTGRES.Base
  nameWithType: Mix.Database.EntityConfigurations.POSTGRES.Base
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Base
  type: Namespace
  assemblies:
  - mix.database
references:
- uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresAssociationBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresAssociationBaseConfiguration`2
  name: PostgresAssociationBaseConfiguration<T, TPrimaryKey>
  nameWithType: PostgresAssociationBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresAssociationBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: PostgresAssociationBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresAssociationBaseConfiguration(Of T, TPrimaryKey)
  name.vb: PostgresAssociationBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresAssociationBaseConfiguration`2
    name: PostgresAssociationBaseConfiguration
    nameWithType: PostgresAssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresAssociationBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresAssociationBaseConfiguration`2
    name: PostgresAssociationBaseConfiguration
    nameWithType: PostgresAssociationBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresAssociationBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresEntityBaseConfiguration`2
  name: PostgresEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: PostgresEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: PostgresEntityBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: PostgresEntityBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresEntityBaseConfiguration`2
    name: PostgresEntityBaseConfiguration
    nameWithType: PostgresEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresEntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresEntityBaseConfiguration`2
    name: PostgresEntityBaseConfiguration
    nameWithType: PostgresEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresEntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration`2
  name: PostgresMultilingualContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: PostgresMultilingualContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: PostgresMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: PostgresMultilingualContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration`2
    name: PostgresMultilingualContentBaseConfiguration
    nameWithType: PostgresMultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration`2
    name: PostgresMultilingualContentBaseConfiguration
    nameWithType: PostgresMultilingualContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualSEOContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualSEOContentBaseConfiguration`2
  name: PostgresMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: PostgresMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualSEOContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: PostgresMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: PostgresMultilingualSEOContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualSEOContentBaseConfiguration`2
    name: PostgresMultilingualSEOContentBaseConfiguration
    nameWithType: PostgresMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualSEOContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualSEOContentBaseConfiguration`2
    name: PostgresMultilingualSEOContentBaseConfiguration
    nameWithType: PostgresMultilingualSEOContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualSEOContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualUniqueNameContentBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualUniqueNameContentBaseConfiguration`2
  name: PostgresMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  nameWithType: PostgresMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualUniqueNameContentBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: PostgresMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  name.vb: PostgresMultilingualUniqueNameContentBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualUniqueNameContentBaseConfiguration`2
    name: PostgresMultilingualUniqueNameContentBaseConfiguration
    nameWithType: PostgresMultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualUniqueNameContentBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualUniqueNameContentBaseConfiguration`2
    name: PostgresMultilingualUniqueNameContentBaseConfiguration
    nameWithType: PostgresMultilingualUniqueNameContentBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresMultilingualUniqueNameContentBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityBaseConfiguration`2
  name: PostgresTenantEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: PostgresTenantEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: PostgresTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: PostgresTenantEntityBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityBaseConfiguration`2
    name: PostgresTenantEntityBaseConfiguration
    nameWithType: PostgresTenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityBaseConfiguration`2
    name: PostgresTenantEntityBaseConfiguration
    nameWithType: PostgresTenantEntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityUniqueNameBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityUniqueNameBaseConfiguration`2
  name: PostgresTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  nameWithType: PostgresTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityUniqueNameBaseConfiguration<T, TPrimaryKey>
  nameWithType.vb: PostgresTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  fullName.vb: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  name.vb: PostgresTenantEntityUniqueNameBaseConfiguration(Of T, TPrimaryKey)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityUniqueNameBaseConfiguration`2
    name: PostgresTenantEntityUniqueNameBaseConfiguration
    nameWithType: PostgresTenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityUniqueNameBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityUniqueNameBaseConfiguration`2
    name: PostgresTenantEntityUniqueNameBaseConfiguration
    nameWithType: PostgresTenantEntityUniqueNameBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.POSTGRES.Base.PostgresTenantEntityUniqueNameBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: )
    nameWithType: )
    fullName: )
