### YamlMime:ManagedReference
items:
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration`2
  commentId: T:Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration`2
  id: SqlServerEntityBaseConfiguration`2
  parent: Mix.Database.EntityConfigurations.SQLSERVER.Base
  children: []
  langs:
  - csharp
  - vb
  name: SqlServerEntityBaseConfiguration<T, TPrimaryKey>
  nameWithType: SqlServerEntityBaseConfiguration<T, TPrimaryKey>
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration<T, TPrimaryKey>
  type: Class
  source:
    remote:
      path: src/platform/mix.database/EntityConfigurations/SQLSERVER/Base/SqlServerEntityBaseConfiguration.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: SqlServerEntityBaseConfiguration
    path: ../../mix.core/src/platform/mix.database/EntityConfigurations/SQLSERVER/Base/SqlServerEntityBaseConfiguration.cs
    startLine: 4
  assemblies:
  - mix.database
  namespace: Mix.Database.EntityConfigurations.SQLSERVER.Base
  syntax:
    content: 'public abstract class SqlServerEntityBaseConfiguration<T, TPrimaryKey> : EntityBaseConfiguration<T, TPrimaryKey, SqlServerDatabaseConstants> where T : EntityBase<TPrimaryKey> where TPrimaryKey : IComparable'
    typeParameters:
    - id: T
    - id: TPrimaryKey
    content.vb: >-
      Public MustInherit Class SqlServerEntityBaseConfiguration(Of T As EntityBase(Of TPrimaryKey), TPrimaryKey As IComparable)
          Inherits EntityBaseConfiguration(Of T, TPrimaryKey, SqlServerDatabaseConstants)
  inheritance:
  - System.Object
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}
  derivedClasses:
  - Mix.Database.EntityConfigurations.SQLSERVER.MixContributorConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDatabaseColumnConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDataConentAssociationConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDataConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDataContentValueConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixDiscussionConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixPostConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixTenantConfiguration
  - Mix.Database.EntityConfigurations.SQLSERVER.MixViewTemplateContentConfiguration
  inheritedMembers:
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}.Config
  - Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}.Configure(EntityTypeBuilder{{T}})
  nameWithType.vb: SqlServerEntityBaseConfiguration(Of T, TPrimaryKey)
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
  fullName.vb: Mix.Database.EntityConfigurations.SQLSERVER.Base.SqlServerEntityBaseConfiguration(Of T, TPrimaryKey)
  name.vb: SqlServerEntityBaseConfiguration(Of T, TPrimaryKey)
references:
- uid: Mix.Database.EntityConfigurations.SQLSERVER.Base
  commentId: N:Mix.Database.EntityConfigurations.SQLSERVER.Base
  name: Mix.Database.EntityConfigurations.SQLSERVER.Base
  nameWithType: Mix.Database.EntityConfigurations.SQLSERVER.Base
  fullName: Mix.Database.EntityConfigurations.SQLSERVER.Base
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}
  commentId: T:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}
  parent: Mix.Database.EntityConfigurations.Base
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  name: EntityBaseConfiguration<T, TPrimaryKey, SqlServerDatabaseConstants>
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, SqlServerDatabaseConstants>
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants>
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, SqlServerDatabaseConstants)
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants)
  name.vb: EntityBaseConfiguration(Of T, TPrimaryKey, SqlServerDatabaseConstants)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants
    name: SqlServerDatabaseConstants
    nameWithType: SqlServerDatabaseConstants
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants
    name: SqlServerDatabaseConstants
    nameWithType: SqlServerDatabaseConstants
    fullName: Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}.Config
  commentId: P:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}.Config
  parent: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  name: Config
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, SqlServerDatabaseConstants>.Config
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants>.Config
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, SqlServerDatabaseConstants).Config
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants).Config
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}.Configure(EntityTypeBuilder{{T}})
  commentId: M:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{`0,`1,Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}.Configure(EntityTypeBuilder{`0})
  parent: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration{{T},{TPrimaryKey},Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants}
  definition: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  name: Configure(EntityTypeBuilder<T>)
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, SqlServerDatabaseConstants>.Configure(EntityTypeBuilder<T>)
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants>.Configure(EntityTypeBuilder<T>)
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, SqlServerDatabaseConstants).Configure(EntityTypeBuilder(Of T))
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants).Configure(EntityTypeBuilder(Of T))
  name.vb: Configure(EntityTypeBuilder(Of T))
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration<T, TPrimaryKey, SqlServerDatabaseConstants>.Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants>.Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration(Of T, TPrimaryKey, SqlServerDatabaseConstants).Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, Mix.Database.EntityConfigurations.SQLSERVER.SqlServerDatabaseConstants).Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  commentId: T:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
  name: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  name.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig)
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3
    name: EntityBaseConfiguration
    nameWithType: EntityBaseConfiguration
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TPrimaryKey
    nameWithType: TPrimaryKey
    fullName: TPrimaryKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TConfig
    nameWithType: TConfig
    fullName: TConfig
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Database.EntityConfigurations.Base
  commentId: N:Mix.Database.EntityConfigurations.Base
  name: Mix.Database.EntityConfigurations.Base
  nameWithType: Mix.Database.EntityConfigurations.Base
  fullName: Mix.Database.EntityConfigurations.Base
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  commentId: P:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Config
  name: Config
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Config
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Config
- uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  commentId: M:Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
  isExternal: true
  name: Configure(EntityTypeBuilder<T>)
  nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure(EntityTypeBuilder<T>)
  nameWithType.vb: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  fullName.vb: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure(EntityTypeBuilder(Of T))
  name.vb: Configure(EntityTypeBuilder(Of T))
  spec.csharp:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration<T, TPrimaryKey, TConfig>.Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration`3.Configure(EntityTypeBuilder{`0})
    name: Configure
    nameWithType: EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
    fullName: Mix.Database.EntityConfigurations.Base.EntityBaseConfiguration(Of T, TPrimaryKey, TConfig).Configure
  - name: (
    nameWithType: (
    fullName: (
  - uid: EntityTypeBuilder`1
    name: EntityTypeBuilder
    nameWithType: EntityTypeBuilder
    fullName: EntityTypeBuilder
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
