### YamlMime:ManagedReference
items:
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL
  commentId: N:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL
  id: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL
  children:
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeFieldConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetReferenceConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetValueConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeValueConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCacheConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCmsUserConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixConfigurationConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCultureConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixFileConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixLanguageConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixMediaConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModuleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModuleDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModulePostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPageConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPageModuleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPagePostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageNavigationConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageRoleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostMediaConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostModuleConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedAttributeDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedAttributeSetConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedDataConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedPostConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixTemplateConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixThemeConfiguration
  - Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixUrlAliasConfiguration
  langs:
  - csharp
  - vb
  name: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL
  nameWithType: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL
  type: Namespace
  assemblies:
  - Mix.Cms.Lib
references:
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeFieldConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeFieldConfiguration
  name: MixAttributeFieldConfiguration
  nameWithType: MixAttributeFieldConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeFieldConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetConfiguration
  name: MixAttributeSetConfiguration
  nameWithType: MixAttributeSetConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetDataConfiguration
  name: MixAttributeSetDataConfiguration
  nameWithType: MixAttributeSetDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetReferenceConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetReferenceConfiguration
  name: MixAttributeSetReferenceConfiguration
  nameWithType: MixAttributeSetReferenceConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetReferenceConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetValueConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetValueConfiguration
  name: MixAttributeSetValueConfiguration
  nameWithType: MixAttributeSetValueConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeSetValueConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeValueConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeValueConfiguration
  name: MixAttributeValueConfiguration
  nameWithType: MixAttributeValueConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixAttributeValueConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCacheConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCacheConfiguration
  name: MixCacheConfiguration
  nameWithType: MixCacheConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCacheConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCmsUserConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCmsUserConfiguration
  name: MixCmsUserConfiguration
  nameWithType: MixCmsUserConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCmsUserConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixConfigurationConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixConfigurationConfiguration
  name: MixConfigurationConfiguration
  nameWithType: MixConfigurationConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixConfigurationConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCultureConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCultureConfiguration
  name: MixCultureConfiguration
  nameWithType: MixCultureConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixCultureConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixFileConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixFileConfiguration
  name: MixFileConfiguration
  nameWithType: MixFileConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixFileConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixLanguageConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixLanguageConfiguration
  name: MixLanguageConfiguration
  nameWithType: MixLanguageConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixLanguageConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixMediaConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixMediaConfiguration
  name: MixMediaConfiguration
  nameWithType: MixMediaConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixMediaConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModuleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModuleConfiguration
  name: MixModuleConfiguration
  nameWithType: MixModuleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModuleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModuleDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModuleDataConfiguration
  name: MixModuleDataConfiguration
  nameWithType: MixModuleDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModuleDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModulePostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModulePostConfiguration
  name: MixModulePostConfiguration
  nameWithType: MixModulePostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixModulePostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPageConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPageConfiguration
  name: MixPageConfiguration
  nameWithType: MixPageConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPageConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPageModuleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPageModuleConfiguration
  name: MixPageModuleConfiguration
  nameWithType: MixPageModuleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPageModuleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPagePostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPagePostConfiguration
  name: MixPagePostConfiguration
  nameWithType: MixPagePostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPagePostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageConfiguration
  name: MixPortalPageConfiguration
  nameWithType: MixPortalPageConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageNavigationConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageNavigationConfiguration
  name: MixPortalPageNavigationConfiguration
  nameWithType: MixPortalPageNavigationConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageNavigationConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageRoleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageRoleConfiguration
  name: MixPortalPageRoleConfiguration
  nameWithType: MixPortalPageRoleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPortalPageRoleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostConfiguration
  name: MixPostConfiguration
  nameWithType: MixPostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostMediaConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostMediaConfiguration
  name: MixPostMediaConfiguration
  nameWithType: MixPostMediaConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostMediaConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostModuleConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostModuleConfiguration
  name: MixPostModuleConfiguration
  nameWithType: MixPostModuleConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixPostModuleConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedAttributeDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedAttributeDataConfiguration
  name: MixRelatedAttributeDataConfiguration
  nameWithType: MixRelatedAttributeDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedAttributeDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedAttributeSetConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedAttributeSetConfiguration
  name: MixRelatedAttributeSetConfiguration
  nameWithType: MixRelatedAttributeSetConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedAttributeSetConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedDataConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedDataConfiguration
  name: MixRelatedDataConfiguration
  nameWithType: MixRelatedDataConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedDataConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedPostConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedPostConfiguration
  name: MixRelatedPostConfiguration
  nameWithType: MixRelatedPostConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixRelatedPostConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixTemplateConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixTemplateConfiguration
  name: MixTemplateConfiguration
  nameWithType: MixTemplateConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixTemplateConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixThemeConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixThemeConfiguration
  name: MixThemeConfiguration
  nameWithType: MixThemeConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixThemeConfiguration
- uid: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixUrlAliasConfiguration
  commentId: T:Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixUrlAliasConfiguration
  name: MixUrlAliasConfiguration
  nameWithType: MixUrlAliasConfiguration
  fullName: Mix.Cms.Lib.Models.EntityConfigurations.POSTGRESQL.MixUrlAliasConfiguration
