### YamlMime:ManagedReference
items:
- uid: Mix.Constant.Constants.MixAppSettingsSection
  commentId: T:Mix.Constant.Constants.MixAppSettingsSection
  id: MixAppSettingsSection
  parent: Mix.Constant.Constants
  children:
  - Mix.Constant.Constants.MixAppSettingsSection.Authentication
  - Mix.Constant.Constants.MixAppSettingsSection.Azure
  - Mix.Constant.Constants.MixAppSettingsSection.ConnectionStrings
  - Mix.Constant.Constants.MixAppSettingsSection.Database
  - Mix.Constant.Constants.MixAppSettingsSection.GlobalSettings
  - Mix.Constant.Constants.MixAppSettingsSection.GoogleFirebase
  - Mix.Constant.Constants.MixAppSettingsSection.IpSecuritySettings
  - Mix.Constant.Constants.MixAppSettingsSection.MixConfigurations
  - Mix.Constant.Constants.MixAppSettingsSection.MixHeart
  - Mix.Constant.Constants.MixAppSettingsSection.Smtp
  langs:
  - csharp
  - vb
  name: MixAppSettingsSection
  nameWithType: MixAppSettingsSection
  fullName: Mix.Constant.Constants.MixAppSettingsSection
  type: Class
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MixAppSettingsSection
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 2
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public class MixAppSettingsSection
    content.vb: Public Class MixAppSettingsSection
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Constant.Constants.MixAppSettingsSection.ConnectionStrings
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.ConnectionStrings
  id: ConnectionStrings
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: ConnectionStrings
  nameWithType: MixAppSettingsSection.ConnectionStrings
  fullName: Mix.Constant.Constants.MixAppSettingsSection.ConnectionStrings
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: ConnectionStrings
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 4
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string ConnectionStrings = "ConnectionStrings"
    return:
      type: System.String
    content.vb: Public Const ConnectionStrings As String = "ConnectionStrings"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Constant.Constants.MixAppSettingsSection.Database
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.Database
  id: Database
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: Database
  nameWithType: MixAppSettingsSection.Database
  fullName: Mix.Constant.Constants.MixAppSettingsSection.Database
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Database
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 5
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string Database = "Database"
    return:
      type: System.String
    content.vb: Public Const Database As String = "Database"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Constant.Constants.MixAppSettingsSection.MixConfigurations
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.MixConfigurations
  id: MixConfigurations
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: MixConfigurations
  nameWithType: MixAppSettingsSection.MixConfigurations
  fullName: Mix.Constant.Constants.MixAppSettingsSection.MixConfigurations
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MixConfigurations
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 6
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string MixConfigurations = "MixConfigurations"
    return:
      type: System.String
    content.vb: Public Const MixConfigurations As String = "MixConfigurations"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Constant.Constants.MixAppSettingsSection.Authentication
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.Authentication
  id: Authentication
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: Authentication
  nameWithType: MixAppSettingsSection.Authentication
  fullName: Mix.Constant.Constants.MixAppSettingsSection.Authentication
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Authentication
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 7
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string Authentication = "Authentication"
    return:
      type: System.String
    content.vb: Public Const Authentication As String = "Authentication"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Constant.Constants.MixAppSettingsSection.IpSecuritySettings
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.IpSecuritySettings
  id: IpSecuritySettings
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: IpSecuritySettings
  nameWithType: MixAppSettingsSection.IpSecuritySettings
  fullName: Mix.Constant.Constants.MixAppSettingsSection.IpSecuritySettings
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: IpSecuritySettings
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 8
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string IpSecuritySettings = "IpSecuritySettings"
    return:
      type: System.String
    content.vb: Public Const IpSecuritySettings As String = "IpSecuritySettings"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Constant.Constants.MixAppSettingsSection.GlobalSettings
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.GlobalSettings
  id: GlobalSettings
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: GlobalSettings
  nameWithType: MixAppSettingsSection.GlobalSettings
  fullName: Mix.Constant.Constants.MixAppSettingsSection.GlobalSettings
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: GlobalSettings
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 9
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string GlobalSettings = "GlobalSettings"
    return:
      type: System.String
    content.vb: Public Const GlobalSettings As String = "GlobalSettings"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Constant.Constants.MixAppSettingsSection.Smtp
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.Smtp
  id: Smtp
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: Smtp
  nameWithType: MixAppSettingsSection.Smtp
  fullName: Mix.Constant.Constants.MixAppSettingsSection.Smtp
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Smtp
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 10
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string Smtp = "Smtp"
    return:
      type: System.String
    content.vb: Public Const Smtp As String = "Smtp"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Constant.Constants.MixAppSettingsSection.MixHeart
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.MixHeart
  id: MixHeart
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: MixHeart
  nameWithType: MixAppSettingsSection.MixHeart
  fullName: Mix.Constant.Constants.MixAppSettingsSection.MixHeart
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MixHeart
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 11
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string MixHeart = "MixHeart"
    return:
      type: System.String
    content.vb: Public Const MixHeart As String = "MixHeart"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Constant.Constants.MixAppSettingsSection.GoogleFirebase
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.GoogleFirebase
  id: GoogleFirebase
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: GoogleFirebase
  nameWithType: MixAppSettingsSection.GoogleFirebase
  fullName: Mix.Constant.Constants.MixAppSettingsSection.GoogleFirebase
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: GoogleFirebase
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 12
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string GoogleFirebase = "GoogleFirebase"
    return:
      type: System.String
    content.vb: Public Const GoogleFirebase As String = "GoogleFirebase"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mix.Constant.Constants.MixAppSettingsSection.Azure
  commentId: F:Mix.Constant.Constants.MixAppSettingsSection.Azure
  id: Azure
  parent: Mix.Constant.Constants.MixAppSettingsSection
  langs:
  - csharp
  - vb
  name: Azure
  nameWithType: MixAppSettingsSection.Azure
  fullName: Mix.Constant.Constants.MixAppSettingsSection.Azure
  type: Field
  source:
    remote:
      path: src/platform/mix.constant/Constants/MixAppSettingsSection.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Azure
    path: ../../mix.core/src/platform/mix.constant/Constants/MixAppSettingsSection.cs
    startLine: 13
  assemblies:
  - mix.constant
  namespace: Mix.Constant.Constants
  syntax:
    content: public const string Azure = "Azure"
    return:
      type: System.String
    content.vb: Public Const Azure As String = "Azure"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Mix.Constant.Constants
  commentId: N:Mix.Constant.Constants
  name: Mix.Constant.Constants
  nameWithType: Mix.Constant.Constants
  fullName: Mix.Constant.Constants
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
