### YamlMime:ManagedReference
items:
- uid: Mix.Lib.Services.MixConfigurationService
  commentId: T:Mix.Lib.Services.MixConfigurationService
  id: MixConfigurationService
  parent: Mix.Lib.Services
  children:
  - Mix.Lib.Services.MixConfigurationService.#ctor
  - Mix.Lib.Services.MixConfigurationService.Reload(MixCmsContext,Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction)
  langs:
  - csharp
  - vb
  name: MixConfigurationService
  nameWithType: MixConfigurationService
  fullName: Mix.Lib.Services.MixConfigurationService
  type: Class
  source:
    remote:
      path: src/platform/mix.library/Services/MixConfigurationService.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: MixConfigurationService
    path: ../../mix.core/src/platform/mix.library/Services/MixConfigurationService.cs
    startLine: 4
  assemblies:
  - mix.library
  namespace: Mix.Lib.Services
  syntax:
    content: 'public class MixConfigurationService : JsonConfigurationServiceBase'
    content.vb: >-
      Public Class MixConfigurationService
          Inherits JsonConfigurationServiceBase
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Lib.Services.MixConfigurationService.#ctor
  commentId: M:Mix.Lib.Services.MixConfigurationService.#ctor
  id: '#ctor'
  parent: Mix.Lib.Services.MixConfigurationService
  langs:
  - csharp
  - vb
  name: MixConfigurationService()
  nameWithType: MixConfigurationService.MixConfigurationService()
  fullName: Mix.Lib.Services.MixConfigurationService.MixConfigurationService()
  type: Constructor
  source:
    remote:
      path: src/platform/mix.library/Services/MixConfigurationService.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: .ctor
    path: ../../mix.core/src/platform/mix.library/Services/MixConfigurationService.cs
    startLine: 6
  assemblies:
  - mix.library
  namespace: Mix.Lib.Services
  syntax:
    content: public MixConfigurationService()
    content.vb: Public Sub New
  overload: Mix.Lib.Services.MixConfigurationService.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Mix.Lib.Services.MixConfigurationService.Reload(MixCmsContext,Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction)
  commentId: M:Mix.Lib.Services.MixConfigurationService.Reload(MixCmsContext,Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction)
  id: Reload(MixCmsContext,Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction)
  parent: Mix.Lib.Services.MixConfigurationService
  langs:
  - csharp
  - vb
  name: Reload(MixCmsContext, IDbContextTransaction)
  nameWithType: MixConfigurationService.Reload(MixCmsContext, IDbContextTransaction)
  fullName: Mix.Lib.Services.MixConfigurationService.Reload(MixCmsContext, Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction)
  type: Method
  source:
    remote:
      path: src/platform/mix.library/Services/MixConfigurationService.cs
      branch: develop
      repo: https://github.com/mixcore/mix.core.git
    id: Reload
    path: ../../mix.core/src/platform/mix.library/Services/MixConfigurationService.cs
    startLine: 10
  assemblies:
  - mix.library
  namespace: Mix.Lib.Services
  syntax:
    content: public static void Reload(MixCmsContext _context = null, IDbContextTransaction _transaction = null)
    parameters:
    - id: _context
      type: MixCmsContext
    - id: _transaction
      type: Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction
    content.vb: Public Shared Sub Reload(_context As MixCmsContext = Nothing, _transaction As IDbContextTransaction = Nothing)
  overload: Mix.Lib.Services.MixConfigurationService.Reload*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Mix.Lib.Services
  commentId: N:Mix.Lib.Services
  name: Mix.Lib.Services
  nameWithType: Mix.Lib.Services
  fullName: Mix.Lib.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Lib.Services.MixConfigurationService.#ctor*
  commentId: Overload:Mix.Lib.Services.MixConfigurationService.#ctor
  name: MixConfigurationService
  nameWithType: MixConfigurationService.MixConfigurationService
  fullName: Mix.Lib.Services.MixConfigurationService.MixConfigurationService
- uid: Mix.Lib.Services.MixConfigurationService.Reload*
  commentId: Overload:Mix.Lib.Services.MixConfigurationService.Reload
  name: Reload
  nameWithType: MixConfigurationService.Reload
  fullName: Mix.Lib.Services.MixConfigurationService.Reload
- uid: MixCmsContext
  isExternal: true
  name: MixCmsContext
  nameWithType: MixCmsContext
  fullName: MixCmsContext
- uid: Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction
  commentId: T:Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction
  parent: Microsoft.EntityFrameworkCore.Storage
  isExternal: true
  name: IDbContextTransaction
  nameWithType: IDbContextTransaction
  fullName: Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction
- uid: Microsoft.EntityFrameworkCore.Storage
  commentId: N:Microsoft.EntityFrameworkCore.Storage
  isExternal: true
  name: Microsoft.EntityFrameworkCore.Storage
  nameWithType: Microsoft.EntityFrameworkCore.Storage
  fullName: Microsoft.EntityFrameworkCore.Storage
