@startuml
class DefaultViewModel {
    + Id : string <<get>> <<set>>
    + UserId : string <<get>> <<set>>
    + ConnectionId : string <<get>> <<set>>
    + DeviceId : string <<get>> <<set>>
    + EndDate : DateTime? <<get>> <<set>>
    + DefaultViewModel()
    + DefaultViewModel(model:MixMessengerUserDevice, _context:MixChatServiceContext, _transaction:IDbContextTransaction)
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixChatServiceContext,MixMessengerUserDevice,DefaultViewModel>" <|-- DefaultViewModel
DefaultViewModel --> "StartDate" DateTime
@enduml
