@startuml
class "HubRequest`1"<T> {
    + Uid : string <<get>> <<set>>
    + From : string <<get>> <<set>>
    + To : string <<get>> <<set>>
    + AttributeSetName : string <<get>> <<set>>
    + Action : string <<get>> <<set>>
    + Data : T <<get>> <<set>>
    + Room : string <<get>> <<set>>
    + IsMySelf : bool <<get>> <<set>>
    + IsSave : bool <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
}
"HubRequest`1" --> "Connection" MessengerConnection
"HubRequest`1" --> "RequestDate" DateTime
@enduml
