@startuml
class MixAttributeValueConfiguration {
    + Configure(builder:EntityTypeBuilder<MixAttributeSetValue>) : void
}
"IEntityTypeConfiguration`1" "<MixAttributeSetValue>" <|-- MixAttributeValueConfiguration
@enduml
