@startuml
class MixAttributeSetDataConfiguration {
    + Configure(entity:EntityTypeBuilder<MixAttributeSetData>) : void
}
"IEntityTypeConfiguration`1" "<MixAttributeSetData>" <|-- MixAttributeSetDataConfiguration
@enduml
