@startuml
class MixConfigurationConfiguration {
    + Configure(entity:EntityTypeBuilder<MixConfiguration>) : void
}
"IEntityTypeConfiguration`1" "<MixConfiguration>" <|-- MixConfigurationConfiguration
@enduml
