@startuml
class MixRelatedAttributeSetConfiguration {
    + Configure(entity:EntityTypeBuilder<MixRelatedAttributeSet>) : void
}
"IEntityTypeConfiguration`1" "<MixRelatedAttributeSet>" <|-- MixRelatedAttributeSetConfiguration
@enduml
