@startuml
class MixRelatedAttributeDataConfiguration {
    + Configure(entity:EntityTypeBuilder<MixRelatedAttributeData>) : void
}
"IEntityTypeConfiguration`1" "<MixRelatedAttributeData>" <|-- MixRelatedAttributeDataConfiguration
@enduml
