@startuml
class MixUrlHelperExtensions <<static>> {
    + {static} AbsoluteAction(url:IUrlHelper, actionName:string, controllerName:string, routeValues:object) : string
    + {static} AbsoluteContent(url:IUrlHelper, contentPath:string) : string
    + {static} AbsoluteRouteUrl(url:IUrlHelper, routeName:string, routeValues:object) : string
}
@enduml
