@startuml
class ReadViewModel {
    + ReadViewModel(model:MixPostMedia, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + ReadViewModel()
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + MediaId : int <<get>> <<set>>
    + PostId : int <<get>> <<set>>
    + IsActived : bool <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixPostMedia
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + <<override>> SaveSubModels(parent:MixPostMedia, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<bool>
    + <<override>> <<async>> SaveSubModelsAsync(parent:MixPostMedia, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixCmsContext,MixPostMedia,ReadViewModel>" <|-- ReadViewModel
ReadViewModel --> "CreatedDateTime" DateTime
ReadViewModel --> "Status" MixContentStatus
ReadViewModel --> "Media" UpdateViewModel
@enduml
