@startuml
class ReadMvcViewModel {
    + ReadMvcViewModel(model:MixPagePost, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + ReadMvcViewModel()
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + PostId : int <<get>> <<set>>
    + PageId : int <<get>> <<set>>
    + IsActived : bool <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + Post : MixPosts.ReadListItemViewModel <<get>> <<set>>
    + Page : MixPages.ReadViewModel <<get>> <<set>>
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixPagePost
    + LoadPage(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + LoadPost(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + {static} GetPagePostNavAsync(postId:int, specificulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<List<MixPagePosts.ReadViewModel>>
}
"ViewModelBase`3" "<MixCmsContext,MixPagePost,ReadMvcViewModel>" <|-- ReadMvcViewModel
@enduml
