@startuml
class GraphQLQuery {
    + GraphQLQuery(dbContext:DbContext, dbMetadata:IDatabaseMetadata, tableNameLookup:ITableNameLookup)
}
class "ObjectGraphType`1"<T> {
}
"ObjectGraphType`1" "<object>" <|-- GraphQLQuery
@enduml
