@startuml
class QueryFilterHelper {
    + TestCreateModel() : void
    + {static} CreateExpression(jsonQuery:JObject) : Expression<Func<MixAttributeSetValue, bool>>
    - {static} GetExpression(expressionModel:ExpressionModel) : Expression<Func<MixAttributeSetValue, bool>>
    - {static} CombineExpressionByType(type:MixLogicalOperatorKind, expr1:Expression<Func<MixAttributeSetValue, bool>>, expr2:Expression<Func<MixAttributeSetValue, bool>>) : Expression<Func<MixAttributeSetValue, bool>>
    - {static} GetFunction(functionModel:FunctionModel) : Expression<Func<MixAttributeSetValue, bool>>
    - {static} buildLikeString(stringValue:string) : string
}
@enduml
