@startuml
class UserRoleModel {
    + UserId : string <<get>> <<set>>
    + RoleId : string <<get>> <<set>>
    + RoleName : string <<get>> <<set>>
    + IsUserInRole : bool <<get>> <<set>>
}
@enduml
