@startuml
class IdentityHelper {
    + IdentityHelper(userManager:UserManager<ApplicationUser>, signInManager:SignInManager<ApplicationUser>, roleManager:RoleManager<IdentityRole>)
    + <<async>> GenerateAccessTokenAsync(user:ApplicationUser, isRemember:bool) : Task<AccessTokenViewModel>
    + <<async>> GenerateTokenAsync(user:ApplicationUser, expires:DateTime, refreshToken:string) : Task<string>
    + <<async>> GetClaimsAsync(user:ApplicationUser) : Task<List<Claim>>
    + CreateClaim(type:string, value:string) : Claim
    + GetPrincipalFromExpiredToken(token:string) : ClaimsPrincipal
}
class JwtSecurityKey <<static>> {
    + {static} Create(secret:string) : SymmetricSecurityKey
}
IdentityHelper +-- JwtSecurityKey
@enduml
