@startuml
class MixCacheService {
    + MixCacheService()
    + {static} GetAsync(key:string) : Task<T>
    + {static} RemoveCacheAsync() : Task
}
class "DefaultModelRepository`2"<T1,T2> {
}
MixCacheService --> "Repository<MixCmsContext,MixCache>" "DefaultModelRepository`2"
MixCacheService --> "Instance" MixCacheService
@enduml
