@startuml
class IndexViewModel {
    + HasPassword : bool <<get>> <<set>>
    + Logins : IList<UserLoginInfo> <<get>> <<set>>
    + PhoneNumber : string <<get>> <<set>>
    + TwoFactor : bool <<get>> <<set>>
    + BrowserRemembered : bool <<get>> <<set>>
}
@enduml
