@startuml
class ReadViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + ImageUrl : string <<get>>
    + ThumbnailUrl : string <<get>>
    + IsActived : bool <<get>> <<set>>
    + Asset : IFormFile <<get>> <<set>>
    + AssetFolder : string <<get>>
    + UploadsFolder : string <<get>>
    + TemplateFolder : string <<get>>
    + Domain : string <<get>>
    + ReadViewModel()
    + ReadViewModel(model:MixTheme, _context:MixCmsContext, _transaction:IDbContextTransaction)
}
"ViewModelBase`3" "<MixCmsContext,MixTheme,ReadViewModel>" <|-- ReadViewModel
@enduml
