@startuml
class ReadViewModel {
    + Id : int <<get>> <<set>>
    + PageId : int <<get>> <<set>>
    + RoleId : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + IsActived : bool <<get>> <<set>>
    + ReadViewModel(model:MixPortalPageRole, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + ReadViewModel()
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixPortalPageRole
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixCmsContext,MixPortalPageRole,ReadViewModel>" <|-- ReadViewModel
ReadViewModel --> "CreatedDateTime" DateTime
ReadViewModel --> "Status" MixContentStatus
@enduml
