@startuml
class TableType {
    + TableType(tableMetadata:TableMetadata, type:Type)
}
class "ObjectGraphType`1"<T> {
}
"ObjectGraphType`1" "<object>" <|-- TableType
TableType --> "TableArgs" QueryArguments
TableType --> "_type" Type
@enduml
