@startuml
class RegisterViewModel {
    + FirstName : string <<get>> <<set>>
    + LastName : string <<get>> <<set>>
    + NickName : string <<get>> <<set>>
    + UserName : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
    + ReturnUrl : string <<get>> <<set>>
}
@enduml
