@startuml
class VerifyCodeViewModel {
    + Provider : string <<get>> <<set>>
    + Code : string <<get>> <<set>>
    + ReturnUrl : string <<get>> <<set>>
    + RememberBrowser : bool <<get>> <<set>>
    + RememberMe : bool <<get>> <<set>>
}
@enduml
