@startuml
class MixModulePostConfiguration {
    + Configure(entity:EntityTypeBuilder<MixModulePost>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixModulePost>" <|-- MixModulePostConfiguration
@enduml
