@startuml
class MixPostConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPost>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixPost>" <|-- MixPostConfiguration
@enduml
