@startuml
class MixPageModuleConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPageModule>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixPageModule>" <|-- MixPageModuleConfiguration
@enduml
