@startuml
class MixPostModuleConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPostModule>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixPostModule>" <|-- MixPostModuleConfiguration
@enduml
