@startuml
class ReadMvcViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Icon : string <<get>> <<set>>
    + CssClass : string <<get>> <<set>>
    + Layout : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Excerpt : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + SeoName : string <<get>> <<set>>
    + SeoTitle : string <<get>> <<set>>
    + SeoDescription : string <<get>> <<set>>
    + SeoKeywords : string <<get>> <<set>>
    + Source : string <<get>> <<set>>
    + Views : int? <<get>> <<set>>
    + Tags : string <<get>> <<set>>
    + StaticUrl : string <<get>> <<set>>
    + Level : int? <<get>> <<set>>
    + PageSize : int? <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + DetailsUrl : string <<get>>
    + Domain : string <<get>>
    + ImageUrl : string <<get>>
    + ThumbnailUrl : string <<get>>
    + TemplatePath : string <<get>>
    + ReadMvcViewModel()
    + ReadMvcViewModel(model:MixPage, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + LoadData(pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + LoadDataByTag(tagName:string, orderBy:string, orderDirection:int, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + LoadDataByKeyword(keyword:string, orderBy:string, orderDirection:int, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + GetModule(name:string) : MixModules.ReadMvcViewModel
    + HasValue(fieldName:string) : bool
    + Property(fieldName:string) : T
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
class "PaginationModel`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixPage,ReadMvcViewModel>" <|-- ReadMvcViewModel
MvcViewModel <|-- ReadMvcViewModel
ReadMvcViewModel --> "Cultures<Domain.Core.Models.SupportedCulture>" "List`1"
ReadMvcViewModel --> "Type" MixPageType
ReadMvcViewModel --> "CreatedDateTime" DateTime
ReadMvcViewModel --> "Status" MixContentStatus
ReadMvcViewModel o-> "Posts<MixPagePosts.ReadViewModel>" "PaginationModel`1"
ReadMvcViewModel o-> "Modules<MixPageModules.ReadMvcViewModel>" "List`1"
@enduml
