@startuml
class UpdateViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Icon : string <<get>> <<set>>
    + CssClass : string <<get>> <<set>>
    + Layout : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Excerpt : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + SeoName : string <<get>> <<set>>
    + SeoTitle : string <<get>> <<set>>
    + SeoDescription : string <<get>> <<set>>
    + SeoKeywords : string <<get>> <<set>>
    + Source : string <<get>> <<set>>
    + Views : int? <<get>> <<set>>
    + Tags : string <<get>> <<set>>
    + StaticUrl : string <<get>> <<set>>
    + Level : int? <<get>> <<set>>
    + PageSize : int? <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + DetailsUrl : string <<get>>
    + Domain : string <<get>>
    + ImageUrl : string <<get>>
    + ThumbnailUrl : string <<get>>
    + ActivedTheme : int <<get>>
    + TemplateFolderType : string <<get>>
    + TemplateFolder : string <<get>>
    + UpdateViewModel()
    + UpdateViewModel(model:MixPage, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixPage
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + <<override>> SaveSubModels(parent:MixPage, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<bool>
    + <<override>> <<async>> SaveSubModelsAsync(parent:MixPage, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    + GetAliases(context:MixCmsContext, transaction:IDbContextTransaction) : List<MixUrlAliases.UpdateViewModel>
    + GetModuleNavs(context:MixCmsContext, transaction:IDbContextTransaction) : List<MixPageModules.ReadMvcViewModel>
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixPage,UpdateViewModel>" <|-- UpdateViewModel
UpdateViewModel --> "Cultures<Domain.Core.Models.SupportedCulture>" "List`1"
UpdateViewModel o-> "Type" MixPageType
UpdateViewModel --> "CreatedDateTime" DateTime
UpdateViewModel --> "Status" MixContentStatus
UpdateViewModel --> "ModuleNavs<MixPageModules.ReadMvcViewModel>" "List`1"
UpdateViewModel o-> "ListTag" JArray
UpdateViewModel --> "ImageFileStream" FileStreamViewModel
UpdateViewModel --> "Templates<MixTemplates.UpdateViewModel>" "List`1"
UpdateViewModel --> "Masters<MixTemplates.UpdateViewModel>" "List`1"
UpdateViewModel --> "UrlAliases<MixUrlAliases.UpdateViewModel>" "List`1"
UpdateViewModel --> "SysCategories<MixRelatedAttributeDatas.UpdateViewModel>" "List`1"
UpdateViewModel --> "SysTags<MixRelatedAttributeDatas.UpdateViewModel>" "List`1"
@enduml
