@startuml
class DeleteViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Cultures : List<Domain.Core.Models.SupportedCulture> <<get>> <<set>>
    + Keyword : string <<get>> <<set>>
    + Category : string <<get>> <<set>>
    + DataType : MixDataType <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Value : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + DeleteViewModel()
    + DeleteViewModel(model:MixConfiguration, _context:MixCmsContext, _transaction:IDbContextTransaction)
}
"ViewModelBase`3" "<MixCmsContext,MixConfiguration,DeleteViewModel>" <|-- DeleteViewModel
@enduml
