@startuml
class ImportViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Cultures : System.Collections.Generic.List<Domain.Core.Models.SupportedCulture> <<get>> <<set>>
    + Keyword : string <<get>> <<set>>
    + Category : string <<get>> <<set>>
    + Value : string <<get>> <<set>>
    + DataType : MixDataType <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + Domain : string <<get>>
    + Property : DataValueViewModel <<get>> <<set>>
    + ImportViewModel()
    + ImportViewModel(model:MixConfiguration, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixConfiguration
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + <<override>> <<async>> SaveModelAsync(isSaveSubModels:bool, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<ImportViewModel>>
    + {static} <<async>> ImportConfigurations(arrConfiguration:List<MixConfiguration>, destCulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    - LoadCultures(initCulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : List<SupportedCulture>
}
"ViewModelBase`3" "<MixCmsContext,MixConfiguration,ImportViewModel>" <|-- ImportViewModel
@enduml
