@startuml
class Startup <<partial>> {
    + Startup(configuration:IConfiguration)
    <<readonly>> MixcoreAllowSpecificOrigins : string = "_mixcoreAllowSpecificOrigins"
    + Configuration : IConfiguration <<get>>
    + ConfigureServices(services:IServiceCollection) : void
    + Configure(app:IApplicationBuilder, env:IWebHostEnvironment) : void
    - VerifyInitData(services:IServiceCollection) : void
}
@enduml
