@startuml
class MixPostMediaConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPostMedia>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixPostMedia>" <|-- MixPostMediaConfiguration
@enduml
