@startuml
class MixRelatedAttributeSetConfiguration {
    + Configure(entity:EntityTypeBuilder<MixRelatedAttributeSet>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixRelatedAttributeSet>" <|-- MixRelatedAttributeSetConfiguration
@enduml
