@startuml
class MixAttributeFieldConfiguration {
    + Configure(entity:EntityTypeBuilder<MixAttributeField>) : void
}
"IEntityTypeConfiguration`1" "<MixAttributeField>" <|-- MixAttributeFieldConfiguration
@enduml
