@startuml
class MixAttributeSetReferenceConfiguration {
    + Configure(entity:EntityTypeBuilder<MixAttributeSetReference>) : void
}
"IEntityTypeConfiguration`1" "<MixAttributeSetReference>" <|-- MixAttributeSetReferenceConfiguration
@enduml
