@startuml
class MixPortalPageRoleConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPortalPageRole>) : void
}
"IEntityTypeConfiguration`1" "<MixPortalPageRole>" <|-- MixPortalPageRoleConfiguration
@enduml
