@startuml
class MixRelatedPostConfiguration {
    + Configure(entity:EntityTypeBuilder<MixRelatedPost>) : void
}
"IEntityTypeConfiguration`1" "<MixRelatedPost>" <|-- MixRelatedPostConfiguration
@enduml
