@startuml
class Program {
    + {static} Main(args:string[]) : void
    + {static} CreateHostBuilder(args:string[]) : IHostBuilder
}
class Startup <<partial>> {
    + Startup(configuration:IConfiguration)
    <<readonly>> MixcoreAllowSpecificOrigins : string = "_mixcoreAllowSpecificOrigins"
    + ConfigureServices(services:IServiceCollection) : void
    + Configure(app:IApplicationBuilder, env:IWebHostEnvironment) : void
}
Startup --> "Configuration" IConfiguration
class AuthServiceCollectionExtensions <<static>> {
    + {static} AddMixAuthorize(services:IServiceCollection, Configuration:IConfiguration) : IServiceCollection
    + {static} UseMixAuthorize(app:IApplicationBuilder) : IApplicationBuilder
}
class JwtSecurityKey <<static>> {
    + {static} Create(secret:string) : SymmetricSecurityKey
}
AuthServiceCollectionExtensions +-- JwtSecurityKey
class MixRoutesServiceCollectionExtensions <<static>> {
    + {static} UseMixRoutes(app:IApplicationBuilder) : IApplicationBuilder
}
class Startup <<partial>> {
    + ConfigureSignalRServices(services:IServiceCollection) : void
    + ConfigurationSignalR(app:IApplicationBuilder) : void
}
class BaseController {
    + BaseController()
    + culture : string <<get>> <<set>>
    + <<override>> OnActionExecuting(context:ActionExecutingContext) : void
    + <<async>> Error(page:string) : System.Threading.Tasks.Task<IActionResult>
}
Controller <|-- BaseController
BaseController --> "ViewContext" ViewContext
class DataController {
    + <<async>> Index(attributeSetName:string, seoName:string) : Task<IActionResult>
}
BaseController <|-- DataController
class HomeController {
    + <<async>> Index(seoName:string) : Task<IActionResult>
}
BaseController <|-- HomeController
class InitController {
    + Index(page:string) : IActionResult
}
BaseController <|-- InitController
class ModuleController {
    + <<async>> Index(id:int, culture:string, seoName:string) : Task<IActionResult>
}
BaseController <|-- ModuleController
class PageController {
    + <<async>> Index(culture:string, seoName:string) : Task<IActionResult>
}
BaseController <|-- PageController
class PortalController {
    + Index(page:string) : IActionResult
}
BaseController <|-- PortalController
class PostController {
    + <<async>> Index(id:int, culture:string, seoName:string) : Task<IActionResult>
}
BaseController <|-- PostController
class SecurityController {
    + Index(page:string) : IActionResult
}
BaseController <|-- SecurityController
class VueController {
    + <<async>> Index(culture:string, seoName:string) : Task<PartialViewResult>
}
BaseController <|-- VueController
class ErrorViewModel {
    + RequestId : string <<get>> <<set>>
    + ShowRequestId : bool <<get>>
}
class MethodRules {
    + {static} RedirectXMLRequests(context:RewriteContext) : void
}
class RedirectImageRequests {
    + RedirectImageRequests(extension:string, newPath:string)
    + ApplyRule(context:RewriteContext) : void
}
IRule <|-- RedirectImageRequests
class CookieValidator {
    + {static} <<async>> ValidateAsync(context:CookieValidatePrincipalContext) : Task
}
class JwtValidator {
    + {static} ValidateAsync(context:TokenValidatedContext) : void
    + {static} ValidateFail(context:AuthenticationFailedContext) : void
}
class Views__ViewImports {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views__ViewStart {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class wwwroot__ProductDetailImages {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views__ViewImports {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views__ViewStart {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class wwwroot__ProductDetailImages {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Data_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Home_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Home_Module {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Init_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Module_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Page_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Portal_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Post_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Security_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared_Error {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared__Layout {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared__LayoutInit_Angular {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared__LayoutPortal_Angular {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class "UserManager`1"<T> {
}
Views_Shared__LayoutPortal_Angular --> "UserManager<ApplicationUser>" "UserManager`1"
class Views_Shared__LayoutPortal_Angular_bk {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class "UserManager`1"<T> {
}
Views_Shared__LayoutPortal_Angular_bk --> "UserManager<ApplicationUser>" "UserManager`1"
class Views_Shared__LayoutSecurity_Angular {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared__LoginPartial {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class "UserManager`1"<T> {
}
class "SignInManager`1"<T> {
}
Views_Shared__LoginPartial --> "UserManager<ApplicationUser>" "UserManager`1"
Views_Shared__LoginPartial --> "SignInManager<ApplicationUser>" "SignInManager`1"
class Views_Shared__ValidationScriptsPartial {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Vue_VueComponent {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Data_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Home_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Home_Module {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Init_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Module_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Page_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Portal_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Post_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Security_Index {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared_Error {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared__Layout {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared__LayoutInit_Angular {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared__LayoutPortal_Angular {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class "UserManager`1"<T> {
}
Views_Shared__LayoutPortal_Angular --> "UserManager<ApplicationUser>" "UserManager`1"
class Views_Shared__LayoutPortal_Angular_bk {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class "UserManager`1"<T> {
}
Views_Shared__LayoutPortal_Angular_bk --> "UserManager<ApplicationUser>" "UserManager`1"
class Views_Shared__LayoutSecurity_Angular {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Shared__LoginPartial {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class "UserManager`1"<T> {
}
class "SignInManager`1"<T> {
}
Views_Shared__LoginPartial --> "UserManager<ApplicationUser>" "UserManager`1"
Views_Shared__LoginPartial --> "SignInManager<ApplicationUser>" "SignInManager`1"
class Views_Shared__ValidationScriptsPartial {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
class Views_Vue_VueComponent {
    + <<async>> <<override>> ExecuteAsync() : global::System.Threading.Tasks.Task
}
class "RazorPage`1"<T> {
}
@enduml
