@startuml
class FunctionModel {
    + FieldName : string <<get>> <<set>>
    + Rule : MixCompareOperatorKind <<get>> <<set>>
    + Value : string <<get>> <<set>>
    + MinValue : string <<get>> <<set>>
    + MaxValue : string <<get>> <<set>>
    + {static} Create(rule:MixCompareOperatorKind, fieldName:string, value:string) : FunctionModel
    + {static} Create(operatorKind:MixCompareOperatorKind, fieldName:string, minValue:string, maxValue:string) : FunctionModel
}
@enduml
