@startuml
class RequestFormSizeLimitAttribute {
    + RequestFormSizeLimitAttribute(valueCountLimit:int)
    + Order : int <<get>> <<set>>
    + OnAuthorization(context:AuthorizationFilterContext) : void
}
Attribute <|-- RequestFormSizeLimitAttribute
IAuthorizationFilter <|-- RequestFormSizeLimitAttribute
IOrderedFilter <|-- RequestFormSizeLimitAttribute
@enduml
