@startuml
class "BaseRestApiController`3"<TDbContext,TModel,TView> {
    + <<virtual>> <<async>> Get() : Task<ActionResult<PaginationModel<TView>>>
    + <<async>> Get(id:string) : Task<ActionResult<TView>>
    + <<async>> Create(data:TView) : Task<ActionResult<TModel>>
    + <<async>> Update(id:string, data:TView) : Task<IActionResult>
    + <<async>> Patch(id:string, fields:JObject) : Task<IActionResult>
    + <<async>> Delete(id:string) : Task<ActionResult<TModel>>
}
class "ViewModelBase`3"<T1,T2,T3> {
}
Controller <|-- "BaseRestApiController`3"
@enduml
