@startuml
class ClaimRequirement {
    + ClaimRequirement(claimName:string, claimValue:string)
    + ClaimName : string <<get>> <<set>>
    + ClaimValue : string <<get>> <<set>>
}
IAuthorizationRequirement <|-- ClaimRequirement
@enduml
