@startuml
class ReadMvcViewModel {
    + ReadMvcViewModel(model:MixRelatedAttributeSet, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + ReadMvcViewModel()
    + Id : int <<get>> <<set>>
    + AttributeSetId : int <<get>> <<set>>
    + ParentId : int <<get>> <<set>>
    + ParentType : MixDatabaseParentType <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + AttributeSet : MixAttributeSets.ReadMvcViewModel <<get>> <<set>>
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
"ViewModelBase`3" "<MixCmsContext,MixRelatedAttributeSet,ReadMvcViewModel>" <|-- ReadMvcViewModel
@enduml
