@startuml
class InitViewModel {
    + Id : int <<get>> <<set>>
    + ThemeId : int <<get>> <<set>>
    + ThemeName : string <<get>> <<set>>
    + FolderType : string <<get>> <<set>>
    + FileFolder : string <<get>> <<set>>
    + FileName : string <<get>> <<set>>
    + Extension : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + MobileContent : string <<get>> <<set>> = "{}"
    + SpaContent : string <<get>> <<set>> = ""
    + Scripts : string <<get>> <<set>>
    + Styles : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Layout : string <<get>> <<set>>
    + AssetFolder : string <<get>>
    + TemplateFolder : string <<get>>
    + TemplatePath : string <<get>>
    + InitViewModel()
    + InitViewModel(model:MixTemplate, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixTemplate
    + <<override>> RemoveModel(isRemoveRelatedModels:bool, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<MixTemplate>
    + <<override>> SaveSubModels(parent:MixTemplate, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<bool>
    + <<override>> <<async>> RemoveModelAsync(isRemoveRelatedModels:bool, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<MixTemplate>>
    + <<override>> SaveSubModelsAsync(parent:MixTemplate, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixCmsContext,MixTemplate,InitViewModel>" <|-- InitViewModel
InitViewModel --> "CreatedDateTime" DateTime
InitViewModel --> "Status" MixContentStatus
@enduml
