@startuml
class ReadMvcViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Cultures : List<Domain.Core.Models.SupportedCulture> <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + FormTemplate : string <<get>> <<set>>
    + EdmTemplate : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Fields : string <<get>> <<set>>
    + Type : MixModuleType <<get>> <<set>>
    + PageSize : int? <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + Domain : string <<get>>
    + DetailsUrl : string <<get>> <<set>>
    + ImageUrl : string <<get>>
    + ThumbnailUrl : string <<get>>
    + Columns : List<ModuleFieldViewModel> <<get>> <<set>>
    + View : MixTemplates.ReadListItemViewModel <<get>> <<set>>
    + FormView : MixTemplates.ReadListItemViewModel <<get>> <<set>>
    + EdmView : MixTemplates.ReadListItemViewModel <<get>> <<set>>
    + Data : PaginationModel<ViewModels.MixModuleDatas.ReadViewModel> <<get>> <<set>>
    + Posts : PaginationModel<MixModulePosts.ReadViewModel> <<get>> <<set>>
    + TemplatePath : string <<get>>
    + FormTemplatePath : string <<get>>
    + EdmTemplatePath : string <<get>>
    + AttributeData : MixRelatedAttributeDatas.ReadMvcViewModel <<get>> <<set>>
    + PostId : int? <<get>> <<set>>
    + PageId : int? <<get>> <<set>>
    + ReadMvcViewModel()
    + ReadMvcViewModel(model:MixModule, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    - LoadAttributes(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + {static} GetBy(predicate:Expression<Func<MixModule, bool>>, postId:int?, productid:int?, pageId:int, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<ReadMvcViewModel>
    + LoadData(postId:int?, productId:int?, pageId:int?, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + HasValue(fieldName:string) : bool
    + Property(fieldName:string) : T
}
"ViewModelBase`3" "<MixCmsContext,MixModule,ReadMvcViewModel>" <|-- ReadMvcViewModel
@enduml
