@startuml
class ApiRelatedAttributeSetPortalController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<ReadMvcViewModel>>>
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixRelatedAttributeSet,UpdateViewModel,ReadMvcViewModel,DeleteViewModel>" <|-- ApiRelatedAttributeSetPortalController
@enduml
