@startuml
class ApiPageController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<ReadViewModel>>>
}
class "BaseAuthorizedRestApiController`5"<T1,T2,T3,T4,T5> {
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixPage,UpdateViewModel,ReadViewModel,DeleteViewModel>" <|-- ApiPageController
@enduml
