@startuml
class QueryRequest {
    + OperationName : string <<get>> <<set>>
    + NamedQuery : string <<get>> <<set>>
    + Query : string <<get>> <<set>>
}
QueryRequest --> "Variables" JObject
@enduml
