@startuml
class TableMetadata {
    + TableName : string <<get>> <<set>>
    + AssemblyFullName : string <<get>> <<set>>
}
class "IEnumerable`1"<T> {
}
TableMetadata --> "Columns<ColumnMetadata>" "IEnumerable`1"
@enduml
