@startuml
class ExpressionModel {
    + {static} Create(expressType:MixLogicalOperatorKind) : ExpressionModel
    + AddFunction(function:FunctionModel) : ExpressionModel
    + AddExpression(expression:ExpressionModel) : ExpressionModel
}
class "List`1"<T> {
}
ExpressionModel --> "ExpressionType" MixLogicalOperatorKind
ExpressionModel --> "Functions<FunctionModel>" "List`1"
ExpressionModel --> "Expressions<ExpressionModel>" "List`1"
@enduml
