@startuml
class DeleteViewModel {
    + Id : string <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + DataId : string <<get>> <<set>>
    + ParentId : string <<get>> <<set>>
    + ParentType : MixDatabaseParentType <<get>> <<set>>
    + AttributeSetId : int <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + Status : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + DeleteViewModel()
    + DeleteViewModel(model:MixRelatedAttributeData, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixRelatedAttributeData
}
"ViewModelBase`3" "<MixCmsContext,MixRelatedAttributeData,DeleteViewModel>" <|-- DeleteViewModel
@enduml
