@startuml
class Helper {
    + {static} <<async>> RemoveRelatedDataAsync(parentId:string, parentType:MixDatabaseParentType, specificulture:string, context:MixCmsContext, transaction:IDbContextTransaction) : Task<RepositoryResponse<List<MixRelatedAttributeData>>>
}
@enduml
