@startuml
class MsSqlMixCmsContext <<partial>> {
    + MsSqlMixCmsContext()
    # <<override>> OnModelCreating(modelBuilder:ModelBuilder) : void
    <<partial>> OnModelCreatingPartial(modelBuilder:ModelBuilder) : void
}
MixCmsContext <|-- MsSqlMixCmsContext
@enduml
