@startuml
class Aspnetusertokens <<partial>> {
    + UserId : string <<get>> <<set>>
    + LoginProvider : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Value : string <<get>> <<set>>
    + <<virtual>> User : Aspnetusers <<get>> <<set>>
}
@enduml
