@startuml
class Aspnetroles <<partial>> {
    + Aspnetroles()
    + Id : string <<get>> <<set>>
    + ConcurrencyStamp : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + NormalizedName : string <<get>> <<set>>
    + <<virtual>> Aspnetroleclaims : ICollection<Aspnetroleclaims> <<get>> <<set>>
    + <<virtual>> Aspnetuserroles : ICollection<Aspnetuserroles> <<get>> <<set>>
}
@enduml
