@startuml
class MixAttributeSetData <<partial>> {
    + Id : string <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + AttributeSetId : int <<get>> <<set>>
    + AttributeSetName : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + <<virtual>> AttributeSet : MixAttributeSet <<get>> <<set>>
}
@enduml
