@startuml
class MixMessengerUser <<partial>> {
    + MixMessengerUser()
    + Id : string <<get>> <<set>>
    + FacebookId : string <<get>> <<set>>
    + Avatar : string <<get>> <<set>>
    + CreatedDate : DateTime <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Status : int <<get>> <<set>>
    + <<virtual>> MixMessengerMessage : ICollection<MixMessengerMessage> <<get>> <<set>>
    + <<virtual>> MixMessengerNavRoomUser : ICollection<MixMessengerNavRoomUser> <<get>> <<set>>
    + <<virtual>> MixMessengerNavTeamUser : ICollection<MixMessengerNavTeamUser> <<get>> <<set>>
}
@enduml
