@startuml
class MixMessengerMessage <<partial>> {
    + Id : Guid <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + CreatedDate : DateTime <<get>> <<set>>
    + RoomId : Guid? <<get>> <<set>>
    + TeamId : int? <<get>> <<set>>
    + UserId : string <<get>> <<set>>
    + <<virtual>> Room : MixMessengerHubRoom <<get>> <<set>>
    + <<virtual>> Team : MixMessengerTeam <<get>> <<set>>
    + <<virtual>> User : MixMessengerUser <<get>> <<set>>
}
@enduml
