@startuml
class MixModule <<partial>> {
    + MixModule()
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Fields : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + FormTemplate : string <<get>> <<set>>
    + EdmTemplate : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Type : int <<get>> <<set>>
    + PostType : string <<get>> <<set>>
    + PageSize : int? <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + <<virtual>> SpecificultureNavigation : MixCulture <<get>> <<set>>
    + <<virtual>> MixModuleData : ICollection<MixModuleData> <<get>> <<set>>
    + <<virtual>> MixModulePost : ICollection<MixModulePost> <<get>> <<set>>
    + <<virtual>> MixPageModule : ICollection<MixPageModule> <<get>> <<set>>
    + <<virtual>> MixPostModule : ICollection<MixPostModule> <<get>> <<set>>
}
@enduml
