@startuml
class MixPortalPage <<partial>> {
    + MixPortalPage()
    + Id : int <<get>> <<set>>
    + Icon : string <<get>> <<set>>
    + TextKeyword : string <<get>> <<set>>
    + Url : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + TextDefault : string <<get>> <<set>>
    + Level : int <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + <<virtual>> MixPortalPageNavigationPage : ICollection<MixPortalPageNavigation> <<get>> <<set>>
    + <<virtual>> MixPortalPageNavigationParent : ICollection<MixPortalPageNavigation> <<get>> <<set>>
    + <<virtual>> MixPortalPageRole : ICollection<MixPortalPageRole> <<get>> <<set>>
}
@enduml
