@startuml
class ApplicationUser {
    + JoinDate : DateTime <<get>> <<set>>
    + IsActived : bool <<get>> <<set>>
    + LastModified : System.DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + RegisterType : string <<get>> <<set>>
    + Avatar : string <<get>> <<set>>
    + NickName : string <<get>> <<set>>
    + FirstName : string <<get>> <<set>>
    + LastName : string <<get>> <<set>>
    + Gender : string <<get>> <<set>>
    + CountryId : int <<get>> <<set>>
    + Culture : string <<get>> <<set>>
    + DOB : DateTime? <<get>> <<set>>
    + <<virtual>> Roles : ICollection<IdentityUserRole<string>> <<get>>
    + <<virtual>> Claims : ICollection<IdentityUserClaim<string>> <<get>>
    + <<virtual>> Logins : ICollection<IdentityUserLogin<string>> <<get>>
}
IdentityUser <|-- ApplicationUser
@enduml
