@startuml
class MixMediaConfiguration {
    + Configure(entity:EntityTypeBuilder<MixMedia>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixMedia>" <|-- MixMediaConfiguration
@enduml
