@startuml
class MixPagePostConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPagePost>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixPagePost>" <|-- MixPagePostConfiguration
@enduml
