@startuml
class MixUrlAliasConfiguration {
    + Configure(entity:EntityTypeBuilder<MixUrlAlias>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixUrlAlias>" <|-- MixUrlAliasConfiguration
@enduml
