@startuml
class ReadViewModel {
    + Id : string <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + AttributeSetId : int <<get>> <<set>>
    + AttributeSetName : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + Status : string <<get>> <<set>>
    + ReadViewModel()
    + ReadViewModel(model:MixAttributeSetData, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixAttributeSetData,ReadViewModel>" <|-- ReadViewModel
ReadViewModel --> "CreatedDateTime" DateTime
ReadViewModel --> "Data" JObject
ReadViewModel --> "Connection" MessengerConnection
ReadViewModel o-> "RelatedData<Lib.ViewModels.MixRelatedAttributeDatas.UpdateViewModel>" "List`1"
ReadViewModel --> "Values<Lib.ViewModels.MixAttributeSetValues.UpdateViewModel>" "List`1"
ReadViewModel --> "Fields<Lib.ViewModels.MixAttributeFields.UpdateViewModel>" "List`1"
ReadViewModel o-> "RefData<MixAttributeSetDatas.FormViewModel>" "List`1"
@enduml
