@startuml
class ReadAndroidViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Cultures : List<Domain.Core.Models.SupportedCulture> <<get>> <<set>>
    + Keyword : string <<get>> <<set>>
    + DataType : MixDataType <<get>> <<set>>
    + Value : string <<get>> <<set>>
    + DefaultValue : string <<get>> <<set>>
    + ReadAndroidViewModel()
    + ReadAndroidViewModel(model:MixLanguage, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> RemoveRelatedModels(view:ReadAndroidViewModel, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<bool>
    + <<override>> <<async>> RemoveRelatedModelsAsync(view:ReadAndroidViewModel, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    + {static} <<async>> ImportLanguages(arrLanguage:List<MixLanguage>, destCulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
}
"ViewModelBase`3" "<MixCmsContext,MixLanguage,ReadAndroidViewModel>" <|-- ReadAndroidViewModel
@enduml
