@startuml
class MixAttributeSetConfiguration {
    + Configure(entity:EntityTypeBuilder<MixAttributeSet>) : void
}
"IEntityTypeConfiguration`1" "<MixAttributeSet>" <|-- MixAttributeSetConfiguration
@enduml
