@startuml
class UpdateViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Cultures : List<Domain.Core.Models.SupportedCulture> <<get>> <<set>>
    + SourceId : string <<get>> <<set>>
    + Type : MixUrlAliasType <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Alias : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + UpdateViewModel()
    + UpdateViewModel(model:MixUrlAlias, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixUrlAlias
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + <<override>> Validate(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    - LoadCultures(initCulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : List<SupportedCulture>
}
"ViewModelBase`3" "<MixCmsContext,MixUrlAlias,UpdateViewModel>" <|-- UpdateViewModel
@enduml
