@startuml
class PostgresSQLAccountContextModelSnapshot <<partial>> {
    # <<override>> BuildModel(modelBuilder:ModelBuilder) : void
}
ModelSnapshot <|-- PostgresSQLAccountContextModelSnapshot
@enduml
