@startuml
class TemplateRepository {
    + GetTemplate(templatePath:string, templates:List<TemplateViewModel>, templateFolder:string) : TemplateViewModel
    + GetTemplate(name:string, templateFolder:string) : TemplateViewModel
    + DeleteTemplate(name:string, templateFolder:string) : bool
    + GetTemplates(folder:string) : List<TemplateViewModel>
    + SaveTemplate(file:TemplateViewModel) : bool
}
TemplateRepository --> "Instance" TemplateRepository
@enduml
