@startuml
class MessengerConnection {
    + Id : string <<get>> <<set>>
    + ConnectionId : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Avatar : string <<get>> <<set>>
    + DeviceId : string <<get>> <<set>>
}
class HubMessage {
    + Connection : MessengerConnection <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + CreatedDate : DateTime <<get>> <<set>>
}
@enduml
