@startuml
class "HubRequest`1"<T> {
    + Uid : string <<get>> <<set>>
    + Connection : MessengerConnection <<get>> <<set>>
    + From : string <<get>> <<set>>
    + To : string <<get>> <<set>>
    + AttributeSetName : string <<get>> <<set>>
    + Action : string <<get>> <<set>>
    + Data : T <<get>> <<set>>
    + RequestDate : DateTime <<get>>
    + Room : string <<get>> <<set>>
    + IsMySelf : bool <<get>> <<set>>
    + IsSave : bool <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
}
@enduml
