@startuml
class "HubResponse`1"<T> {
    + IsSucceed : bool <<get>> <<set>>
    + ResponseKey : string <<get>> <<set>>
    + Errors : List<string> <<get>> <<set>>
    + Exception : Exception <<get>> <<set>>
    + Data : T <<get>> <<set>>
    + RenderDate : DateTime <<get>>
}
@enduml
