@startuml
enum MixDataType {
    Custom,
    DateTime,
    Date,
    Time,
    Duration,
    PhoneNumber,
    Double,
    Text,
    Html,
    MultilineText,
    EmailAddress,
    Password,
    Url,
    ImageUrl,
    CreditCard,
    PostalCode,
    Upload,
    Color,
    Boolean,
    Icon,
    VideoYoutube,
    TuiEditor,
    Integer,
    Reference,
    QRCode,
}
@enduml
