@startuml
class ApiPageController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<ReadViewModel>>>
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixPage,UpdateViewModel,ReadViewModel,DeleteViewModel>" <|-- ApiPageController
@enduml
