@startuml
class ApiAttributeFieldController {
    + ApiAttributeFieldController(context:MixCmsContext, memoryCache:IMemoryCache, hubContext:Microsoft.AspNetCore.SignalR.IHubContext<Mix.Cms.Service.SignalR.Hubs.PortalHub>)
    + <<async>> DeleteAsync(id:int) : Task<RepositoryResponse<MixAttributeField>>
    + <<async>> Details(viewType:string, id:int?) : Task<ActionResult<JObject>>
    + <<async>> InitByName(setId:int) : Task<RepositoryResponse<List<UpdateViewModel>>>
    + <<async>> Save(data:UpdateViewModel) : Task<RepositoryResponse<UpdateViewModel>>
    + <<async>> GetList(request:RequestPaging) : Task<ActionResult<JObject>>
}
class "BaseGenericApiController`2"<T1,T2> {
}
"BaseGenericApiController`2" "<MixCmsContext,MixAttributeField>" <|-- ApiAttributeFieldController
@enduml
