@startuml
class ApiModulePostController {
    + ApiModulePostController(context:MixCmsContext, memoryCache:IMemoryCache, hubContext:Microsoft.AspNetCore.SignalR.IHubContext<Mix.Cms.Service.SignalR.Hubs.PortalHub>)
    + <<async>> DeleteAsync(moduleId:int, postId:int) : Task<RepositoryResponse<MixModulePost>>
    + <<async>> Details(viewType:string, moduleId:int?, postId:int?) : Task<ActionResult<JObject>>
    + <<async>> Save(model:ReadViewModel) : Task<RepositoryResponse<ReadViewModel>>
    + <<async>> SaveFields(moduleId:int, postId:int, fields:List<EntityField>) : Task<RepositoryResponse<MixModulePost>>
    + <<async>> GetList(request:RequestPaging) : Task<ActionResult<JObject>>
    + <<async>> UpdateInfos(models:List<ReadViewModel>) : Task<RepositoryResponse<List<ReadViewModel>>>
    + <<async>> SaveList(models:List<ReadViewModel>) : Task<RepositoryResponse<List<ReadViewModel>>>
}
class "BaseGenericApiController`2"<T1,T2> {
}
"BaseGenericApiController`2" "<MixCmsContext,MixModulePost>" <|-- ApiModulePostController
@enduml
