@startuml
class ApiModuleDataDataController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<UpdateViewModel>>>
    + <<async>> Export() : Task<ActionResult<FileViewModel>>
    + <<async>> InitByIdAsync(moduleId:int) : Task<ActionResult<UpdateViewModel>>
    + <<async>> SaveByName(moduleName:string, data:JObject) : Task<RepositoryResponse<UpdateViewModel>>
}
class "BaseAuthorizedRestApiController`5"<T1,T2,T3,T4,T5> {
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixModuleData,UpdateViewModel,UpdateViewModel,UpdateViewModel>" <|-- ApiModuleDataDataController
@enduml
