@startuml
class DbContextExtensions <<static>> {
    + {static} Query(context:DbContext, entityName:string) : IQueryable
    {static} <<readonly>> SetMethod : MethodInfo
    + {static} Query(context:DbContext, entityType:Type) : IQueryable
}
@enduml
