@startuml
class Aspnetuserclaims <<partial>> {
    + Id : int <<get>> <<set>>
    + ApplicationUserId : string <<get>> <<set>>
    + ClaimType : string <<get>> <<set>>
    + ClaimValue : string <<get>> <<set>>
    + UserId : string <<get>> <<set>>
}
Aspnetuserclaims --> "ApplicationUser" Aspnetusers
Aspnetuserclaims --> "User" Aspnetusers
@enduml
