@startuml
class Aspnetroleclaims <<partial>> {
    + Id : int <<get>> <<set>>
    + ClaimType : string <<get>> <<set>>
    + ClaimValue : string <<get>> <<set>>
    + RoleId : string <<get>> <<set>>
}
Aspnetroleclaims --> "Role" Aspnetroles
@enduml
