@startuml
class Aspnetuserlogins <<partial>> {
    + LoginProvider : string <<get>> <<set>>
    + ProviderKey : string <<get>> <<set>>
    + ApplicationUserId : string <<get>> <<set>>
    + ProviderDisplayName : string <<get>> <<set>>
    + UserId : string <<get>> <<set>>
}
Aspnetuserlogins --> "ApplicationUser" Aspnetusers
Aspnetuserlogins --> "User" Aspnetusers
@enduml
