@startuml
class MixAttributeSet <<partial>> {
    + MixAttributeSet()
    + Id : int <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + FormTemplate : string <<get>> <<set>>
    + EdmTemplate : string <<get>> <<set>>
    + EdmSubject : string <<get>> <<set>>
    + EdmFrom : string <<get>> <<set>>
    + EdmAutoSend : bool? <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
}
MixAttributeSet --> "Type" MixDatabaseType
MixAttributeSet --> "CreatedDateTime" DateTime
MixAttributeSet --> "Status" MixContentStatus
@enduml
