@startuml
class MixAttributeSetReference <<partial>> {
    + Id : int <<get>> <<set>>
    + ParentId : int <<get>> <<set>>
    + ParentType : int <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + AttributeSetId : int <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
}
MixAttributeSetReference --> "CreatedDateTime" DateTime
MixAttributeSetReference --> "Status" MixContentStatus
MixAttributeSetReference --> "AttributeSet" MixAttributeSet
@enduml
