@startuml
class MixLanguage <<partial>> {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Keyword : string <<get>> <<set>>
    + Category : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Value : string <<get>> <<set>>
    + DefaultValue : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
}
MixLanguage --> "DataType" MixDataType
MixLanguage --> "CreatedDateTime" DateTime
MixLanguage --> "Status" MixContentStatus
MixLanguage --> "SpecificultureNavigation" MixCulture
@enduml
