@startuml
class MixPage <<partial>> {
    + MixPage()
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + CssClass : string <<get>> <<set>>
    + Excerpt : string <<get>> <<set>>
    + Icon : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Layout : string <<get>> <<set>>
    + Level : int? <<get>> <<set>>
    + SeoDescription : string <<get>> <<set>>
    + SeoKeywords : string <<get>> <<set>>
    + SeoName : string <<get>> <<set>>
    + SeoTitle : string <<get>> <<set>>
    + StaticUrl : string <<get>> <<set>>
    + Tags : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + PostType : string <<get>> <<set>>
    + Views : int? <<get>> <<set>>
    + PageSize : int? <<get>> <<set>>
    + ExtraFields : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
}
class "ICollection`1"<T> {
}
MixPage --> "Type" MixPageType
MixPage --> "CreatedDateTime" DateTime
MixPage --> "Status" MixContentStatus
MixPage --> "SpecificultureNavigation" MixCulture
MixPage --> "MixModuleData<MixModuleData>" "ICollection`1"
MixPage --> "MixPageModule<MixPageModule>" "ICollection`1"
MixPage --> "MixPagePost<MixPagePost>" "ICollection`1"
@enduml
