@startuml
class MixPostMedia <<partial>> {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + MediaId : int <<get>> <<set>>
    + PostId : int <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Position : int <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
}
MixPostMedia --> "CreatedDateTime" DateTime
MixPostMedia --> "Status" MixContentStatus
MixPostMedia --> "MixMedia" MixMedia
MixPostMedia --> "MixPost" MixPost
@enduml
