@startuml
class MixRelatedData <<partial>> {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + DataId : string <<get>> <<set>>
    + Type : int <<get>> <<set>>
    + ParentId : string <<get>> <<set>>
    + ParentType : string <<get>> <<set>>
    + AttributeSetId : int <<get>> <<set>>
    + AttributeSetName : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
}
MixRelatedData --> "CreatedDateTime" DateTime
MixRelatedData --> "Status" MixContentStatus
@enduml
