@startuml
class GraphqlController {
    - {static} <<readonly>> graphQLSchema : Schema
    {static} GraphqlController()
    + <<async>> Get(query:QueryRequest) : Task<ActionResult>
}
ControllerBase <|-- GraphqlController
@enduml
