@startuml
class DeleteViewModel {
    + Id : int <<get>> <<set>>
    + ReferenceId : int? <<get>> <<set>>
    + DeleteViewModel()
    + DeleteViewModel(model:MixAttributeSet, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> RemoveRelatedModels(view:DeleteViewModel, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<bool>
    + <<override>> <<async>> RemoveRelatedModelsAsync(view:DeleteViewModel, _context:MixCmsContext, _transaction:IDbContextTransaction) : System.Threading.Tasks.Task<RepositoryResponse<bool>>
}
"ViewModelBase`3" "<MixCmsContext,MixAttributeSet,DeleteViewModel>" <|-- DeleteViewModel
@enduml
