@startuml
class "BaseAuthorizedRestApiController`5"<TDbContext,TModel,TView,TRead,TDelete> {
    + <<virtual>> <<async>> Get() : Task<ActionResult<PaginationModel<TRead>>>
    + <<async>> Get(id:string) : Task<ActionResult<TView>>
    + <<async>> Duplicate(id:string) : Task<ActionResult<TView>>
    + <<virtual>> Default() : ActionResult<TView>
    + <<virtual>> <<async>> ClearCacheAsync(id:string) : Task<ActionResult>
    + <<virtual>> <<async>> ClearCacheAsync() : Task<ActionResult>
    + <<virtual>> <<async>> Create(data:TView) : Task<ActionResult<TModel>>
    + <<virtual>> <<async>> Update(id:string, data:TView) : Task<IActionResult>
    + <<virtual>> <<async>> Patch(id:string, fields:JObject) : Task<IActionResult>
    + <<virtual>> <<async>> Delete(id:string) : Task<ActionResult<TModel>>
    + <<async>> ListActionAsync(data:ListAction<string>) : Task<ActionResult<JObject>>
    + <<override>> OnActionExecuting(context:ActionExecutingContext) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
Controller <|-- "BaseAuthorizedRestApiController`5"
@enduml
