@startuml
class MixAttributeSetValueConfiguration {
    + Configure(entity:EntityTypeBuilder<MixAttributeSetValue>) : void
}
"IEntityTypeConfiguration`1" "<MixAttributeSetValue>" <|-- MixAttributeSetValueConfiguration
@enduml
