@startuml
class MixCmsAccountContext <<partial>> {
    + <<virtual>> AspNetRoleClaims : DbSet<AspNetRoleClaims> <<get>> <<set>>
    + <<virtual>> AspNetRoles : DbSet<AspNetRoles> <<get>> <<set>>
    + <<virtual>> AspNetUserClaims : DbSet<AspNetUserClaims> <<get>> <<set>>
    + <<virtual>> AspNetUserLogins : DbSet<AspNetUserLogins> <<get>> <<set>>
    + <<virtual>> AspNetUserRoles : DbSet<AspNetUserRoles> <<get>> <<set>>
    + <<virtual>> AspNetUsers : DbSet<AspNetUsers> <<get>> <<set>>
    + <<virtual>> AspNetUserTokens : DbSet<AspNetUserTokens> <<get>> <<set>>
    + <<virtual>> Clients : DbSet<Clients> <<get>> <<set>>
    + <<virtual>> RefreshTokens : DbSet<RefreshTokens> <<get>> <<set>>
    + MixCmsAccountContext(options:DbContextOptions<ApplicationDbContext>)
    + MixCmsAccountContext()
    # <<override>> OnConfiguring(optionsBuilder:DbContextOptionsBuilder) : void
    + <<override>> Dispose() : void
    # <<override>> OnModelCreating(modelBuilder:ModelBuilder) : void
    <<partial>> OnModelCreatingPartial(modelBuilder:ModelBuilder) : void
}
DbContext <|-- MixCmsAccountContext
@enduml
