@startuml
class MixDbContext {
    + MixDbContext(options:DbContextOptions<MixDbContext>)
    + MixDbContext()
    + Clients : DbSet<Client> <<get>> <<set>>
    + RefreshTokens : DbSet<RefreshToken> <<get>> <<set>>
    # <<override>> OnModelCreating(builder:ModelBuilder) : void
    # <<override>> OnConfiguring(optionsBuilder:DbContextOptionsBuilder) : void
    + <<override>> Dispose() : void
}
"IdentityDbContext`1" "<ApplicationUser>" <|-- MixDbContext
@enduml
