@startuml
class AspNetUsers <<partial>> {
    + AspNetUsers()
    + Id : string <<get>> <<set>>
    + AccessFailedCount : int <<get>> <<set>>
    + Avatar : string <<get>> <<set>>
    + ConcurrencyStamp : string <<get>> <<set>>
    + CountryId : int <<get>> <<set>>
    + Culture : string <<get>> <<set>>
    + Dob : DateTime? <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + EmailConfirmed : bool <<get>> <<set>>
    + FirstName : string <<get>> <<set>>
    + Gender : string <<get>> <<set>>
    + IsActived : bool <<get>> <<set>>
    + JoinDate : DateTime <<get>> <<set>>
    + LastModified : DateTime <<get>> <<set>>
    + LastName : string <<get>> <<set>>
    + LockoutEnabled : bool <<get>> <<set>>
    + LockoutEnd : DateTime? <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + NickName : string <<get>> <<set>>
    + NormalizedEmail : string <<get>> <<set>>
    + NormalizedUserName : string <<get>> <<set>>
    + PasswordHash : string <<get>> <<set>>
    + PhoneNumber : string <<get>> <<set>>
    + PhoneNumberConfirmed : bool <<get>> <<set>>
    + RegisterType : string <<get>> <<set>>
    + SecurityStamp : string <<get>> <<set>>
    + TwoFactorEnabled : bool <<get>> <<set>>
    + UserName : string <<get>> <<set>>
    + <<virtual>> AspNetUserClaimsApplicationUser : ICollection<AspNetUserClaims> <<get>> <<set>>
    + <<virtual>> AspNetUserClaimsUser : ICollection<AspNetUserClaims> <<get>> <<set>>
    + <<virtual>> AspNetUserLoginsApplicationUser : ICollection<AspNetUserLogins> <<get>> <<set>>
    + <<virtual>> AspNetUserLoginsUser : ICollection<AspNetUserLogins> <<get>> <<set>>
    + <<virtual>> AspNetUserRolesApplicationUser : ICollection<AspNetUserRoles> <<get>> <<set>>
    + <<virtual>> AspNetUserRolesUser : ICollection<AspNetUserRoles> <<get>> <<set>>
    + <<virtual>> AspNetUserTokens : ICollection<AspNetUserTokens> <<get>> <<set>>
}
@enduml
