@startuml
class AspNetUserTokens <<partial>> {
    + UserId : string <<get>> <<set>>
    + LoginProvider : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Value : string <<get>> <<set>>
    + <<virtual>> User : AspNetUsers <<get>> <<set>>
}
@enduml
