@startuml
class RefreshTokens <<partial>> {
    + Id : string <<get>> <<set>>
    + ClientId : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + Username : string <<get>> <<set>>
    + ExpiresUtc : DateTime <<get>> <<set>>
    + IssuedUtc : DateTime <<get>> <<set>>
}
@enduml
