@startuml
class MixAttributeSetReferenceConfiguration {
    + Configure(entity:EntityTypeBuilder<MixAttributeSetReference>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixAttributeSetReference>" <|-- MixAttributeSetReferenceConfiguration
@enduml
