@startuml
class MixPortalPageNavigationConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPortalPageNavigation>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixPortalPageNavigation>" <|-- MixPortalPageNavigationConfiguration
@enduml
