@startuml
class MixPortalPageConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPortalPage>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixPortalPage>" <|-- MixPortalPageConfiguration
@enduml
