@startuml
class RefreshToken {
    + Id : string <<get>> <<set>>
    + ClientId : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
}
RefreshToken --> "IssuedUtc" DateTime
RefreshToken --> "ExpiresUtc" DateTime
@enduml
