@startuml
class AspNetUser {
    + AspNetUser(accessor:IHttpContextAccessor)
    + Name : string <<get>>
    + IsAuthenticated() : bool
    + GetClaimsIdentity() : IEnumerable<Claim>
}
IUser <|-- AspNetUser
@enduml
