@startuml
class ReadMvcViewModel {
    + ReadMvcViewModel(model:MixModulePost, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + ReadMvcViewModel()
    + Specificulture : string <<get>> <<set>>
    + PostId : int <<get>> <<set>>
    + ModuleId : int <<get>> <<set>>
    + IsActived : bool <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + {static} GetModulePostNavAsync(postId:int, specificulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<List<MixModulePosts.ReadViewModel>>
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixCmsContext,MixModulePost,ReadMvcViewModel>" <|-- ReadMvcViewModel
ReadMvcViewModel --> "CreatedDateTime" DateTime
ReadMvcViewModel --> "Status" MixContentStatus
@enduml
