@startuml
class SystemLanguageViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Keyword : string <<get>> <<set>>
    + Category : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Value : string <<get>> <<set>>
    + DefaultValue : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + SystemLanguageViewModel()
    + SystemLanguageViewModel(model:MixLanguage, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + {static} <<async>> ImportLanguages(arrLanguage:List<MixLanguage>, destCulture:string) : Task<RepositoryResponse<bool>>
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixLanguage,SystemLanguageViewModel>" <|-- SystemLanguageViewModel
SystemLanguageViewModel --> "Cultures<SupportedCulture>" "List`1"
SystemLanguageViewModel --> "DataType" MixDataType
SystemLanguageViewModel --> "CreatedDateTime" DateTime
SystemLanguageViewModel --> "Status" MixContentStatus
@enduml
