@startuml
class Client {
    + Id : string <<get>> <<set>>
    + Secret : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + ApplicationType : ApplicationTypes <<get>> <<set>>
    + Active : bool <<get>> <<set>>
    + RefreshTokenLifeTime : int <<get>> <<set>>
    + AllowedOrigin : string <<get>> <<set>>
}
@enduml
