@startuml
class ApiPortalPageNavigationPortalController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<ReadViewModel>>>
}
class "BaseAuthorizedRestApiController`4"<T1,T2,T3,T4> {
}
"BaseAuthorizedRestApiController`4" "<MixCmsContext,MixPortalPageNavigation,UpdateViewModel,ReadViewModel>" <|-- ApiPortalPageNavigationPortalController
@enduml
