@startuml
class AccessTokenViewModel {
    + Access_token : string <<get>> <<set>>
    + Token_type : string <<get>> <<set>>
    + Refresh_token : string <<get>> <<set>>
    + Expires_in : int <<get>> <<set>>
    + Client_id : string <<get>> <<set>>
    + Issued : DateTime <<get>> <<set>>
    + Expires : DateTime <<get>> <<set>>
    + DeviceId : string <<get>> <<set>>
    + UserData : UserInfoViewModel <<get>> <<set>>
    + LastUpdateConfiguration : DateTime? <<get>> <<set>>
}
@enduml
