@startuml
class MixRegisterViewModel {
    + Id : string <<get>> <<set>>
    + Username : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + FirstName : string <<get>> <<set>>
    + MiddleName : string <<get>> <<set>>
    + LastName : string <<get>> <<set>>
    + Avatar : string <<get>> <<set>>
    + Address : string <<get>> <<set>>
    + PhoneNumber : string <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixUserStatus <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
    + DetailsUrl : string <<get>> <<set>>
    + UserRoles : List<NavUserRoleViewModel> <<get>> <<set>>
    + Domain : string <<get>>
    + AvatarUrl : string <<get>>
    + MediaFile : FileViewModel <<get>> <<set>>
    + MixRegisterViewModel()
    + MixRegisterViewModel(model:MixCmsUser, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixCmsUser
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + GetRoleNavs() : List<NavUserRoleViewModel>
}
"ViewModelBase`3" "<MixCmsContext,MixCmsUser,MixRegisterViewModel>" <|-- MixRegisterViewModel
@enduml
