@startuml
class NavUserRoleViewModel {
    + Specificulture : string <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + UserId : string <<get>> <<set>>
    + RoleId : string <<get>> <<set>>
    + ApplicationUserId : string <<get>> <<set>>
    + IsActived : bool <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Role : RoleViewModel <<get>> <<set>>
    + NavUserRoleViewModel()
    + NavUserRoleViewModel(model:AspNetUserRoles, _context:MixCmsAccountContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsAccountContext, _transaction:IDbContextTransaction) : void
}
"ViewModelBase`3" "<MixCmsAccountContext,AspNetUserRoles,NavUserRoleViewModel>" <|-- NavUserRoleViewModel
@enduml
