@startuml
class RoleViewModel {
    + Id : string <<get>> <<set>>
    + ConcurrencyStamp : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + NormalizedName : string <<get>> <<set>>
    + RoleViewModel()
    + RoleViewModel(model:AspNetRoles, _context:MixCmsAccountContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsAccountContext, _transaction:IDbContextTransaction) : AspNetRoles
    + <<override>> <<async>> RemoveRelatedModelsAsync(view:RoleViewModel, _context:MixCmsAccountContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
}
"ViewModelBase`3" "<MixCmsAccountContext,AspNetRoles,RoleViewModel>" <|-- RoleViewModel
@enduml
