@startuml
class ServiceCollectionExtensions <<static>> {
    + {static} AddMyGraphQL(services:IServiceCollection) : IServiceCollection
    + {static} AddGenerateApis(services:IServiceCollection) : IServiceCollection
}
@enduml
