@startuml
class ReadRolePermissionViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + TextKeyword : string <<get>> <<set>>
    + TextDefault : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Descriotion : string <<get>> <<set>>
    + Icon : string <<get>> <<set>>
    + Url : string <<get>> <<set>>
    + Level : int <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + ReadRolePermissionViewModel()
    + ReadRolePermissionViewModel(model:MixPortalPage, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixPortalPage,ReadRolePermissionViewModel>" <|-- ReadRolePermissionViewModel
ReadRolePermissionViewModel --> "CreatedDateTime" DateTime
ReadRolePermissionViewModel --> "Status" MixContentStatus
ReadRolePermissionViewModel o-> "ChildPages<MixPortalPagePortalPages.ReadPermissionViewModel>" "List`1"
@enduml
