@startuml
!include .\\Mix.Cms.Api\Program.puml
!include .\\Mix.Cms.Api\Startup.puml
!include .\\Mix.Cms.Api.GraphQL\Program.puml
!include .\\Mix.Cms.Api.GraphQL\ServiceCollectionExtensions.puml
!include .\\Mix.Cms.Api.GraphQL\Startup.puml
!include .\\Mix.Cms.Api.RestFul\Program.puml
!include .\\Mix.Cms.Api.RestFul\ServiceCollectionExtensions.puml
!include .\\Mix.Cms.Api.RestFul\Startup.puml
!include .\\Mix.Cms.Lib\MixCmsHelper.puml
!include .\\Mix.Cms.Lib\MixConstants.puml
!include .\\Mix.Cms.Schedule\ServiceCollectionExtensions.puml
!include .\\Mix.Cms.Service.SignalR\Constants.puml
!include .\\Mix.Cms.Service.SignalR\ServiceCollectionExtensions.puml
!include .\\Mix.Cms.Web\Program.puml
!include .\\Mix.Cms.Web\Startup.puml
!include .\\Mix.Identity\Const.puml
!include .\\Mix.Cms.Api\Helpers\IdentityHelper.puml
!include .\\Mix.Cms.Api.GraphQL\Controllers\GraphqlController.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\DbContextExtensions.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\GraphQLQuery.puml
!include .\\Mix.Cms.Lib\Attributes\RequestFormSizeLimitAttribute.puml
!include .\\Mix.Cms.Lib\Constants\MixAppSettingKeywords.puml
!include .\\Mix.Cms.Lib\Constants\MixConfigurations.puml
!include .\\Mix.Cms.Lib\Constants\MixDatabaseNames.puml
!include .\\Mix.Cms.Lib\Constants\MixDefaultThemes.puml
!include .\\Mix.Cms.Lib\Constants\MixDefaultValues.puml
!include .\\Mix.Cms.Lib\Constants\MixFileExtensions.puml
!include .\\Mix.Cms.Lib\Constants\MixFolders.puml
!include .\\Mix.Cms.Lib\Constants\MixTemplateFolders.puml
!include .\\Mix.Cms.Lib\Controllers\BaseReadOnlyApiController.puml
!include .\\Mix.Cms.Lib\Controllers\BaseRestApiController .puml
!include .\\Mix.Cms.Lib\Controllers\BaseRestWithCrudApiController.puml
!include .\\Mix.Cms.Lib\Controllers\BaseRestWithReadApiController.puml
!include .\\Mix.Cms.Lib\Enums\MixCalculateOperatorKind.puml
!include .\\Mix.Cms.Lib\Enums\MixCompareOperatorKind.puml
!include .\\Mix.Cms.Lib\Enums\MixContentStatus.puml
!include .\\Mix.Cms.Lib\Enums\MixDatabaseContentAssociationType.puml
!include .\\Mix.Cms.Lib\Enums\MixDatabaseParentType.puml
!include .\\Mix.Cms.Lib\Enums\MixDatabaseProvider.puml
!include .\\Mix.Cms.Lib\Enums\MixDatabaseType.puml
!include .\\Mix.Cms.Lib\Enums\MixDataType.puml
!include .\\Mix.Cms.Lib\Enums\MixExpressionRule.puml
!include .\\Mix.Cms.Lib\Enums\MixLogicalOperatorKind.puml
!include .\\Mix.Cms.Lib\Enums\MixModuleType.puml
!include .\\Mix.Cms.Lib\Enums\MixPageType.puml
!include .\\Mix.Cms.Lib\Enums\MixResponseKey.puml
!include .\\Mix.Cms.Lib\Enums\MixResponseStatus.puml
!include .\\Mix.Cms.Lib\Enums\MixStructureType.puml
!include .\\Mix.Cms.Lib\Enums\MixTemplateFolderType.puml
!include .\\Mix.Cms.Lib\Enums\MixUrlAliasType.puml
!include .\\Mix.Cms.Lib\Enums\MixUserStatus.puml
!include .\\Mix.Cms.Lib\Extensions\MixAttributeValueModelExtensions.puml
!include .\\Mix.Cms.Lib\Extensions\ModelBuilderExtensions.puml
!include .\\Mix.Cms.Lib\Extensions\ServiceCollectionExtensions.puml
!include .\\Mix.Cms.Lib\Extensions\UrlHelperExtensions.puml
!include .\\Mix.Cms.Lib\Helpers\MixAttributeSetValueHelper.puml
!include .\\Mix.Cms.Lib\Helpers\QueryFilterHelper.puml
!include .\\Mix.Cms.Lib\Interfaces\MvcViewModel.puml
!include .\\Mix.Cms.Lib\MiddleWares\IpRestrictionMiddleware.puml
!include .\\Mix.Cms.Lib\Models\ExpressionModel.puml
!include .\\Mix.Cms.Lib\Models\FunctionModel.puml
!include .\\Mix.Cms.Lib\Repositories\CommonRepository.puml
!include .\\Mix.Cms.Lib\Repositories\TemplateRepository.puml
!include .\\Mix.Cms.Lib\Services\InitCmsService.puml
!include .\\Mix.Cms.Lib\Services\MixCacheService.puml
!include .\\Mix.Cms.Lib\Services\MixService.puml
!include .\\Mix.Cms.Lib\ViewModels\CommonViewModels.puml
!include .\\Mix.Cms.Lib\ViewModels\DashboardViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\SiteStructureViewModel.puml
!include .\\Mix.Cms.Schedule\Jobs\PublishScheduledPostsJob.puml
!include .\\Mix.Cms.Service.SignalR\Hubs\BaseSignalRHub.puml
!include .\\Mix.Cms.Service.SignalR\Hubs\InitCmsHub.puml
!include .\\Mix.Cms.Service.SignalR\Hubs\MixChatHub.puml
!include .\\Mix.Cms.Service.SignalR\Hubs\PortalHub.puml
!include .\\Mix.Cms.Service.SignalR\Hubs\ServiceHub.puml
!include .\\Mix.Cms.Service.SignalR\Hubs\VideoChatHub.puml
!include .\\Mix.Cms.Service.SignalR\Models\HubModels.puml
!include .\\Mix.Cms.Service.SignalR\Models\HubRequest.puml
!include .\\Mix.Cms.Service.SignalR\Models\HubResponse.puml
!include .\\Mix.Cms.Web\App_Start\Startup.Auth.puml
!include .\\Mix.Cms.Web\App_Start\Startup.Route.puml
!include .\\Mix.Cms.Web\App_Start\Startup.SignalR.puml
!include .\\Mix.Cms.Web\Controllers\BaseController.puml
!include .\\Mix.Cms.Web\Controllers\DataController.puml
!include .\\Mix.Cms.Web\Controllers\HomeController.puml
!include .\\Mix.Cms.Web\Controllers\InitController.puml
!include .\\Mix.Cms.Web\Controllers\ModuleController.puml
!include .\\Mix.Cms.Web\Controllers\PageController.puml
!include .\\Mix.Cms.Web\Controllers\PortalController.puml
!include .\\Mix.Cms.Web\Controllers\PostController.puml
!include .\\Mix.Cms.Web\Controllers\SecurityController.puml
!include .\\Mix.Cms.Web\Controllers\VueController.puml
!include .\\Mix.Cms.Web\Models\ErrorViewModel.puml
!include .\\Mix.Cms.Web\Models\RewriteRules.puml
!include .\\Mix.Heart.NetCore\Attributes\GeneratedControllerAttribute.puml
!include .\\Mix.Heart.NetCore\Controllers\BaseRestApiController.puml
!include .\\Mix.Heart.NetCore\Conventions\GenericControllerRouteConvention.puml
!include .\\Mix.Heart.NetCore\Extensions\ServiceCollectionExtensions.puml
!include .\\Mix.Heart.NetCore\Providers\GenericTypeControllerFeatureProvider.puml
!include .\\Mix.Identity\Authorization\ClaimRequirement.puml
!include .\\Mix.Identity\Authorization\ClaimsRequirementHandler.puml
!include .\\Mix.Identity\Data\ApplicationDbContext.puml
!include .\\Mix.Identity\Data\ClaimData.puml
!include .\\Mix.Identity\Entities\Client.puml
!include .\\Mix.Identity\Entities\RefreshToken.puml
!include .\\Mix.Identity\Infrastructure\ApplicationUserManager.puml
!include .\\Mix.Identity\Infrastructure\ExtendedClaimsProvider.puml
!include .\\Mix.Identity\Interfaces\IUser.puml
!include .\\Mix.Identity\Models\ApplicationUser.puml
!include .\\Mix.Identity\Models\AspNetUser.puml
!include .\\Mix.Identity\Repositories\AuthRepository.puml
!include .\\Mix.Identity\Services\EmailSender.puml
!include .\\Mix.Identity\Services\ISmsSender.puml
!include .\\Mix.Identity\Services\MessageServices.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiAccountController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiAttributeDataController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiAttributeFieldController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiAttributeSetController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiConfigurationController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiCultureController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiFileController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiInitCmsController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiMediaController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiModuleController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiModuleDataController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiModulePostController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiPagePostController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiPermissionController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiPortalController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiRoleController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiTemplateController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiThemeController.puml
!include .\\Mix.Cms.Api\Controllers\v1\ApiUrlAliasController.puml
!include .\\Mix.Cms.Api\Controllers\v1\BaseApiControoler.puml
!include .\\Mix.Cms.Api\Controllers\v1\BaseGenericApiController.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Interfaces\IDatabaseMetadata.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Interfaces\ITableNameLookup.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Models\ColumnMetadata.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Models\DatabaseMetadata.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Models\QueryRequest.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Models\TableMetadata.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Models\TableNameLookup.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Providers\DynamicLinqProvider.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Resolvers\MyFieldResolver.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Resolvers\NameFieldResolver.puml
!include .\\Mix.Cms.Api.GraphQL\Infrastructure\Types\TableType.puml
!include .\\Mix.Cms.Lib\Migrations\MixCmsAccount\20200312035845_Init.puml
!include .\\Mix.Cms.Lib\Migrations\MixCmsAccount\20200312035845_Init.Designer.puml
!include .\\Mix.Cms.Lib\Migrations\MixCmsAccount\MixCmsAccountContextModelSnapshot.puml
!include .\\Mix.Cms.Lib\Migrations\MixMessenger\20181119151731_init.puml
!include .\\Mix.Cms.Lib\Migrations\MixMessenger\20181119151731_init.Designer.puml
!include .\\Mix.Cms.Lib\Migrations\MixMessenger\MixChatServiceContextModelSnapshot.puml
!include .\\Mix.Cms.Lib\Migrations\MsSqlMixCms\20210107122622_Init.puml
!include .\\Mix.Cms.Lib\Migrations\MsSqlMixCms\20210107122622_Init.Designer.puml
!include .\\Mix.Cms.Lib\Migrations\MsSqlMixCms\MsSqlMixCmsContextModelSnapshot.puml
!include .\\Mix.Cms.Lib\Migrations\MySqlMixCms\20201227053439_Init.puml
!include .\\Mix.Cms.Lib\Migrations\MySqlMixCms\20201227053439_Init.Designer.puml
!include .\\Mix.Cms.Lib\Migrations\MySqlMixCms\MySqlMixCmsContextModelSnapshot.puml
!include .\\Mix.Cms.Lib\Migrations\PostgresqlMixCms\20210119170618_Init.puml
!include .\\Mix.Cms.Lib\Migrations\PostgresqlMixCms\20210119170618_Init.Designer.puml
!include .\\Mix.Cms.Lib\Migrations\PostgresqlMixCms\PostgresqlMixCmsContextModelSnapshot.puml
!include .\\Mix.Cms.Lib\Migrations\PostgresSQLAccount\20210122053253_Init.puml
!include .\\Mix.Cms.Lib\Migrations\PostgresSQLAccount\20210122053253_Init.Designer.puml
!include .\\Mix.Cms.Lib\Migrations\PostgresSQLAccount\PostgresSQLAccountContextModelSnapshot.puml
!include .\\Mix.Cms.Lib\Migrations\SQLAccount\20200312035845_Init.puml
!include .\\Mix.Cms.Lib\Migrations\SQLAccount\20200312035845_Init.Designer.puml
!include .\\Mix.Cms.Lib\Migrations\SQLAccount\MixCmsAccountContextModelSnapshot.puml
!include .\\Mix.Cms.Lib\Models\Account\AspNetRoleClaims.puml
!include .\\Mix.Cms.Lib\Models\Account\AspNetRoles.puml
!include .\\Mix.Cms.Lib\Models\Account\AspNetUserClaims.puml
!include .\\Mix.Cms.Lib\Models\Account\AspNetUserLogins.puml
!include .\\Mix.Cms.Lib\Models\Account\AspNetUserRoles.puml
!include .\\Mix.Cms.Lib\Models\Account\AspNetUsers.puml
!include .\\Mix.Cms.Lib\Models\Account\AspNetUserTokens.puml
!include .\\Mix.Cms.Lib\Models\Account\Clients.puml
!include .\\Mix.Cms.Lib\Models\Account\RefreshTokens.puml
!include .\\Mix.Cms.Lib\Models\Account\_MixCmsAccountContext.puml
!include .\\Mix.Cms.Lib\Models\Account\_MixDbContext.puml
!include .\\Mix.Cms.Lib\Models\Account\_PostgresSQLAccountContext.puml
!include .\\Mix.Cms.Lib\Models\Account\_SQLAccountContext.puml
!include .\\Mix.Cms.Lib\Models\Cms\Aspnetroleclaims.puml
!include .\\Mix.Cms.Lib\Models\Cms\Aspnetroles.puml
!include .\\Mix.Cms.Lib\Models\Cms\Aspnetuserclaims.puml
!include .\\Mix.Cms.Lib\Models\Cms\Aspnetuserlogins.puml
!include .\\Mix.Cms.Lib\Models\Cms\Aspnetuserroles.puml
!include .\\Mix.Cms.Lib\Models\Cms\Aspnetusers.puml
!include .\\Mix.Cms.Lib\Models\Cms\Aspnetusertokens.puml
!include .\\Mix.Cms.Lib\Models\Cms\Clients.puml
!include .\\Mix.Cms.Lib\Models\Cms\Efmigrationshistory.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixAttributeField.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixAttributeSet.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixAttributeSetData.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixAttributeSetReference.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixAttributeSetValue.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixCache.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixCmsUser.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixConfiguration.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixCulture.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixFile.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixLanguage.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixMedia.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixMessengerHubRoom.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixMessengerMessage.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixMessengerNavRoomUser.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixMessengerNavTeamUser.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixMessengerTeam.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixMessengerUser.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixMessengerUserDevice.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixModule.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixModuleData.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixModulePost.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixPage.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixPageModule.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixPagePost.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixPortalPage.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixPortalPageNavigation.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixPortalPageRole.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixPost.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixPostMedia.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixPostModule.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixRelatedAttributeData.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixRelatedAttributeSet.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixRelatedData.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixRelatedPost.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixTemplate.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixTheme.puml
!include .\\Mix.Cms.Lib\Models\Cms\MixUrlAlias.puml
!include .\\Mix.Cms.Lib\Models\Cms\Refreshtokens.puml
!include .\\Mix.Cms.Lib\Models\Cms\_MixCmsContext.puml
!include .\\Mix.Cms.Lib\Models\Cms\_MsSqlMixCmsContext.puml
!include .\\Mix.Cms.Lib\Models\Cms\_MySqlMixCmsContext.puml
!include .\\Mix.Cms.Lib\Models\Cms\_PostgresqlMixCmsContext.puml
!include .\\Mix.Cms.Lib\Models\Cms\_SqliteMixCmsContext.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\IdentityModels.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\MixRegisterViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\NavUserRoleViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\RefreshTokenViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\RoleViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\UserInfoViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\UserRoleViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\Init\InitCmsViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeFields\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeFields\FieldConfigurations.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeFields\HubViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeFields\MobileViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeFields\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeFields\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\AdditionalViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\ExportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\FormViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\NavigationViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDatas\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDataValues\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDataValues\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDataValues\HubViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDataValues\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDataValues\MobileViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDataValues\NavigationViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDataValues\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDataValues\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSetDataValues\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSets\ContentUpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSets\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSets\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSets\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSets\ReadMvcArticleViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSets\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSets\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixAttributeSets\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixConfigurations\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixConfigurations\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixConfigurations\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixConfigurations\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixConfigurations\SystemConfigurationViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixConfigurations\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixCultures\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixCultures\SystemCultureViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixCultures\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixLanguages\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixLanguages\MobileViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixLanguages\ReadAndroidViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixLanguages\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixLanguages\SystemLanguageViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixLanguages\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixMedias\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixMedias\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModuleDatas\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModuleDatas\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModuleDatas\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModuleDatas\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModuleDatas\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModulePosts\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModulePosts\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModulePosts\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModules\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModules\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModules\ReadListItemViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModules\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixModules\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPageModules\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPageModules\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPagePosts\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPagePosts\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPagePosts\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPagePosts\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPages\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPages\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPages\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPages\ReadListItemViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPages\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPages\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPages\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPortalPagePortalPages\ReadPermissionViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPortalPagePortalPages\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPortalPagePortalPages\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPortalPageRoles\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPortalPages\ReadRolePermissionViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPortalPages\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPortalPages\UpdateRolePermissionViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPortalPages\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPostMedias\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPostModules\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPostPosts\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPosts\CreateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPosts\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPosts\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPosts\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPosts\ReadListItemViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPosts\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPosts\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPosts\SyncViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixPosts\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeDatas\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeDatas\FormViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeDatas\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeDatas\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeDatas\NavigationViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeDatas\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeDatas\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeDatas\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeSets\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeSets\ReadMvcViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeSets\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixRelatedAttributeSets\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixTemplates\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixTemplates\ImportViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixTemplates\InitViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixTemplates\ReadListItemViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixTemplates\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixTemplates\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixThemes\DeleteViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixThemes\Helper.puml
!include .\\Mix.Cms.Lib\ViewModels\MixThemes\InitViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixThemes\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixThemes\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\MixUrlAliases\UpdateViewModel.puml
!include .\\Mix.Cms.Service.SignalR\Models\VideoChat\CallOffer.puml
!include .\\Mix.Cms.Service.SignalR\Models\VideoChat\User.puml
!include .\\Mix.Cms.Service.SignalR\Models\VideoChat\UserCall.puml
!include .\\Mix.Cms.Service.SignalR\ViewModels\MixAttributeSetDatas\FormViewModel.puml
!include .\\Mix.Cms.Service.SignalR\ViewModels\MixAttributeSetDatas\ReadViewModel.puml
!include .\\Mix.Cms.Service.SignalR\ViewModels\MixMessengerUserDevices\DefaultViewModel.puml
!include .\\Mix.Cms.Service.SignalR\ViewModels\MixMessengerUsers\ConnectViewModel.puml
!include .\\Mix.Cms.Service.SignalR\ViewModels\MixMessengerUsers\DefaultViewModel.puml
!include .\\Mix.Cms.Web\App_Start\Validattors\CookieValidator.puml
!include .\\Mix.Cms.Web\App_Start\Validattors\JwtValidator.puml
!include .\\Mix.Identity\Models\AccountViewModels\CreateRoleBindingModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\ExternalLoginConfirmationViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\ExternalLoginViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\ForgotPasswordViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\LoginViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\LoginWith2faViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\LoginWithRecoveryCodeViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\RegisterViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\ResetPasswordViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\SendCodeViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\UserRoleModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\UsersInRoleModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\UserViewModel.puml
!include .\\Mix.Identity\Models\AccountViewModels\VerifyCodeViewModel.puml
!include .\\Mix.Identity\Models\ManageViewModels\AddPhoneNumberViewModel.puml
!include .\\Mix.Identity\Models\ManageViewModels\ChangePasswordViewModel.puml
!include .\\Mix.Identity\Models\ManageViewModels\ConfigureTwoFactorViewModel.puml
!include .\\Mix.Identity\Models\ManageViewModels\FactorViewModel.puml
!include .\\Mix.Identity\Models\ManageViewModels\IndexViewModel.puml
!include .\\Mix.Identity\Models\ManageViewModels\ManageLoginsViewModel.puml
!include .\\Mix.Identity\Models\ManageViewModels\RemoveLoginViewModel.puml
!include .\\Mix.Identity\Models\ManageViewModels\SetPasswordViewModel.puml
!include .\\Mix.Identity\Models\ManageViewModels\VerifyPhoneNumberViewModel.puml
!include .\\Mix.Cms.Api\Controllers\v1\Mix\BaseRestApiController.puml
!include .\\Mix.Cms.Api\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Api\obj\Debug\net5.0\Mix.Cms.Api.AssemblyInfo.puml
!include .\\Mix.Cms.Api\obj\Debug\net5.0\Mix.Cms.Api.MvcApplicationPartsAssemblyInfo.puml
!include .\\Mix.Cms.Api\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Api\obj\Release\net5.0\Mix.Cms.Api.AssemblyInfo.puml
!include .\\Mix.Cms.Api\obj\Release\net5.0\Mix.Cms.Api.MvcApplicationPartsAssemblyInfo.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\AttributeSetDatas\ApiAttributeSetDataController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\AttributeSetDatas\AttributeSetDataMvcController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\AttributeSetDatas\AttributeSetDataPortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\AttributeSetFields\ApiAttributeSetFieldController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\AttributeSets\ApiAttributeSetController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\AttributeSets\ApiAttributeSetPortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\AttributeSetValues\ApiAttributeSetValueController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\Configurations\ApiConfigurationPortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\Languages\ApiLanguageController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\ModuleDatas\ApiModuleDataMvcController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\ModuleDatas\ApiModuleDataPortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\ModulePosts\ApiModulePostMvcController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\Modules\ApiModuleMvcController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\Modules\ApiModulePortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\PagePosts\ApiPagePostMvcController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\Pages\ApiPagePortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\PortalPageNavigation\ApiPortalPageNavigationPortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\PortalPages\ApiPortalPagePortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\Posts\ApiPostMvcController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\Posts\ApiPostPortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\RelatedAttributeData\ApiRelatedAttributeDataPortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\RelatedAttributeSet\ApiRelatedAttributeSetPortalController.puml
!include .\\Mix.Cms.Api.RestFul\Controllers\v1\Templates\ApiTemplatesPortalController.puml
!include .\\Mix.Cms.Api.RestFul\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Api.RestFul\obj\Debug\net5.0\Mix.Cms.Api.RestFul.AssemblyInfo.puml
!include .\\Mix.Cms.Api.RestFul\obj\Debug\net5.0\Mix.Cms.Api.RestFul.MvcApplicationPartsAssemblyInfo.puml
!include .\\Mix.Cms.Api.RestFul\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Api.RestFul\obj\Release\net5.0\Mix.Cms.Api.RestFul.AssemblyInfo.puml
!include .\\Mix.Cms.Api.RestFul\obj\Release\net5.0\Mix.Cms.Api.RestFul.MvcApplicationPartsAssemblyInfo.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixAttributeFieldConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixAttributeSetConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixAttributeSetDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixAttributeSetReferenceConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixAttributeSetValueConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixAttributeValueConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixCacheConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixCmsUserConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixConfigurationConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixCultureConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixFileConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixLanguageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixMediaConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixModuleDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixModulePostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixPageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixPageModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixPagePostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixPortalPageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixPortalPageNavigationConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixPortalPageRoleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixPostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixPostMediaConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixPostModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixRelatedAttributeDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixRelatedAttributeSetConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixRelatedDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixRelatedPostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixTemplateConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixThemeConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MSSQL\MixUrlAliasConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixAttributeFieldConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixAttributeSetConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixAttributeSetDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixAttributeSetReferenceConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixAttributeSetValueConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixAttributeValueConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixCacheConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixCmsUserConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixConfigurationConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixCultureConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixFileConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixLanguageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixMediaConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixModuleDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixModulePostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixPageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixPageModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixPagePostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixPortalPageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixPortalPageNavigationConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixPortalPageRoleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixPostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixPostMediaConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixPostModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixRelatedAttributeDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixRelatedAttributeSetConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixRelatedDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixRelatedPostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixTemplateConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixThemeConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\MySQL\MixUrlAliasConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixAttributeFieldConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixAttributeSetConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixAttributeSetDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixAttributeSetReferenceConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixAttributeSetValueConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixAttributeValueConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixCacheConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixCmsUserConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixConfigurationConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixCultureConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixFileConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixLanguageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixMediaConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixModuleDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixModulePostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixPageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixPageModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixPagePostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixPortalPageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixPortalPageNavigationConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixPortalPageRoleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixPostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixPostMediaConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixPostModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixRelatedAttributeDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixRelatedAttributeSetConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixRelatedDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixRelatedPostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixTemplateConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixThemeConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\POSTGRESQL\MixUrlAliasConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixAttributeFieldConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixAttributeSetConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixAttributeSetDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixAttributeSetReferenceConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixAttributeSetValueConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixAttributeValueConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixCacheConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixCmsUserConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixConfigurationConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixCultureConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixFileConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixLanguageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixMediaConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixModuleDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixModulePostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixPageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixPageModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixPagePostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixPortalPageConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixPortalPageNavigationConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixPortalPageRoleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixPostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixPostMediaConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixPostModuleConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixRelatedAttributeDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixRelatedAttributeSetConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixRelatedDataConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixRelatedPostConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixTemplateConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixThemeConfiguration.puml
!include .\\Mix.Cms.Lib\Models\EntityConfigurations\SQLITE\MixUrlAliasConfiguration.puml
!include .\\Mix.Cms.Lib\Models\Messenger\Data\MixMessengerHubRoom.puml
!include .\\Mix.Cms.Lib\Models\Messenger\Data\MixMessengerMessage.puml
!include .\\Mix.Cms.Lib\Models\Messenger\Data\MixMessengerNavRoomUser.puml
!include .\\Mix.Cms.Lib\Models\Messenger\Data\MixMessengerNavTeamUser.puml
!include .\\Mix.Cms.Lib\Models\Messenger\Data\MixMessengerTeam.puml
!include .\\Mix.Cms.Lib\Models\Messenger\Data\MixMessengerUser.puml
!include .\\Mix.Cms.Lib\Models\Messenger\Data\MixMessengerUserDevice.puml
!include .\\Mix.Cms.Lib\Models\Messenger\Data\_MixChatServiceContext.puml
!include .\\Mix.Cms.Lib\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Lib\obj\Debug\net5.0\Mix.Cms.Lib.AssemblyInfo.puml
!include .\\Mix.Cms.Lib\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Lib\obj\Release\net5.0\Mix.Cms.Lib.AssemblyInfo.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\MixRoles\ReadViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\MixRoles\UpdateViewModel.puml
!include .\\Mix.Cms.Lib\ViewModels\Account\MixUsers\UpdateViewModel.puml
!include .\\Mix.Cms.Schedule\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Schedule\obj\Debug\net5.0\Mix.Cms.Schedule.AssemblyInfo.puml
!include .\\Mix.Cms.Schedule\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Schedule\obj\Release\net5.0\Mix.Cms.Schedule.AssemblyInfo.puml
!include .\\Mix.Cms.Service.SignalR\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Service.SignalR\obj\Debug\net5.0\Mix.Cms.Service.SignalR.AssemblyInfo.puml
!include .\\Mix.Cms.Service.SignalR\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Service.SignalR\obj\Release\net5.0\Mix.Cms.Service.SignalR.AssemblyInfo.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Mix.Cms.Web.AssemblyInfo.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Mix.Cms.Web.MvcApplicationPartsAssemblyInfo.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Mix.Cms.Web.RazorAssemblyInfo.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Mix.Cms.Web.RazorTargetAssemblyInfo.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Mix.Cms.Web.AssemblyInfo.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Mix.Cms.Web.MvcApplicationPartsAssemblyInfo.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Mix.Cms.Web.RazorAssemblyInfo.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Mix.Cms.Web.RazorTargetAssemblyInfo.puml
!include .\\Mix.Heart.NetCore\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Heart.NetCore\obj\Debug\net5.0\Mix.Heart.NetCore.AssemblyInfo.puml
!include .\\Mix.Heart.NetCore\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Heart.NetCore\obj\Release\net5.0\Mix.Heart.NetCore.AssemblyInfo.puml
!include .\\Mix.Identity\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Identity\obj\Debug\net5.0\Mix.Identity.AssemblyInfo.puml
!include .\\Mix.Identity\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Mix.Identity\obj\Debug\netcoreapp3.1\Mix.Identity.AssemblyInfo.puml
!include .\\Mix.Identity\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\Mix.Identity\obj\Release\net5.0\Mix.Identity.AssemblyInfo.puml
!include .\\Mix.Identity\obj\Release\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Mix.Identity\obj\Release\netcoreapp3.1\Mix.Identity.AssemblyInfo.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\_ViewImports.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\_ViewStart.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\wwwroot\_ProductDetailImages.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\_ViewImports.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\_ViewStart.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\wwwroot\_ProductDetailImages.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Data\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Home\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Home\Module.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Init\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Module\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Page\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Portal\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Post\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Security\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Shared\Error.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Shared\_Layout.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Shared\_LayoutInit_Angular.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Shared\_LayoutPortal_Angular.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Shared\_LayoutPortal_Angular_bk.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Shared\_LayoutSecurity_Angular.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Shared\_LoginPartial.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Shared\_ValidationScriptsPartial.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Debug\net5.0\Razor\Views\Vue\VueComponent.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Data\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Home\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Home\Module.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Init\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Module\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Page\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Portal\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Post\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Security\Index.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Shared\Error.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Shared\_Layout.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Shared\_LayoutInit_Angular.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Shared\_LayoutPortal_Angular.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Shared\_LayoutPortal_Angular_bk.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Shared\_LayoutSecurity_Angular.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Shared\_LoginPartial.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Shared\_ValidationScriptsPartial.cshtml.g.puml
!include .\\Mix.Cms.Web\obj\Release\net5.0\Razor\Views\Vue\VueComponent.cshtml.g.puml
@enduml
