@startuml
class HubViewModel {
    + Id : string <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Cultures : List<Domain.Core.Models.SupportedCulture> <<get>> <<set>>
    + AttributeFieldId : int <<get>> <<set>>
    + Regex : string <<get>> <<set>>
    + DataType : MixEnums.MixDataType <<get>> <<set>>
    + Status : string <<get>> <<set>>
    + AttributeFieldName : string <<get>> <<set>>
    + AttributeSetName : string <<get>> <<set>>
    + BooleanValue : bool? <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + DataId : string <<get>> <<set>>
    + DateTimeValue : DateTime? <<get>> <<set>>
    + DoubleValue : double? <<get>> <<set>>
    + IntegerValue : int? <<get>> <<set>>
    + StringValue : string <<get>> <<set>>
    + EncryptValue : string <<get>> <<set>>
    + EncryptKey : string <<get>> <<set>>
    + EncryptType : int <<get>> <<set>>
    + Field : MixAttributeFields.ReadViewModel <<get>> <<set>>
    + DataNavs : List<MixRelatedAttributeDatas.HubViewModel> <<get>> <<set>>
    + HubViewModel()
    + HubViewModel(model:MixAttributeSetValue, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixAttributeSetValue
    + <<override>> Validate(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
"ViewModelBase`3" "<MixCmsContext,MixAttributeSetValue,HubViewModel>" <|-- HubViewModel
@enduml
