@startuml
class UpdateViewModel {
    + Id : string <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + AttributeFieldId : int <<get>> <<set>>
    + Regex : string <<get>> <<set>>
    + DataType : MixDataType <<get>> <<set>>
    + AttributeFieldName : string <<get>> <<set>>
    + AttributeSetName : string <<get>> <<set>>
    + BooleanValue : bool? <<get>> <<set>>
    + DataId : string <<get>> <<set>>
    + DateTimeValue : DateTime? <<get>> <<set>>
    + DoubleValue : double? <<get>> <<set>>
    + IntegerValue : int? <<get>> <<set>>
    + StringValue : string <<get>> <<set>>
    + EncryptValue : string <<get>> <<set>>
    + EncryptKey : string <<get>> <<set>>
    + EncryptType : int <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + Field : MixAttributeFields.UpdateViewModel <<get>> <<set>>
    + UpdateViewModel()
    + UpdateViewModel(model:MixAttributeSetValue, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixAttributeSetValue
    - ParseDefaultValue(defaultValue:string) : void
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + <<override>> Validate(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
"ViewModelBase`3" "<MixCmsContext,MixAttributeSetValue,UpdateViewModel>" <|-- UpdateViewModel
@enduml
