@startuml
class Helper {
    + {static} <<async>> GetModelistByMeta(metaName:string, metaValue:string, culture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<TView>>>
    + {static} <<async>> GetPostListByValueId(valueId:string, culture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<TView>>>
    + {static} <<async>> GetPostListByValueIds(valueIds:List<string>, culture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<TView>>>
    + {static} <<async>> GetPostListByPageId(pageId:int, keyword:string, culture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<TView>>>
    + {static} <<async>> GetPostListByDataId(dataId:string, culture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<TView>>>
    + {static} <<async>> GetPostListByDataIds(dataIds:List<string>, culture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<TView>>>
    + {static} <<async>> SearchPost(keyword:string, dataIds:List<string>, pageIds:List<int>, culture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<TView>>>
    + {static} <<async>> GetModelistByAdditionalField(fieldName:string, value:string, culture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<TView>>>
    + {static} <<async>> PublishScheduledPosts() : Task
}
@enduml
