@startuml
class ApiFileController {
    + ApiFileController(context:MixCmsContext, memoryCache:IMemoryCache, hubContext:Microsoft.AspNetCore.SignalR.IHubContext<Mix.Cms.Service.SignalR.Hubs.PortalHub>)
    + Details(folder:string, filename:string) : RepositoryResponse<FileViewModel>
    + Delete() : RepositoryResponse<bool>
    + Upload(folder:string, file:IFormFile) : IActionResult
    + Save(model:FileViewModel) : RepositoryResponse<FileViewModel>
    + GetList(request:RequestPaging) : RepositoryResponse<FilePageViewModel>
}
class "BaseApiController`1"<T> {
}
"BaseApiController`1" "<MixCmsContext>" <|-- ApiFileController
@enduml
