@startuml
class ApiUrlAliasController {
    + ApiUrlAliasController(context:MixCmsContext, memoryCache:IMemoryCache, hubContext:Microsoft.AspNetCore.SignalR.IHubContext<Mix.Cms.Service.SignalR.Hubs.PortalHub>)
    + <<async>> DeleteAsync(id:int) : Task<RepositoryResponse<MixUrlAlias>>
    + <<async>> Details(viewType:string, id:int?) : Task<ActionResult<JObject>>
    + <<async>> Save(model:UpdateViewModel) : Task<RepositoryResponse<UpdateViewModel>>
    + <<async>> GetList(request:RequestPaging) : Task<ActionResult<JObject>>
}
class "BaseGenericApiController`2"<T1,T2> {
}
"BaseGenericApiController`2" "<MixCmsContext,MixUrlAlias>" <|-- ApiUrlAliasController
@enduml
