@startuml
class ApiPortalPageNavigationPortalController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<ReadViewModel>>>
}
"BaseAuthorizedRestApiController`4" "<MixCmsContext,MixPortalPageNavigation,UpdateViewModel,ReadViewModel>" <|-- ApiPortalPageNavigationPortalController
@enduml
