@startuml
class ServiceCollectionExtensions <<static>> {
    + {static} AddMixRestApi(services:IServiceCollection) : IServiceCollection
    + {static} UseMixRestApi(app:IApplicationBuilder) : IApplicationBuilder
}
@enduml
