@startuml
class MethodRules {
    + {static} RedirectXMLRequests(context:RewriteContext) : void
}
class RedirectImageRequests {
    - <<readonly>> _extension : string
    - <<readonly>> _newPath : PathString
    + RedirectImageRequests(extension:string, newPath:string)
    + ApplyRule(context:RewriteContext) : void
}
IRule <|-- RedirectImageRequests
@enduml
