@startuml
class Helper {
    + {static} <<async>> ExportTheme(id:int, data:SiteStructureViewModel, culture:string, scheme:string, host:string) : Task<RepositoryResponse<string>>
    + {static} <<async>> InitTheme(model:string, culture:string, assets:IFormFile, theme:IFormFile) : Task<RepositoryResponse<InitViewModel>>
}
@enduml
