@startuml
class ManageLoginsViewModel {
}
class "IList`1"<T> {
}
ManageLoginsViewModel --> "CurrentLogins<UserLoginInfo>" "IList`1"
ManageLoginsViewModel --> "OtherLogins<AuthenticationScheme>" "IList`1"
@enduml
