@startuml
class ReadViewModel {
    + Id : string <<get>> <<set>>
    + ConcurrencyStamp : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + NormalizedName : string <<get>> <<set>>
    + ReadViewModel()
    + ReadViewModel(model:AspNetRoles, _context:MixCmsAccountContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsAccountContext, _transaction:IDbContextTransaction) : AspNetRoles
    + <<override>> <<async>> RemoveRelatedModelsAsync(view:ReadViewModel, _context:MixCmsAccountContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<bool>>
    + <<override>> ExpandView(_context:MixCmsAccountContext, _transaction:IDbContextTransaction) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsAccountContext,AspNetRoles,ReadViewModel>" <|-- ReadViewModel
ReadViewModel --> "Permissions<MixPortalPages.ReadRolePermissionViewModel>" "List`1"
@enduml
