@startuml
class ApiAttributeFieldController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<ReadViewModel>>>
    + <<async>> Init(attributeSet:string) : Task<ActionResult<PaginationModel<UpdateViewModel>>>
}
class "BaseAuthorizedRestApiController`5"<T1,T2,T3,T4,T5> {
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixAttributeField,UpdateViewModel,ReadViewModel,DeleteViewModel>" <|-- ApiAttributeFieldController
@enduml
