@startuml
class ImportViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Icon : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Excerpt : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + SeoName : string <<get>> <<set>>
    + SeoTitle : string <<get>> <<set>>
    + SeoDescription : string <<get>> <<set>>
    + SeoKeywords : string <<get>> <<set>>
    + Source : string <<get>> <<set>>
    + Views : int? <<get>> <<set>>
    + Type : string <<get>> <<set>>
    + PublishedDateTime : DateTime? <<get>> <<set>>
    + Tags : string <<get>> <<set>> = "[]"
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Domain : string <<get>>
    + ImportViewModel()
    + ImportViewModel(model:MixPost, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixPost,ImportViewModel>" <|-- ImportViewModel
ImportViewModel --> "Cultures<Domain.Core.Models.SupportedCulture>" "List`1"
ImportViewModel --> "CreatedDateTime" DateTime
ImportViewModel --> "Status" MixContentStatus
ImportViewModel --> "Pages<MixPagePosts.ReadViewModel>" "List`1"
ImportViewModel --> "Modules<MixModulePosts.ReadViewModel>" "List`1"
ImportViewModel --> "MediaNavs<MixPostMedias.ReadViewModel>" "List`1"
ImportViewModel --> "PostNavs<MixPostPosts.ReadViewModel>" "List`1"
ImportViewModel o-> "ListTag" JArray
ImportViewModel --> "SysCategories<MixRelatedAttributeDatas.FormViewModel>" "List`1"
ImportViewModel --> "SysTags<MixRelatedAttributeDatas.FormViewModel>" "List`1"
ImportViewModel --> "UrlAliases<MixUrlAliases.UpdateViewModel>" "List`1"
@enduml
