@startuml
class ReadListItemViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + Icon : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Excerpt : string <<get>> <<set>>
    + SeoName : string <<get>> <<set>>
    + SeoTitle : string <<get>> <<set>>
    + SeoDescription : string <<get>> <<set>>
    + SeoKeywords : string <<get>> <<set>>
    + Source : string <<get>> <<set>>
    + Views : int? <<get>> <<set>>
    + Type : string <<get>> <<set>>
    + PublishedDateTime : DateTime? <<get>> <<set>>
    + Tags : string <<get>> <<set>> = "[]"
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + DetailsUrl : string <<get>>
    + Domain : string <<get>>
    + ImageUrl : string <<get>>
    + ThumbnailUrl : string <<get>>
    + ReadListItemViewModel()
    + ReadListItemViewModel(model:MixPost, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + Property(fieldName:string) : T
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixPost,ReadListItemViewModel>" <|-- ReadListItemViewModel
ReadListItemViewModel --> "Cultures<Domain.Core.Models.SupportedCulture>" "List`1"
ReadListItemViewModel --> "CreatedDateTime" DateTime
ReadListItemViewModel --> "Status" MixContentStatus
ReadListItemViewModel o-> "SysTags<MixRelatedAttributeDatas.FormViewModel>" "List`1"
ReadListItemViewModel o-> "SysCategories<MixRelatedAttributeDatas.FormViewModel>" "List`1"
ReadListItemViewModel --> "ListTag<string>" "List`1"
ReadListItemViewModel --> "ListCategory<string>" "List`1"
ReadListItemViewModel --> "Pages<MixPagePosts.ReadViewModel>" "List`1"
@enduml
