@startuml
class ReadViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + ExtraFields : string <<get>> <<set>> = "[]"
    + ExtraProperties : string <<get>> <<set>> = "[]"
    + Icon : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Excerpt : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + SeoName : string <<get>> <<set>>
    + SeoTitle : string <<get>> <<set>>
    + SeoDescription : string <<get>> <<set>>
    + SeoKeywords : string <<get>> <<set>>
    + Source : string <<get>> <<set>>
    + Views : int? <<get>> <<set>>
    + Type : string <<get>> <<set>>
    + PublishedDateTime : DateTime? <<get>> <<set>>
    + Tags : string <<get>> <<set>> = "[]"
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Domain : string <<get>>
    + ImageUrl : string <<get>>
    + ThumbnailUrl : string <<get>>
    + DetailsUrl : string <<get>>
    + ReadViewModel()
    + ReadViewModel(model:MixPost, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + Property(name:string) : string
    + {static} <<async>> GetModelListByCategoryAsync(pageId:int, specificulture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, skip:int?, top:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<ReadViewModel>>>
    + {static} GetModelListByCategory(pageId:int, specificulture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<PaginationModel<ReadViewModel>>
    + {static} GetModelListByModule(ModuleId:int, specificulture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<PaginationModel<ReadViewModel>>
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + Property(fieldName:string) : T
}
class "ViewModelBase`3"<T1,T2,T3> {
}
class "List`1"<T> {
}
"ViewModelBase`3" "<MixCmsContext,MixPost,ReadViewModel>" <|-- ReadViewModel
ReadViewModel --> "Cultures<Domain.Core.Models.SupportedCulture>" "List`1"
ReadViewModel --> "CreatedDateTime" DateTime
ReadViewModel --> "Status" MixContentStatus
ReadViewModel --> "Properties<ExtraProperty>" "List`1"
ReadViewModel o-> "SysTags<MixRelatedAttributeDatas.FormViewModel>" "List`1"
ReadViewModel o-> "SysCategories<MixRelatedAttributeDatas.FormViewModel>" "List`1"
ReadViewModel --> "ListTag<string>" "List`1"
ReadViewModel --> "ListCategory<string>" "List`1"
@enduml
