@startuml
class MixChatHub {
    - <<const>> defaultRoom : string = "public"
    - <<const>> defaultDevice : string = "website"
    + Join(request:HubRequest<MessengerConnection>) : void
    + SendMessage(request:JObject) : void
    + SendMessageToCaller(message:string) : Task
    + SendMessageToGroups(message:string) : Task
    - SendToConnection(message:T, action:MessageReponseKey, connectionId:string, isMySelf:bool) : void
    - SendToCaller(message:T, action:MessageReponseKey) : void
    - SendToGroup(message:T, action:MessageReponseKey, groupName:string, isMySelf:bool) : void
    - SendToAll(message:T, action:MessageReponseKey, isMySelf:bool) : void
    - GetResponseKey(e:T) : string
    + <<override>> <<async>> OnConnectedAsync() : Task
    + <<override>> OnDisconnectedAsync(exception:Exception) : Task
}
BaseSignalRHub <|-- MixChatHub
@enduml
