@startuml
class DeleteViewModel {
    + Id : int <<get>> <<set>>
    + AttributeSetId : int <<get>> <<set>>
    + ParentId : int <<get>> <<set>>
    + Status : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + DeleteViewModel()
    + DeleteViewModel(model:MixRelatedAttributeSet, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixRelatedAttributeSet
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixCmsContext,MixRelatedAttributeSet,DeleteViewModel>" <|-- DeleteViewModel
DeleteViewModel --> "ParentType" MixDatabaseParentType
DeleteViewModel --> "CreatedDateTime" DateTime
@enduml
