@startuml
class MixAttributeValueConfiguration {
    + Configure(builder:EntityTypeBuilder<MixAttributeSetValue>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixAttributeSetValue>" <|-- MixAttributeValueConfiguration
@enduml
