@startuml
class MixFileConfiguration {
    + Configure(entity:EntityTypeBuilder<MixFile>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixFile>" <|-- MixFileConfiguration
@enduml
