@startuml
class MixRelatedAttributeDataConfiguration {
    + Configure(entity:EntityTypeBuilder<MixRelatedAttributeData>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixRelatedAttributeData>" <|-- MixRelatedAttributeDataConfiguration
@enduml
