@startuml
class MixTemplateConfiguration {
    + Configure(entity:EntityTypeBuilder<MixTemplate>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixTemplate>" <|-- MixTemplateConfiguration
@enduml
