@startuml
class MixAttributeSetConfiguration {
    + Configure(entity:EntityTypeBuilder<MixAttributeSet>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixAttributeSet>" <|-- MixAttributeSetConfiguration
@enduml
