@startuml
class Helper {
    + {static} GetNavAsync(postId:int, specificulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<List<MixPagePosts.ReadViewModel>>
    + {static} GetActivedNavAsync(postId:int?, pageId:int?, specificulture:string, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<List<TView>>
}
@enduml
