@startuml
class ApiLanguageController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<ReadMvcViewModel>>>
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixLanguage,UpdateViewModel,ReadMvcViewModel,UpdateViewModel>" <|-- ApiLanguageController
@enduml
