@startuml
class MixConfigurationConfiguration {
    + Configure(entity:EntityTypeBuilder<MixConfiguration>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixConfiguration>" <|-- MixConfigurationConfiguration
@enduml
