@startuml
class MixLanguageConfiguration {
    + Configure(entity:EntityTypeBuilder<MixLanguage>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixLanguage>" <|-- MixLanguageConfiguration
@enduml
