@startuml
class MixModuleConfiguration {
    + Configure(entity:EntityTypeBuilder<MixModule>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixModule>" <|-- MixModuleConfiguration
@enduml
