@startuml
class MixModuleDataConfiguration {
    + Configure(entity:EntityTypeBuilder<MixModuleData>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixModuleData>" <|-- MixModuleDataConfiguration
@enduml
