@startuml
class MixPortalPageRoleConfiguration {
    + Configure(entity:EntityTypeBuilder<MixPortalPageRole>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixPortalPageRole>" <|-- MixPortalPageRoleConfiguration
@enduml
