@startuml
class MixRelatedPostConfiguration {
    + Configure(entity:EntityTypeBuilder<MixRelatedPost>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixRelatedPost>" <|-- MixRelatedPostConfiguration
@enduml
