@startuml
class MixRelatedDataConfiguration {
    + Configure(entity:EntityTypeBuilder<MixRelatedData>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<MixRelatedData>" <|-- MixRelatedDataConfiguration
@enduml
