@startuml
interface MvcViewModel {
    + Id : int <<get>> <<set>>
    + Layout : string <<get>> <<set>>
    + SeoTitle : string <<get>> <<set>>
    + ThumbnailUrl : string <<get>>
    + SeoDescription : string <<get>> <<set>>
    + TemplatePath : string <<get>>
    + DetailsUrl : string <<get>>
    + View : ViewModels.MixTemplates.ReadListItemViewModel <<get>> <<set>>
}
@enduml
