@startuml
class ReadViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + Cultures : List<Domain.Core.Models.SupportedCulture> <<get>> <<set>>
    + Template : string <<get>> <<set>>
    + Thumbnail : string <<get>> <<set>>
    + Image : string <<get>> <<set>>
    + ExtraFields : string <<get>> <<set>> = "[]"
    + ExtraProperties : string <<get>> <<set>> = "[]"
    + Icon : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Excerpt : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + SeoName : string <<get>> <<set>>
    + SeoTitle : string <<get>> <<set>>
    + SeoDescription : string <<get>> <<set>>
    + SeoKeywords : string <<get>> <<set>>
    + Source : string <<get>> <<set>>
    + Views : int? <<get>> <<set>>
    + Type : string <<get>> <<set>>
    + PublishedDateTime : DateTime? <<get>> <<set>>
    + Tags : string <<get>> <<set>> = "[]"
    + CreatedBy : string <<get>> <<set>>
    + CreatedDateTime : DateTime <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + Status : MixContentStatus <<get>> <<set>>
    + Domain : string <<get>>
    + ImageUrl : string <<get>>
    + ThumbnailUrl : string <<get>>
    + DetailsUrl : string <<get>>
    + Properties : List<ExtraProperty> <<get>> <<set>>
    + AttributeData : MixRelatedAttributeDatas.ReadMvcViewModel <<get>> <<set>>
    + SysTags : List<MixRelatedAttributeDatas.FormViewModel> <<get>> <<set>>
    + SysCategories : List<MixRelatedAttributeDatas.FormViewModel> <<get>> <<set>>
    + ListTag : List<string> <<get>>
    + ListCategory : List<string> <<get>>
    + ReadViewModel()
    + ReadViewModel(model:MixPost, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + Property(name:string) : string
    + {static} <<async>> GetModelListByCategoryAsync(pageId:int, specificulture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, skip:int?, top:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : Task<RepositoryResponse<PaginationModel<ReadViewModel>>>
    + {static} GetModelListByCategory(pageId:int, specificulture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<PaginationModel<ReadViewModel>>
    + {static} GetModelListByModule(ModuleId:int, specificulture:string, orderByPropertyName:string, direction:Heart.Enums.MixHeartEnums.DisplayDirection, pageSize:int?, pageIndex:int?, _context:MixCmsContext, _transaction:IDbContextTransaction) : RepositoryResponse<PaginationModel<ReadViewModel>>
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    - LoadTags(context:MixCmsContext, transaction:IDbContextTransaction) : void
    - LoadCategories(context:MixCmsContext, transaction:IDbContextTransaction) : void
    - LoadAttributes(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + Property(fieldName:string) : T
}
"ViewModelBase`3" "<MixCmsContext,MixPost,ReadViewModel>" <|-- ReadViewModel
@enduml
