@startuml
class RefreshTokenViewModel {
    + Id : string <<get>> <<set>>
    + ClientId : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + RefreshTokenViewModel()
    + RefreshTokenViewModel(model:RefreshTokens, _context:MixCmsAccountContext, _transaction:IDbContextTransaction)
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixCmsAccountContext,RefreshTokens,RefreshTokenViewModel>" <|-- RefreshTokenViewModel
RefreshTokenViewModel --> "ExpiresUtc" DateTime
RefreshTokenViewModel --> "IssuedUtc" DateTime
@enduml
