@startuml
class AspNetRoles <<partial>> {
    + AspNetRoles()
    + Id : string <<get>> <<set>>
    + ConcurrencyStamp : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + NormalizedName : string <<get>> <<set>>
}
class "ICollection`1"<T> {
}
AspNetRoles --> "AspNetRoleClaims<AspNetRoleClaims>" "ICollection`1"
AspNetRoles --> "AspNetUserRoles<AspNetUserRoles>" "ICollection`1"
@enduml
