@startuml
class AspNetUserClaims <<partial>> {
    + Id : int <<get>> <<set>>
    + ApplicationUserId : string <<get>> <<set>>
    + ClaimType : string <<get>> <<set>>
    + ClaimValue : string <<get>> <<set>>
    + UserId : string <<get>> <<set>>
}
AspNetUserClaims --> "ApplicationUser" AspNetUsers
AspNetUserClaims --> "User" AspNetUsers
@enduml
