@startuml
class AspNetUserTokens <<partial>> {
    + UserId : string <<get>> <<set>>
    + LoginProvider : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Value : string <<get>> <<set>>
}
AspNetUserTokens --> "User" AspNetUsers
@enduml
