@startuml
class AspNetUserLogins <<partial>> {
    + LoginProvider : string <<get>> <<set>>
    + ProviderKey : string <<get>> <<set>>
    + ApplicationUserId : string <<get>> <<set>>
    + ProviderDisplayName : string <<get>> <<set>>
    + UserId : string <<get>> <<set>>
}
AspNetUserLogins --> "ApplicationUser" AspNetUsers
AspNetUserLogins --> "User" AspNetUsers
@enduml
