@startuml
class AspNetRoleClaims <<partial>> {
    + Id : int <<get>> <<set>>
    + ClaimType : string <<get>> <<set>>
    + ClaimValue : string <<get>> <<set>>
    + RoleId : string <<get>> <<set>>
}
AspNetRoleClaims --> "Role" AspNetRoles
@enduml
