@startuml
class RefreshTokens <<partial>> {
    + Id : string <<get>> <<set>>
    + ClientId : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + Username : string <<get>> <<set>>
}
RefreshTokens --> "ExpiresUtc" DateTime
RefreshTokens --> "IssuedUtc" DateTime
@enduml
