@startuml
class ApiRelatedAttributeDataPortalController {
    + <<override>> <<async>> Get() : Task<ActionResult<PaginationModel<FormViewModel>>>
    + <<async>> GetNavigation(name:string) : Task<ActionResult<Lib.ViewModels.MixAttributeSetDatas.Navigation>>
}
"BaseAuthorizedRestApiController`5" "<MixCmsContext,MixRelatedAttributeData,FormViewModel,FormViewModel,DeleteViewModel>" <|-- ApiRelatedAttributeDataPortalController
@enduml
