@startuml
class FieldConfigurations {
}
class UploadConfigurations {
    + Accepts : string <<get>>
    + Width : int? <<get>> <<set>>
    + Height : int? <<get>> <<set>>
    + IsCrop : bool <<get>> <<set>>
}
FieldConfigurations o-> "Upload" UploadConfigurations
UploadConfigurations o-> "ArrayAccepts" JArray
@enduml
