@startuml
class MobileViewModel {
    + Id : int <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + AttributeSetId : int <<get>> <<set>>
    + AttributeSetName : string <<get>> <<set>>
    + ReferenceId : int? <<get>> <<set>>
    + Regex : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + DefaultValue : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + IsRequire : bool <<get>> <<set>>
    + IsEncrypt : bool <<get>> <<set>>
    + IsSelect : bool <<get>> <<set>>
    + IsUnique : bool <<get>> <<set>>
    + Status : string <<get>> <<set>>
    + MobileViewModel()
    + MobileViewModel(model:MixAttributeField, _context:MixCmsContext, _transaction:IDbContextTransaction)
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixCmsContext,MixAttributeField,MobileViewModel>" <|-- MobileViewModel
MobileViewModel --> "CreatedDateTime" DateTime
@enduml
