@startuml
class UpdateViewModel {
    + Id : int <<get>> <<set>>
    + Specificulture : string <<get>> <<set>>
    + AttributeSetId : int <<get>> <<set>>
    + AttributeSetName : string <<get>> <<set>>
    + Configurations : string <<get>> <<set>>
    + ReferenceId : int? <<get>> <<set>>
    + Regex : string <<get>> <<set>>
    + IsRegex : bool <<get>>
    + Title : string <<get>> <<set>>
    + DefaultValue : string <<get>> <<set>>
    + Options : string <<get>> <<set>> = "[]"
    + Name : string <<get>> <<set>>
    + IsRequire : bool <<get>> <<set>>
    + IsEncrypt : bool <<get>> <<set>>
    + IsSelect : bool <<get>> <<set>>
    + IsUnique : bool <<get>> <<set>>
    + IsMultiple : bool <<get>> <<set>>
    + CreatedBy : string <<get>> <<set>>
    + ModifiedBy : string <<get>> <<set>>
    + LastModified : DateTime? <<get>> <<set>>
    + Priority : int <<get>> <<set>>
    + UpdateViewModel()
    + UpdateViewModel(model:MixAttributeField, _context:MixCmsContext, _transaction:IDbContextTransaction)
    + <<override>> Validate(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
    + <<override>> ParseModel(_context:MixCmsContext, _transaction:IDbContextTransaction) : MixAttributeField
    + <<override>> ExpandView(_context:MixCmsContext, _transaction:IDbContextTransaction) : void
}
class "ViewModelBase`3"<T1,T2,T3> {
}
"ViewModelBase`3" "<MixCmsContext,MixAttributeField,UpdateViewModel>" <|-- UpdateViewModel
UpdateViewModel --> "DataType" MixDataType
UpdateViewModel --> "JOptions" JArray
UpdateViewModel --> "CreatedDateTime" DateTime
UpdateViewModel --> "Status" MixContentStatus
UpdateViewModel o-> "FieldConfigurations" FieldConfigurations
@enduml
