@startuml
class PostController {
    # <<override>> ValidateRequest() : void
    + <<async>> Index(id:int, culture:string, seoName:string) : Task<IActionResult>
}
BaseController <|-- PostController
@enduml
