@startuml
class VueController {
    # <<override>> ValidateRequest() : void
    + <<async>> Index(culture:string, seoName:string) : Task<PartialViewResult>
}
BaseController <|-- VueController
@enduml
